### ISSUE TITLE
[Bug] AMS reports the same value for active regardless of which tray is in use.

### ISSUE THREAD

**Issue by CitizenRacer** [greghesp/ha-bambulab#101]
### Describe the bug

I *think* that all four trays are reporting the value for active that tray 1 is set to. Even if a tray is empty.

### To Reproduce

Print something and the active tray will be incorrect

### Expected Behaviour

I expect only the tray that is in use to be listed as active.

### What device are you using?

X1C

### Firmware Version

1.04.01.00

### Home Assistant Version

latest

### Component Version

v1.0.5

### Other Information

![Screenshot 2023-04-16 at 1 14 36 PM](https://user-images.githubusercontent.com/14790049/232339778-1ea172b3-e510-4213-8dcc-32952c51942f.png)

**Comment by AdrianGarside** [comment]
They are indeed! When I converted to storing these as attributes I missed a fix up after a cut and paste.

**Comment by CitizenRacer** [comment]
Brand also seems to not report anything. Sent from my mobileOn Apr 16, 2023, at 1:23 PM, AdrianGarside ***@***.***> wrote:﻿
They are indeed! When I converted to storing these as attributes I missed a fix up after a cut and paste.

**Comment by AdrianGarside** [comment]
Brand always comes back empty for me in the payload from the printer. Maybe I should ignore it for now since even if it does get populated in some cases its probably not useful if it’s usually going to be empty.

**Comment by AdrianGarside** [comment]
Fixed with #102
