### ISSUE TITLE
[Bug] 1.1.1-dev2 causes tons of exceptions

### ISSUE THREAD

**Issue by renssies** [greghesp/ha-bambulab#108]
### Describe the bug

I've turned on debugging and now Home Assistant is showing a ton of errors in the system log. 

![Screenshot 2023-04-21 at 16 36 20](https://user-images.githubusercontent.com/830094/233663881-5f13c270-2e83-4fc6-92b6-adf4be931ffa.png)

### To Reproduce

Install 1.1.1-dev2

### Expected Behaviour

A limited number of errors to show up, not 387 times the same error

### What device are you using?

X1C

### Home Assistant Version

2023.4.5

### Component Version

1.1.1-dev2

### Log Extracts

This error originated from a custom integration.

Logger: custom_components.bambu_lab.pybambu
Source: custom_components/bambu_lab/pybambu/bambu_client.py:36 
Integration: Bambu Lab (documentation, issues) 
First occurred: 4:14:14 PM (387 occurrences) 
Last logged: 4:35:42 PM

An exception occurred processing a message:
Exception type: <class 'ValueError'>
Exception args: ("invalid literal for int() with base 10: 'num:1,ams_exist:0x1,tray_now:'",)

**Comment by AdrianGarside** [comment]
Should be fixed with #110

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v1.1.1-dev3
