### ISSUE TITLE
[Bug] Start time briefly reports 1 January 1970 before printing

### ISSUE THREAD

**Issue by renssies** [greghesp/ha-bambulab#109]
### Describe the bug

The start time sensor sometimes jumps to the start of UTC 1 January 1970 before it returns to the previous value. It might be start the start time reports a 0 sometimes. To solve any values below 1000 should be filtered out.

![Screenshot 2023-04-21 at 16 57 37](https://user-images.githubusercontent.com/830094/233671009-1a86e9c1-3d4f-4ce7-b40b-6fa44cd3d0c5.png)

### To Reproduce

1. Start a print
2. Closely observe the start time entity while the printer is doing it's preparation steps such as bed leveling or extrusion calibration.

### Expected Behaviour

To not have the printer time travel back to 1 January 1970

### What device are you using?

X1C

### Home Assistant Version

2023.4.5

### Component Version

1.1.1-dev2

**Comment by renssies** [comment]
To add, the debug log values of all the MQTT messages just show `gcode_start_time` with a value above 1680000000

**Comment by AdrianGarside** [comment]
Should be fixed with #110

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v1.1.1-dev3
