### ISSUE TITLE
[Bug] Unknown Error when configuring

### ISSUE THREAD

**Issue by jonathanalevi** [greghesp/ha-bambulab#111]
### Describe the bug

<img width="451" alt="image" src="https://user-images.githubusercontent.com/1540530/233561498-5e8bf183-7a00-442b-9798-886dc9b824af.png">

### To Reproduce

Hit "Configure"
Choose any option
Click "Next"

### Expected Behaviour

It should configure the device...? 

### What device are you using?

X1C

### Firmware Version

01.04.01.00

### Home Assistant Version

Home Assistant 2023.4.5

### Component Version

Latest

**Comment by AdrianGarside** [comment]
What version? I had a bad merge in the v1.1.1-dev3 release.

**Comment by AdrianGarside** [comment]
Should be fixed with: https://github.com/greghesp/ha-bambulab/releases/tag/v1.1.1-dev10
