### ISSUE TITLE
[Feature] Add print file thumbnail from 3mf

### ISSUE THREAD

**Issue by greghesp** [greghesp/ha-bambulab#112]
### Describe the feature

The 3mf file Bambu Studio passes to the printer contains a thumbnail of the print. Extract this and expose as a sensor, or attribute 

### What device is this for?

X1C

### Other Information

This will require us to add an FTP connection to fetch the correct 3mf file, and extract it to Home Assistant

**Comment by AdrianGarside** [comment]
Python seems to be able to successfully connect and download files using the ftps lib in my testing.

**Comment by AdrianGarside** [comment]
python3 ./ftp.py

Connecting
List
['timelapse_2023-04-21_00-51.avi']
Downloading: 2023-04-21 23:42:20.204124
Done: 2023-04-21 23:43:33.593681

The ftps import is really just a very thin wrapper around pycurl - really it just tweaks the interaction and adds a 5x retry (which is questionable to do blindly):
https://github.com/jcollado/ftps/blob/master/ftps/ftps.py

**Comment by AdrianGarside** [comment]
python3 ./ftp.py

Connecting
List
['timelapse_2023-04-21_00-51.avi']
Downloading: 2023-04-21 23:42:20.204124
Done: 2023-04-21 23:43:33.593681

The ftps import is really just a very thin wrapper around pycurl - really it just tweaks the interaction and adds a 5x retry (which is questionable to do blindly):
https://github.com/jcollado/ftps/blob/master/ftps/ftps.py

**Comment by totalitarian** [comment]
Any plans to implement this? Would love to access both the thumbnail and download the time lapses

**Comment by jneilliii** [comment]
> The ftps import is really just a very thin wrapper around pycurl

please consider other alternatives, getting pycurl installed on windows seems to be a bit tricky.

**Comment by mehhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
This would be a great feature!

**Comment by AdrianGarside** [comment]
Fixed in v2.0.0.
