### ISSUE TITLE
[Bug] AMS Empty vs empty

### ISSUE THREAD

**Issue by jneilliii** [greghesp/ha-bambulab#119]
### Describe the bug

Was just curious if the AMS tray data is meant to have two different Empty properties or if this was a mishap?

![image](https://user-images.githubusercontent.com/5249455/233899872-f3b82430-82b2-451a-9c43-c38b68f7c08b.png)

### To Reproduce

1. Connect to X1C with AMS using pybambu module (not ha specific question)
2. Add breakpoint in callback on `event_printer_data_update`
3. `device_data = self.bambu_client.get_device()`
4. Evaluate the AMS data, and noticed multiple properties with different capitalization. 

### Expected Behaviour

Assuming these two properties are representing the same thing, it's getting set wrong in the models.py file on line https://github.com/greghesp/ha-bambulab/blob/09d986b045563ee1db16f5eb72c67366819b84e1/custom_components/bambu_lab/pybambu/models.py#L489

Personally I would probably make all of them lowercase for consistency with the other properties. 

### What device are you using?

X1C

### Firmware Version

1.04.01.00

### Home Assistant Version

0

### Component Version

1.1.2

### Other Information

As mentioned, not using your HA integration, but specifically utilizing the pybambu module since it's being actively developed here. One other thing I questioned is the imports for HA stuff in models.py is necessary or not for the HA integration, I have to remove that in my local download and doesn't seem to cause any issues doing so as they are not referenced within the module itself.

**Comment by AdrianGarside** [comment]
No, there's no reason to import HA types there. I did that temporarily to bootstrap some code and then failed to clean those imports up when I removed all the HA calls again from the model. In fact I have an explicit goal to keep HA knowledge entirely out from the pybambu model layer.
