### ISSUE TITLE
[Bug] Bambu Cloud MQTT option no longer works

### ISSUE THREAD

**Issue by eshkrab** [greghesp/ha-bambulab#126]
### Describe the bug

Hello!

Just got a X1C, running firmware v 01.05.01.00 (came out yesterday, 04/26/23) and yesterday found this add-on, which made me very happy as I'm missing Octoprint on this printer. I've not tried the LAN only mode yet but since Bambu Cloud is supported, was trying that. However, I get an error on trying to connect and not really sure how to go about troubleshooting.

I've tried SN both in all lowercase and uppercase, anything else I'm missing? Even updated today since the new version of the add-on came out so fast (1.2.0)

### To Reproduce

go to 'Add integration'
'Bambu Lab'
Choose X1C, fill out SN, Bambu Cloud, press 'Next'
Fill out credentials (work for app, studio, OrcaSlicer, and website)
get 'Failed to connect'

### Expected Behaviour

Addon should be able to connect?

### What device are you using?

X1C

### Firmware Version

01.05.01.00

### Home Assistant Version

Supervisor 2023.04.1 Operating System 10.1

### Component Version

1.2.0

**Comment by jneilliii** [comment]
> I'm missing Octoprint on this printer.

you'll be happy to know I also got the X1C and will be looking into OctoPrint integration in the near future...

**Comment by AdrianGarside** [comment]
Unfortunately I can confirm this is broken now. Something has changed on the Bambu cloud mqtt side. Code is still successfully retrieving an auth token but using it to connect is being refused with an access denied error.

**Comment by Exit2Studios** [comment]
I have same issue.  First appeared after upgrading firmware to 1.05.1

**Comment by MiezLisa** [comment]
same problem for me, i changed my wifi and the integration stopped working so i deleted the integration and wanted to set it up again - error: failed to connect! :(

firmware printer 01.05.01.00 
homeassistant integration (Bambu Lab) v1.2.0

**Comment by eshkrab** [comment]
> > I'm missing Octoprint on this printer.
> 
> you'll be happy to know I also got the X1C and will be looking into OctoPrint integration in the near future...

Ah, that'll be awesome. Are you thinking of making like a translation layer so it sends MQTT over wifi  instead of serial commands?

**Comment by jneilliii** [comment]
Yeah, basically a middle man that interprets commands from OctoPrint and communicates with bambu over mqtt/ftps.

**Comment by ThoughtfulDev** [comment]
Same here. After FW upgrade to the latest (X1C).

**Comment by coreywagehoft** [comment]
I was having this issue before the recent FW upgrade, and I am still having the issue after the FW upgrade.

**Comment by AdrianGarside** [comment]
It’s not specific to the printer firmware. It’s entirely a server side rejection. The question is how it’s changed in a away that breaks this integration without breaking Bambu Studio and the Handy App.

**Comment by MiezLisa** [comment]
> All - Just want to highlight, LAN mode for the X1C doesn't mean that the printer needs to be in LAN mode. It'll still work, even if LAN mode on your printer is not on
> 
> @AdrianGarside - we should probably reword this one for the X1C

thanks for the hint :)

**Comment by AdrianGarside** [comment]
It doesn’t mean that for the P1P either since they reenable local mqtt even in cloud mode. Until/if we have a solution I’ll pull the cloud mqtt config option.

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v1.2.1

**Comment by WolfwithSword** [comment]
Yeah it likely should be reworded, as it's more about how the integration connects to the printer's mqtt - "Local connection" vs "Cloud Server MQTT". Should make the wording as different from "LAN mode" and "Cloud mode" as possible I think.

Luckily both printers now once again work with local mqtt connections, the cloud is a good fallback for P1P though if it ever gets locked again (if the cloud connection even still works).

**Comment by AdrianGarside** [comment]
Yeah the wording I used originally was very confusing in hindsight. I fixed it while I was suppressing the cloud mqtt option in case we can ever re enable that. But with local working (and more reliably anyway) it’s probably not a priority.

**Comment by AdrianGarside** [comment]
Per:
https://github.com/Doridian/OpenBambuAPI/blob/main/mqtt.md

The problem is probably that Bambu has started enforcing the expected user name:
```
Username: u_{USER_ID}, where the user id can be grabbed by cracking your own {ACCESS_TOKEN} (which is a JWT) and reading its preferred_username field.
```

**Comment by AdrianGarside** [comment]
I was able to use [JSON Web Tokens - jwt.io](https://jwt.io/) to decode the token and get the user name - it’s u_ so not obviously something that can be predicted from the bambu user name. Some online base64 decode tools could decode the payload portion of the token into the json payload too but others failed - not sure why yet.

**Comment by WolfwithSword** [comment]
Seems like there are libraries for the jwt.io, so could import it and on startup of the integration, do an API call to bambu to fetch the token and decode it internally. A lot of workaround to get the cloud MQTT working, which since the LAN access is back up and working, doesn't seem too useful anymore.

If cloud is down it may not work but local lan mqtt would still. I would maybe suggest priority of this is low since the lan mqtt can be accessed in *any* mode and works better. But it can be a backup option with some slow development?

**Comment by AdrianGarside** [comment]
import base64
# code = 2nd portion of the auth token (delimited with periods)
b64_string = code
b64_string += "=" * ((4 - len(b64_string) % 4) % 4)
base64.b64decode(b64_string)
# Gives json payload with "username":"u_<digts>" within it

**Comment by AdrianGarside** [comment]
Fixing this will allow us to workaround the new 'there shall only be one' local mqtt behavior in the latest firmware.

**Comment by AdrianGarside** [comment]
Re-enabled in latest dev release.
