### ISSUE TITLE
[Feature] Detect door state

### ISSUE THREAD

**Issue by leonklingele** [greghesp/ha-bambulab#127]
### Describe the feature

I was wondering if the current door state is somehow exposed by the printer (i.e. open or closed). Apparently the X1 ships with a sensor to detect this which however isn't used as of now.

### What device is this for?

X1C

**Comment by AdrianGarside** [comment]
@greghesp - I see 'hw_switch_state' in the mqtt payload from your machine (set to 1). I have it in my P1P payload too but it's set to zero. P1P doesn't have a door sensor. That appears to be the only payload that might be this.

**Comment by AdrianGarside** [comment]
That code suggests it's the filament load sensor.

**Comment by AdrianGarside** [comment]
Unfortunately not something we can do currenty.
