### ISSUE TITLE
[Feature] Total and remaining color swaps

### ISSUE THREAD

**Issue by maziggy** [greghesp/ha-bambulab#129]
### Describe the feature

Don't know if that fits to your project:

In general I would like the total/remaining color swaps for the current print. I had a quick look at it. Looks like the 3mf format is not standard :( I was able to get the current print file via FTP but was not able to parse the color swaps.

### What device is this for?

AMS

**Comment by WolfwithSword** [comment]
This would be interesting though after parsing the 3mf of a multi colour print I also cannot find a way of determining the filament change/swap counts. Possibly if you counted the number of times the gcode was present in the currently printing gcode file?

As for tracking current total done (thus, math to get remaining), the closest I can think of is to track the miscellaneous mqtt messages for it, or count how many times it goes into the "Changing filament" stage. Might try looking into this more

**Comment by AdrianGarside** [comment]
My assumption is we'd have to download the 3mf and unzip to get the gcode (or maybe download the gcode directly), parse it for the color change gcode commands. And then each time the gcode line number in the mqtt changes to be accurate (and resilient to HA restarts) we'd have to reparse to see how many had been dealt with up to that point. Or we could do a hybrid where we attempt to count them as they happen via the stage but re-initialize using the gcode parsing if we're starting up fresh and a print is already in progress.

**Comment by WolfwithSword** [comment]
Maybe if we used the layer sensors (x1c only) to compare, one could theoretically just parse the gcode file (yep, downloaded via ftp and extracted) one time and not as a sensor, store filament swaps at each layer they occur, and could just make a count for the sum up to current layer vs the sum of all layer's changes. That way there'd be no need to monitor for stages which may not always change. Won't be real-time accurate but may be enough.

**Comment by AdrianGarside** [comment]
That's pretty much what I was thinking except I'm suggesting using the mc_print_line_number to track progress through the file. layer/total layer aren't available on the P1P. And doing it by mc_print_line_number would exactly accurate.

Thinking about it that approach would also work to fabricate the missing layer / total layer count values that are currently missing on the P1P...

**Comment by maziggy** [comment]
I think the problem is to find the total amount of swaps. I couldn't find that information in the 3mf file. That's IMHO the only thing missing.

**Comment by WolfwithSword** [comment]
3MF's sent to the printer contain the gcode, and parsing through one I extracted you can see the following repeated for each filament swap:

```gcode
;--------------------
; CP TOOLCHANGE START
; toolchange #1
; material : PLA -> PLA
;--------------------
```
The number increments and material will be different depending what you swap to/from but you could do a simple count of "CP TOOLCHANGE START" in the gcode for your total sum. Of course, will need to match the gcode to the correct plate being printed and would need to FTP to the printer, unzip the 3mf, extract the gcode (which is arguably the largest file in the 3mf so it may sometimes be time/process consuming). So if it is implemented, would need to be async / not hold back the printer updates, and just one time update when it's "done". 

This *won't* work for filament changes with external spool as defined in gcode I think, I forget if it adds this too (plus I run custom printer gcode for filament swap when using external spool for swapping so I can't reliably test) but I think that use case is much less likely.

**Comment by maziggy** [comment]
Where did you exactly find the Gcode in the 3mf file? Couldn't find anything.

`imac:bambu xxxx$ unzip alien2.3mf
Archive:  alien2.3mf
  inflating: [Content_Types].xml
 extracting: Metadata/plate_1.png
 extracting: Metadata/plate_2.png
 extracting: Metadata/plate_3.png
 extracting: Metadata/plate_3_pattern_layer_0.png
  inflating: Metadata/plate_3.json
  inflating: 3D/3dmodel.model
  inflating: 3D/_rels/3dmodel.model.rels
  inflating: 3D/Objects/Egg 7.STL_12.model
  inflating: 3D/Objects/Egg 2.STL_17.model
  inflating: 3D/Objects/Spike Left 2.STL_9.model
  inflating: 3D/Objects/Spike Right 1.STL_5.model
  inflating: 3D/Objects/Egg 4.STL_15.model
  inflating: 3D/Objects/Egg 6.STL_13.model
  inflating: 3D/Objects/Spike Right 2.STL_6.model
  inflating: 3D/Objects/Tail.STL_4.model
  inflating: 3D/Objects/Spike m.STL_7.model
  inflating: 3D/Objects/Egg 3.STL_16.model
  inflating: 3D/Objects/Spike Left 1.STL_8.model
  inflating: 3D/Objects/Egg 1.STL_18.model
  inflating: 3D/Objects/Base.STL_2.model
  inflating: 3D/Objects/Egg 5.STL_14.model
  inflating: 3D/Objects/Arm L.STL_19.model
  inflating: 3D/Objects/Arm R.STL_20.model
  inflating: 3D/Objects/Head.STL_11.model
  inflating: 3D/Objects/Torso.STL_3.model
  inflating: 3D/Objects/Lower Body.STL_10.model
  inflating: Metadata/project_settings.config
  inflating: Metadata/model_settings.config
  inflating: Metadata/slice_info.config
  inflating: _rels/.rels

imac:bambu xxxx$ rm alien2.3mf
remove alien2.3mf? y

imac:bambu xxxx$ egrep -r -i toolchange .
./Metadata/project_settings.config:    "change_filament_gcode": "M620 S[next_extruder]A\nM204 S9000\n{if toolchange_count > 1 && (z_hop_types[current_extruder] == 0 || z_hop_types[current_extruder] == 3)}\nG17\nG2 Z{z_after_toolchange + 0.4} I0.86 J0.86 P1 F10000 ; spiral lift a little from second lift\n{endif}\nG1 Z{max_layer_z + 3.0} F1200 ;** only requiered when printing by object ?! otherwise going + 0.5mm should be enought\n\n\nM106 P1 S0\nM106 P2 S0\n;M104 S[nozzle_temperature_range_high] ;** Change temp to max without waiting, waiting would take age for nothing\n;M104 S275 ;** Change temp to 275°c without waiting, waiting would take age for nothing\n\n\n\n;** Go to cutting current filament position\n;**G1 X20 Y50 F30000 ;**doing in two path to avoid problem on cutter actuator\n\nG1 X20 F30000\nG1 Y50 F30000\nG1 Y-3\n\n{if toolchange_count == 2}\n; get travel path for change filament\nM620.1 X[travel_point_1_x] Y[travel_point_1_y] F30000 P0\nM620.1 X[travel_point_2_x] Y[travel_point_2_y] F30000 P1\nM620.1 X[travel_point_3_x] Y[travel_point_3_y] F30000 P2\n{endif}\n\nM620.1 E{old_filament_e_feedrate * 3} T{old_filament_temp}\n\nT[next_extruder] ;Cut and change filament\n\nM620.1 E{new_filament_e_feedrate * 3} T{new_filament_temp}\n\nM104 S[new_filament_temp]\n\n{if next_extruder < 255}\nG92 E0 ;** reset extruder pos, perfect after T\n\n{if flush_length_1 > 1}\n; FLUSH_START 1\n{if flush_length_1 > 23.7}\nG1 E22.7 F{old_filament_e_feedrate * 1.5} ; do not need pulsatile flushing for start part\nG1 E0.2 F120\nG1 E{(flush_length_1 - 22.7) * 0.25} F{old_filament_e_feedrate * 1.5}\nG1 E0.2 F120\nG1 E{(flush_length_1 - 22.7) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.2 F120\nG1 E{(flush_length_1 - 22.7) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.2 F120\nG1 E{(flush_length_1 - 22.7) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.2 F120\n{else}\nG1 E{flush_length_1} F{old_filament_e_feedrate * 1.5}\n{endif}\n; FLUSH_END\n{endif}\n\n{if flush_length_2 > 1}\n; FLUSH_START 2\nG1 E{(flush_length_2 - 1) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.25 F120\nG1 E{(flush_length_2 - 1) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.25 F120\nG1 E{(flush_length_2 - 1) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.25 F120\nG1 E{(flush_length_2 - 1) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.25 F120\n; FLUSH_END 2\n{endif}\n\n{if flush_length_3 > 1}\n; FLUSH_START 3\nG1 E{(flush_length_3 - 1) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.25 F120\nG1 E{(flush_length_3 - 1) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.25 F120\nG1 E{(flush_length_3 - 1) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.25 F120\nG1 E{(flush_length_3 - 1) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.25 F120\n; FLUSH_END 3\n{endif}\n\n{if flush_length_4 > 1}\n; FLUSH_START 4\nG1 E{(flush_length_4 - 1) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.25 F120\nG1 E{(flush_length_4 - 1) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.25 F120\nG1 E{(flush_length_4 - 1) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.25 F120\nG1 E{(flush_length_4 - 1) * 0.25} F{new_filament_e_feedrate * 1.5}\nG1 E0.25 F120\n; FLUSH_END 4\n{endif}\n\n\n\n;**G1 E2 F{new_filament_e_feedrate} ;Compensate for filament spillage during waiting temperature\nG1 E2 F60 ;Compensate for filament spillage during two second\n\nM106 P1 S255\nG92 E0\nG1 E-[new_retract_length_toolchange] F1800\n\nG1 Y255 F15000\nG1 X80 F15000\nG1 X60 F15000\nG1 X80 F15000\nG1 X60 F15000 ;shake to put down garbage\nG1 X70 F15000\nG1 X90 F15000\n\nG1 Y255 F15000\nG1 X100 F5000\nG1 Y265 F5000\nG1 X70 F10000\nG1 X100 F10000\nG1 X70 F10000\nG1 X100 F10000\nG1 X165 F10000 ;wipe and shake\nG1 Y256 ; move Y to aside, prevent collision\n\n\n\nG1 Z{max_layer_z + 3} F3000\n{if layer_z <= (initial_layer_print_height + 0.001)}\nM204 S[initial_layer_acceleration]\n{else}\nM204 S[default_acceleration]\n{endif}\n{else}\nG1 X[x_after_toolchange] Y[y_after_toolchange] Z[z_after_toolchange] F30000\n{endif}\nM621 S[next_extruder]A\n",
./Metadata/project_settings.config:    "retract_length_toolchange": [
./Metadata/project_settings.config:    "retract_restart_extra_toolchange": [`

**Comment by maziggy** [comment]
Got it. It's in the 3mf file stored on the printer but not in the 3mf file exported by the slicer.

**Comment by AdrianGarside** [comment]
No current plans to implement this as it's a very expensive feature.
