### ISSUE TITLE
[Bug] China user can't login

### ISSUE THREAD

**Issue by chouch0u** [greghesp/ha-bambulab#135]
### Describe the bug

For content and price reasons (P1P sells in China for about 578 USD), Bambulab has built two different account systems - one for global users and the other for mainland China users. The login endpoints are also different: global users use https://bambulab.com/api/sign-in/form, while Chinese users use https://bambulab.cn/api/sign-in/form. Due to the lower price of P1P in China compared to other regions, all Chinese P1P users are required to use the Chinese Bambulab account (for now, X1 does not have this limitation).

So if passable, can you add a toggle or input field for user switch two different endpoint?

### To Reproduce

1. Register a China BambuLab account from https://bambulab.cn . (it required +86 phone number)
2. Login

### Expected Behaviour

1. Click toggle switch endpoint or type endpoint to input field
2. Login

### What device are you using?

P1P

### Home Assistant Version

2023.4.5

### Component Version

1.1.1

### Other Information

If consider fix this problem, I can help for test.

**Comment by AdrianGarside** [comment]
Need to add region to bambu cloud setup so that we can properly call CN API endpoints / handle any future region differentiation.

**Comment by AdrianGarside** [comment]
Should be fixed in v2.0.0 but I haven't tested it.
