### ISSUE TITLE
[Feature] Bed mesh data 

### ISSUE THREAD

**Issue by Alfiegerner** [greghesp/ha-bambulab#146]
### Describe the feature

Wondering if we can expose bed mesh data, as per https://www.wolfwithsword.com/bambulab-bed-mesh/?

### What device is this for?

X1C

**Comment by WolfwithSword** [comment]
I'd love to see if anyone else could get a workaround to HA's limitations around this, but I'm not sure if it's possible.

HA has a limit on the length of sensor values, and while the integration would just store it in the backend, not sure what use that would end up being for the end-user still.

Hence why my two approaches use pastebin and a postgres database. The integration could have some calculations to parse the data (it's annoying to collect MQTT-wise) and try to determine "bad spots" but without the context of the rest of the bed that may not be user-friendly enough to warrant doing.

**Comment by AdrianGarside** [comment]
Getting the nice visualization seems like it would be impossible or a huge amount of work with HA. But you could maybe give summary stats like average deviation and worst case deviation to given people an idea of how flat their bed is. Not very actionable but still a useful thing to know.

**Comment by Alfiegerner** [comment]
Thank you @WolfwithSword for making this work at all and looking at this issue.  I think many people interested in this are driven by the fear of significantly warped plates, so any indication of that would very useful. Or a service that could publish the MQTT data, for copy and pasting into your visualizer would work well too. (I think I saw HA can now return strings from services which might be useful) Appreciate having the fall back to use node red though, keep on meaning to get that set up 👍.

**Comment by WolfwithSword** [comment]
Thanks @Alfiegerner , one thing about the HA string is I believe it's still too long for HA to ever serve it, even if through another service. Additionally, with the latest firmware from a few weeks ago for the X1C, Bambu has synced more of the firmware with the P1P (they had this same update some months ago) where the mc_print misc messages are no longer sent. This means that bed mesh data (as well as ams true humidity and PA flow calibration value) are no longer accessible via MQTT unless you roll back. As such, this feature would unfortunately no longer be in sync with the printer's updates.

**Comment by Alfiegerner** [comment]
Ah bugger, that's a bit annoying from Bambulab ☹️ Looks like it's time to fire up node red, thanks for the heads up.

**Comment by AdrianGarside** [comment]
They've removed this from the firmware even on the X1 now.
