### ISSUE TITLE
[Bug] Printer state often stops updating while printing

### ISSUE THREAD

**Issue by Billiam** [greghesp/ha-bambulab#147]
### Describe the bug

I have some notifications and automations based on starting and stopping a print. The print complete notification is failing regularly, because all printer state seems to get "stuck" during printing. This occurs maybe half of the time.

I do see occasional errors like the one listed below, which I think is the same as https://github.com/greghesp/ha-bambulab/issues/138. I don't think this is responsible, because it seems like I receive state updates after this happens. The error listed below occurred while printing at 4:12PM, but I continued receiving state updates until 4:27. There are no other log items from that first error time until much later (well after the print completed).

When this issue occurs, `current stage` and all other printer entities will be "stuck" until either a new print begins, or I select the `device` tab in BambuStudio or OrcaSlicer, after which the printer state will begin updating again.

I know this report is short in detail/reproduction, so I'm mostly looking for help providing better info for this bug.

### To Reproduce

For me it's just:

* Start a print via bambu studio
* Observe status updates stop coming through sometimes.

### Expected Behaviour

Printer status continues to update while printing

### What device are you using?

P1P

### Firmware Version

01.02.03.00

### Home Assistant Version

2023.5.3

### Component Version

1.3.1

### Log Extracts

Logger: custom_components.bambu_lab.pybambu
Source: custom_components/bambu_lab/pybambu/bambu_client.py:31
Integration: Bambu Lab ([documentation](https://github.com/greghesp/ha-bambulab), [issues](https://github.com/greghesp/ha-bambulab/issues))
First occurred: May 30, 2023 at 8:57:12 PM (7 occurrences)
Last logged: 4:12:28 PM

On Disconnect: Disconnected from Broker: 2
On Disconnect: Disconnected from Broker: 16
An exception occurred processing a message:
Exception type: <class 'UnicodeDecodeError'>
Exception args: ('utf-8', b'{"print":{"gcode_state":"IDLE","gcode_file_prepare_percent":"100","gcode_file":"\xc9\\u0002","command":"push_status","msg":1,"sequence_id":"10493"}}', 80, 81, 'invalid continuation byte')

**Comment by WolfwithSword** [comment]
I think you might be running into issues from both #138 and #92. The first for the invalid/malformed continuation byte exception, and the second for why some states get stuck (the P1P decides to not send update messages sometimes). At least for the second it seems like a fix may be identified?

**Comment by Billiam** [comment]
Thanks, I'll close this since #92 has better detail
