### ISSUE TITLE
[Bug] [WARNING] custom_components.bambu_lab.sensor.BambuLabSensor' took 0.435 seconds

### ISSUE THREAD

**Issue by mydevpeeps** [greghesp/ha-bambulab#156]
### Describe the bug

Error message during research states to inform you of a slow parser:

```
{"name":"homeassistant.helpers.entity","message":["Updating state for sensor.bambu_right_x1c_print_progress (<class 'custom_components.bambu_lab.sensor.BambuLabSensor'>) took 0.435 seconds. Please report it to the custom integration author."],"level":"WARNING","source":["helpers/entity.py",590],"timestamp":1687998928.756159,"exception":"","count":1,"first_occurred":1687998928.756159}
```

### To Reproduce

N/A

### Expected Behaviour

N/A

### What device are you using?

X1C

### Firmware Version

01.05.02.00

### Home Assistant Version

Home Assistant 2023.6.3; Supervisor 2023.06.4; Operating System 10.3; Frontend 20230608.0 - latest

### Component Version

1.0.0 ?

**Comment by AdrianGarside** [comment]
What hardware is your home assistant running on?

**Comment by AdrianGarside** [comment]
And more log context might be useful to see what was going on. The error doesn't make a lot of sense given that the sensor updating is all asynchronous - when HA asks we're just returning a value, there's no live lookup.

**Comment by AdrianGarside** [comment]
Currently inactionable and not reported by anyone else.
