### ISSUE TITLE
[Bug] Humidity sensor value always shows 0%

### ISSUE THREAD

**Issue by bvrielink** [greghesp/ha-bambulab#159]
### Describe the bug

Got a Bambu Lab X1-Carbon with AMS a couple of days ago and installed this plugin and works very good. But got 1 issue with one of the sensors. The Humidity sensor stays on 0% and doesn't change:

![afbeelding](https://github.com/greghesp/ha-bambulab/assets/8544667/fb884ee8-150c-4c93-be48-b2e6c3150903)

If you need more information let me know. Also if you need some logs let me know how to collect them.

### To Reproduce

Add sensor to dashboard and look at value.

### Expected Behaviour

A non 0% value.

### What device are you using?

X1C

### Firmware Version

01.05.02.00

### Home Assistant Version

2023.7.2

### Component Version

1.4.1

**Comment by bvrielink** [comment]
This is a screenshot from Orca Slicer/Bambu Studio which also shows it's not zero:

![afbeelding](https://github.com/greghesp/ha-bambulab/assets/8544667/8f85c7bc-dacf-4144-b389-f975fcba30bb)

**Comment by bvrielink** [comment]
Put it in debug mode see below for a received message. It's only containing 1 humidity field it seems.

File: [debug.txt](https://github.com/greghesp/ha-bambulab/files/12064739/debug.txt)

I'm running 1.40 btw (not 1.4.1 as I thought). Seems Hacs is not updated to 1.4.1 yet I think. But looking at the merges (including the current beta) it doesn't seem anything has changed regarding humidity.

**Comment by AdrianGarside** [comment]
Unfortunately the debug mqtt content that drives the raw humidity value sensor was removed in the latest X1 firmware. This sensor will be removed from the integration in the near future. All that's available is the humidity 'index' value that drives the UX in Orca/Bambu slicer - not the raw value.

**Comment by bvrielink** [comment]
> Unfortunately the debug mqtt content that drives the raw humidity value sensor was removed in the latest X1 firmware. This sensor will be removed from the integration in the near future. All that's available is the humidity 'index' value that drives the UX in Orca/Bambu slicer - not the raw value.

Thanks for your quick answer. Nothing you can do about that unfortunately.

Do you know why HACS is a version behind compared to the release on Github btw?

**Comment by AdrianGarside** [comment]
@bvrielink you have to opt the integration into receiving prerelease versions to get the very latest dev version. Except for critical fixes I try to bake changes in the 'develop' branch for a little while in case I accidentally introduce a bug that's worse than whatever I'm fixing/adding.

**Comment by AdrianGarside** [comment]
1.4.0 is the latest release from main. 1.4.1 should have been named 1.4.1-dev to make it clear it's a prerelease but I slipped up.

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases

**Comment by AdrianGarside** [comment]
Removed in v 1.4.3
