### ISSUE TITLE
[Bug] Select Entity's async_select_option() doesn't match other functions

### ISSUE THREAD

**Issue by SamCHENG16** [greghesp/ha-bambulab#171]
### Describe the bug

Background,
There is 2 Bambu printers, which serial is number-1 and number-2.

If there is two Select Entity for them, select action of printer-1 (active), meanwhile available, current_option, options of printer-2(inactive) is invoked at background.

### To Reproduce

1, Add two Select Entity of the type of printer, and deploy into HA.
2, Enter printer-1's page, can view all information of it.
3, Select entity-1's options of printer-1, then change it, it can find it is printer-1 based on coordinator.get_model().
4, Meanwhile, check log at console of HA, find entity-1 of printer-2 is active, because available, current_option, options of printer-2 is invoked.

### Expected Behaviour

Different printers has it own entity and data model.

### What device are you using?

X1C

### Home Assistant Version

2023.8.1

### Component Version

1.4.6

**Comment by AdrianGarside** [comment]
That makes no sense to me. Each printer is managed by its own instance of the integration. There should be no way they can interfere with each other - they have no way of sending to the wrong mqtt server.

**Comment by AdrianGarside** [comment]
Need actionable details. Logs (especially annotated) showing the issue are necessary. What's described should be completely impossible.
