### ISSUE TITLE
[Bug] ams temperature

### ISSUE THREAD

**Issue by dudu7731** [greghesp/ha-bambulab#177]
### Describe the bug

hi,
i wonder if i can put icecream in my AMS : 
![image](https://github.com/greghesp/ha-bambulab/assets/117290248/dc31aa98-525d-4650-9446-4300c0120aa6)

![image](https://github.com/greghesp/ha-bambulab/assets/117290248/ae670c31-3b23-4be7-97a5-886ecbdb4edd)
seriously, there is a little problem -41,5 °C ... it's getting hot in France but i wonder if there is a conversion problem somewhere ...

### To Reproduce

just see ams sensor 

### Expected Behaviour

see positive temperature in summer ? 

### What device are you using?

X1C

### Home Assistant Version

2023.8.1

### Component Version

1.4.8

**Comment by QuiNz0r** [comment]
had the same issue, weirdly it went back to normal after powering off the printer and on again.

I fear this might even be a bug in the Bambu Firmware? Garbage in / garbage out

**Comment by AdrianGarside** [comment]
The value is straight from the data provided in the mqtt feed. So any odd values are coming from the printer itself.
