### ISSUE TITLE
[Bug] Print Status Entity Missing States

### ISSUE THREAD

**Issue by SartorialGrunt0** [greghesp/ha-bambulab#179]
### Describe the bug

If you select _Print Status_ in an automation, only the states _Unavailable_ and _Unknown_ are available.

### To Reproduce

1.) Go to Settings -> Automations and Scenes -> Create New Automation
2.) Select  Add Condition -> State
3.) Select X1C Print Status Entity
4.) Select State

### Expected Behaviour

I would expect the following list of states.
1.) Offline
2.) Idle
3.)  Running
4.) Finished

This would align with what the entity can see for states.

### What device are you using?

X1C

### Firmware Version

0.1.06.01.00

### Home Assistant Version

2023.8.2

### Component Version

1.4.8

**Comment by AdrianGarside** [comment]
As I hoped/suspected, this was fixed with #178.

**Comment by AdrianGarside** [comment]
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/9a29f337-5f39-4a32-9fc7-41b5433d118a)

**Comment by SartorialGrunt0** [comment]
> ![image](https://github.com/greghesp/ha-bambulab/assets/26147576/9a29f337-5f39-4a32-9fc7-41b5433d118a)
> 
> 

Is there a release than incorporates this change yet?

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v1.4.8-dev2

**Comment by SartorialGrunt0** [comment]
> https://github.com/greghesp/ha-bambulab/releases/tag/v1.4.8-dev2

Thanks! FYI it appears dev 1 includes the update, but dev 2 does not.

**Comment by SartorialGrunt0** [comment]
> > > https://github.com/greghesp/ha-bambulab/releases/tag/v1.4.8-dev2
> 
> > 
> 
> > Thanks! FYI it appears dev 1 includes the update, but dev 2 does not.
> 
> 
> 
> Could you confirm with the lates production release that was just released please?

Hello, yes it is there in 1.4.9!

My camera feed doesn't seem to work at the moment however. I'll investigate and can make another issue for it.
