### ISSUE TITLE
[Bug] Localization change appears to have broken the AMS entities

### ISSUE THREAD

**Issue by AdrianGarside** [greghesp/ha-bambulab#182]
### Describe the bug

From my test instance running against the develop branch:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/67a62449-28cc-46c7-9c2e-316beba15052)

### To Reproduce

.

### Expected Behaviour

Should look like:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/beb3adbd-454e-4cce-bf9a-d8b2647c4865)

### What device are you using?

X1C

### Firmware Version

.

### Home Assistant Version

Latest code in develop

### Component Version

Latest

**Comment by AdrianGarside** [comment]
Previously the entity names were of the form:
sensor.p1p_<SERIAL>_ams_1_tray_1

Now they're just:
sensor.ams1_tray_1

Which means in addition to not working, they're no longer unique.

**Comment by AdrianGarside** [comment]
Code is still there and correct to set the expected name:
        self._attr_unique_id = f"{printer.device_type}_{printer.serial}_AMS_{ams_instance.serial}_{description.key}"

**Comment by AdrianGarside** [comment]
Ah, that's the unique id (has AMS serial). The string showing up in HA is using the AMS index. That's coming from coordinator.py:
            dev_reg.async_update_device(hadevice.id,
                                        name=f"{device_type}_{serial}_AMS_{index+1}",
                                        model="AMS",
                                        manufacturer=BRAND,
                                        sw_version=device.ams.data[index].sw_version,
                                        hw_version=device.ams.data[index].hw_version)

    def get_ams_device(self, index):
        printer_serial = self._entry.data["serial"]
        device_type = self._entry.data["device_type"]
        device_name=f"{device_type}_{printer_serial}_AMS_{index+1}"

        return DeviceInfo(
            identifiers={(DOMAIN, self.get_model().ams.data[index].serial)},
            via_device=(DOMAIN, printer_serial),
            name=device_name,
            model="AMS",
            manufacturer=BRAND,
            hw_version=self.get_model().ams.data[index].hw_version,
            sw_version=self.get_model().ams.data[index].sw_version
        )

My guess is that the localized name is now overriding the sensor name.

**Comment by AdrianGarside** [comment]
Deleting and re-adding to my test HA instance gave me a different result again:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/09bb6193-1b3e-48af-b2c4-d9a0d7601863)
So the sensors are now:
sensor.p1p_01s00a292501557_ams_1
With _n added by HA to make them unique.

And updating my production instance to 1.4.8-dev1 gave me a 4th result: where the sensors have the correct IDs but are unavailable.
2023-09-03 12:15:36.787 DEBUG (MainThread) [custom_components.bambu_lab] ADDING AMS SENSOR: P1P_SERIAL_AMS_SERIAL_humidity_index
2023-09-03 12:15:36.787 DEBUG (MainThread) [custom_components.bambu_lab] ADDING AMS SENSOR: P1P_SERIAL_AMS_SERIAL_tray_1
2023-09-03 12:15:36.788 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.bambu_lab entity: sensor.p1p_SERIAL_ams_1
2023-09-03 12:15:36.788 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.bambu_lab entity: sensor.p1p_SERIAL_ams_1_2

**Comment by AdrianGarside** [comment]
All the sensor names are broken for me after the delete/re-add:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/6eb42aee-10c2-4a38-a80a-979c77a3252f)
And all sensor IDs are of the form:
sensor.p1p_01s00a292501557_6

**Comment by AdrianGarside** [comment]
Looks like HA has always been autogenerating the user visible ID using the device name + entity name. And since the latter is no longer being directly set it just generates a non-unique ID and then appends a number to all of them.

**Comment by AdrianGarside** [comment]
@piitaya FYI - do any of the above symptoms make sense to you? It appears the entity ID is auto generated from device name + entity name. But removing the entity name for localization purposes means it's empty at the time the entity id is generated. Additionally the display name then seems to end up being just the device name and localization doesn't work.

**Comment by piitaya** [comment]
The entity id is derived from device name + entity name but entity name should be generated using translations instead of hardcoded names. It looks like it's not the case for your instance. 

I will look at this tomorrow 😉 I didn't noticed that behavior but it will do more tests.

**Comment by AdrianGarside** [comment]
The worst of the behavior is when configuring the integration from scratch. Prior to that the existing entity IDs get persisted and it all seemed to be working (for the non-AMS sensors at least). But setting up from scratch it the entities get created from scratch and that's when the missing name seems to cause the problems. 

But I've also tried making spot changes to remove the translation key and go back to the hard coded name, and the entities are still getting the wrong ID so I may be missing/misunderstanding something.

**Comment by AdrianGarside** [comment]
@piitaya updated to:
Home Assistant 2023.8.4
Frontend 20230802.1 - latest

And deleted/re-added the integration and now I have correct display names and correct entity IDs.

**Comment by AdrianGarside** [comment]
Closing as we'll enforce a newer min version of HA.

**Comment by AdrianGarside** [comment]
Something still off. Upgraded my production instance to 2023.8.4 and I'm still seeing the AMS sensors not working:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/22a5264a-7ff7-4287-818d-785bdf085780)

**Comment by AdrianGarside** [comment]
Nope, that was just the single-MQTT client only restriction in the latest P1P firmware so my production instances wasn't getting data until I turned off my test instance.
