### ISSUE TITLE
[Feature] Door Open/Close Status

### ISSUE THREAD

**Issue by c0ryd** [greghesp/ha-bambulab#198]
### Describe the feature

Would it be possible to get the door open/close status?  This would be great for an automation to turn on the external lighting when the door is opened. 

### What device is this for?

X1C

**Comment by AdrianGarside** [comment]
Last I checked the sensor wasn't hooked up into the mqtt payload. Unless that's changed we can't do it yet.

**Comment by tretabyte** [comment]
might be easier if you get a small zigbee door sensor and attach to the door, does the trick :)

**Comment by AdrianGarside** [comment]
@greghesp has the door sensor been hooked up into the mqtt payload yet or is this still a non-starter?
