### ISSUE TITLE
[Feature] Sensor for overall print time

### ISSUE THREAD

**Issue by qwasy** [greghesp/ha-bambulab#244]
### Describe the feature

The X1 has a sensor that shows the overall print time, for maintenance etc.
P1P/S don't have that.
Would a sensor like that be possible? 

### What device is this for?

P1P

**Comment by AdrianGarside** [comment]
I think so. I've already been trying to work out how to get home assistant to let me save a persistent value. My initial attempt to save it to the device config isn't working though.

**Comment by qwasy** [comment]
Nice^^
I think a statistic sensor could work https://www.home-assistant.io/integrations/statistics/
Or a long-term statistic one https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

Even though the value will always increase and the statistic charts will be boring.
But that could work for an additional maintenance sensor as well, like every 1000 Hours do some maintenance and then reset the counter.

**Comment by AdrianGarside** [comment]
Ah, I hadn't come across the long-term statistic sensors. Those presumably must be being persisted by HA so that ought to be relatively easy to use, if so.

**Comment by AdrianGarside** [comment]
Latest firmware added the total print time to the P1P - it's available on the touch screen in the device settings. It is not part of the mqtt payload though.

**Comment by AdrianGarside** [comment]
Using the cloud data for current and previous prints will enable us to more accurately track print time without having to have complex logic to make the integration resilient to being restarted in the middle of prints or cancelled prints.
