### ISSUE TITLE
[Bug] Unknown Error entering IP /Access Code

### ISSUE THREAD

**Issue by greghesp** [greghesp/ha-bambulab#245]
### Discussed in https://github.com/greghesp/ha-bambulab/discussions/158

<div type='discussions-op-text'>

<sup>Originally posted by **donutslave** July  7, 2023</sup>
Any hints for getting past this error? Thanks! 
<img width="584" alt="Screenshot 2023-07-07 at 10 05 19 AM" src="https://github.com/greghesp/ha-bambulab/assets/138824124/c555cc39-83f0-40ac-a2f5-4634f5dae4c8">
</div>

**Comment by AdrianGarside** [comment]
Please reopen the issue if you are still seeing this.
