### ISSUE TITLE
[Feature] <Connect to Bambulab account with Google account>

### ISSUE THREAD

**Issue by The-Young-Maker** [greghesp/ha-bambulab#247]
### Describe the feature

Would it be possible to connect to our Bambulab account with Google? Because I created my account with Google so I can not connect my account to Home-Assistant because there is only the option for the email address. Thanks!

### What device is this for?

X1C

**Comment by AdrianGarside** [comment]
You don't need to connect via bambu cloud. With an X1C it is best to connect to the local MQTT server on the printer by providing IP address and access code.

But if you really want to, we just added back the instructions on how to enable password access to your bamby account to the readme in the develop branch:
https://github.com/greghesp/ha-bambulab/tree/develop#setup-using-oauth
