### ISSUE TITLE
[Feature] Error reporting - hms sensor extra attributes are missing.

### ISSUE THREAD

**Issue by Darthmonkey** [greghesp/ha-bambulab#250]
### Describe the feature

Currently when a print fails and an error is generated in the slicer, it's not reflected in any of the current entities.
Although there is an 'HMS errors' entity, it won't necessarily trigger if a filament is blocked or run out.

A possible workaround using Homeassistant would be to test the print progress every 5 minutes and have it send an alert if none is made (assuming it wasn't idle or offline), but it would be more useful to get the actual error.

### What device is this for?

P1P

**Comment by AdrianGarside** [comment]
There is a printer error even that you can use to drive automations:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/ea98fac5-5039-495b-bd20-7bfc9434194b)

What you do with that is personal preference. I have it sending a notification to my phone.

"though there is an 'HMS errors' entity, it won't necessarily trigger if a filament is blocked or run out." - it does get set and in fact it's really annoying on the P1P since it never resets that state even for following prints until you restart the printer or put filament into that slot. But the newer print failed event is much easier to build automations around.

**Comment by AdrianGarside** [comment]
Docs: https://github.com/greghesp/ha-bambulab/blob/v1.7.1/docs/DeviceTrigger.md

**Comment by Darthmonkey** [comment]
Thanks for that, for some reason I assumed all triggers required an entity, so was expecting to see an entity for it in the list of Bambu entities. Good to know it's there, even if it's a bit hidden.
Also, the 'HMS errors' entity doesn't show anything (at least for me) on blocked or run out filaments (assuming the entity is reporting correctly) as I've had at least three in the last week, and HMS seems to think everything is fine.
![image](https://github.com/greghesp/ha-bambulab/assets/3304208/3b5f946e-615f-49c8-957c-2bf31621eab1)

**Comment by AdrianGarside** [comment]
That's odd. The easiest one to test with is the cover falling off error. Does it correct detect and include that data in the hms error sensor?

**Comment by Darthmonkey** [comment]
I'm mid print at the moment, but will edit this later today by initiating a test print, and knocking the cover off.

**Comment by AdrianGarside** [comment]
You don't need to be printing. Can you just remove the cover and see if it gets reported by the sensor.

**Comment by Darthmonkey** [comment]
Perhaps I should have changed the feature request to 'Needs to show an entity for Printer Error Detected and Print Failed' to allow for troubleshooting and clear view of current issues without having to rely on automations?

**Comment by AdrianGarside** [comment]
Print failed is exposed by the print status entity:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/c3f27bf6-b363-4c4a-9b84-8bc2aa13376d)

Current error state is exposed by the HMS errors entity:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/a05c9e51-f0eb-40c2-b243-eb976e19babd)

**Comment by Darthmonkey** [comment]
Just for clarification, this is technically an entity showing the 'failed' condition (not 'error'), but it doesn't show if the filament is blocked or run out (at least for me), so narrowing the question down further may be required, without getting too pedantic, and re-stating the question in a fashion which means more to other users, perhaps the feature request should be:
"An entity showing the current error/warning message shown on the printer/slicer"
For example, if the filament has run out and the slicer shows "filament blocked error 101001101", "filament blocked error 101001101" is shown in the element.
This would be specifically for errors, not failed jobs, as it's misleading (at least to me) as neither 'HMS errors' nor the 'Print status' entity are affected by filament running out (and perhaps other related errors).

**Comment by AdrianGarside** [comment]
The HMS errors entity has that data as additional attributes. The difficulty is that there can be many simultaneous errors so an entity showing a single error would have to arbitrarily choose one to show. Or you can create a template sensor that shows the first error from the HMS errors sensor attributes if that’s how you want to expose things. Or you can directly use the attribute content directly in your dashboard. I’ll see if I can dig up the yaml syntax for that.

**Comment by AdrianGarside** [comment]
This is the format for accessing attribute content to display in the dashboard or a notification:
`{{ state_attr('binary_sensor.p1p_SERIAL_hms_errors', 'Count') }} errors encountered: '{{ state_attr('binary_sensor.p1p_SERIAL_hms_errors', '1-Error')  }}'`

So `state_attr('<ENTITY>', '<ATTRIBUTE>')` will be replaced with the text from that attribute. 

And you can add conditions as well. That looks something like this:
`${states['sensor.p1p_SERIAL_hms_errors'].state == 'Ok' ? 'OK' : 'state_attr('binary_sensor.p1p_SERIAL_hms_errors', '1-Error')  }}' }`

**Comment by AdrianGarside** [comment]
And having said all of that, something seems to have gotten broken as the extra_attributes are missing from the hms_errors sensor with the latest HA and/or integration version. Even in the OK state there should be an extra attribute of Count = 0 that's now nowhere to be seen. The code is still setting all the extra attributes. So that explains why you're pushing to expose the data - if it's gone AWOL from where it's supposed to be exposed.

**Comment by AdrianGarside** [comment]
Ah, they’re still there but only shown when in the error state:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/1fe2676d-f5fa-407e-87e4-2e1e796d6a7b)

It used to show them with just the Count = 0 entry in the non error state too.

**Comment by AdrianGarside** [comment]
Yes, I broke it. This is what it originally looked like in the clear state:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/191f5ee9-9a37-4d15-a42a-953d149de14a)

Maybe with the switch to being a binary sensor I decided that Count = 0 was pointless when the sensor state itself was 'Ok'.

**Comment by AdrianGarside** [comment]
And a state-label is a much easier way to get a known string out but the difficulty here is that the extra state won't be present in the non-error state:

E.g.:
```
  - type: state-label
    entity: sensor.p1p_SERIAL_ams_2_tray_2
    attribute: type
```
type is 'PLA' or 'PETG' in an extra attribute named 'type' on the tray object.

**Comment by AdrianGarside** [comment]
This works for displaying an attribute value like you would the main sensor value:
`type: entities
entities:
  - type: attribute
    name: HMS Error Count
    entity: binary_sensor.p1p_01s00a292501557_hms_errors
    attribute: Count`

**Comment by AdrianGarside** [comment]
Or the entities card:
```
type: entity
entity: binary_sensor.p1p_01s00a292501557_hms_errors
attribute: Count
```

**Comment by AdrianGarside** [comment]
But given 1-Error and 1-Wiki aren't present unless there's an error I think you're into either template sensors or the approach I first suggested but I have a feeling the latter might have been powered by a lovelace add-on.

**Comment by Darthmonkey** [comment]
---Me slowly eating popcorn waiting for the easy approach----
![image](https://github.com/greghesp/ha-bambulab/assets/3304208/fad987ba-fd51-4c88-98c0-f6ce0f772a5c)
Yep, while I've been reading this, I ran out of filament, and this popped up just as I created the entity. That's a bingo as far as I'm concerned!

**Comment by AdrianGarside** [comment]
This is what you get if you plug in the attribute:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/bb13e443-e6a3-4f3f-80ae-bad0bbbc775b)
