### ISSUE TITLE
[Bug] The state of state after printing is unknown.

### ISSUE THREAD

**Issue by cryd-s** [greghesp/ha-bambulab#252]
### Describe the bug

The state of state after printing is unknown.
![image](https://github.com/greghesp/ha-bambulab/assets/47699362/c8528a29-3b6b-46aa-943c-5100be2a89e1)

Is there a option to get the state finished

### To Reproduce

just print

### Expected Behaviour

the state finished 

### What device are you using?

X1C

### Diagnostic Output

```shell
.
```

**Comment by AdrianGarside** [comment]
This is inactionable with logs from the integration. Please provide logs as described in the readme file.
