### ISSUE TITLE
[Question] Oauth password disable

### ISSUE THREAD

**Issue by adrianmihalko** [greghesp/ha-bambulab#259]
> [Setup using OAuth](https://github.com/greghesp/ha-bambulab/issues/new#setup-using-oauth)
> 
> If you signed up using any OAuth method, you need to set a password for your Bambu Cloud account:
> 
> Login to the Bambu mobile app using OAuth.
> Tap the person icon at the bottom right.
> Tap Account Security > Change Password

If I follow these steps I still will be able to login using OAuth or I need to use this password?

**Comment by AdrianGarside** [comment]
You use that password when setting up the integration. But the only reason to use bambu cloud authentication is if you have a P1P/P1S and you have some other local software (not Bamby Studio/Handy) that needs to connect via the local mqtt server on the printer.

**Comment by AdrianGarside** [comment]
Please put discussions in the discussion section.
