### ISSUE TITLE
[Feature] Add optional chamber fan control to P1P (upgrade kit)

### ISSUE THREAD

**Issue by joohkim88** [greghesp/ha-bambulab#260]
### Describe the feature

I see that this was removed because P1P does not have a chamber fan. But if one upgrades P1P to P1S using the official kit, the device will have a chamber fan yet it will still report itself as P1P.

If possible, at least pre-disabled entity should be there for P1P, so that users who upgrade their P1Ps can enable it and use it.

### What device is this for?

P1P

**Comment by joohkim88** [comment]
I do in fact have a P1P with the upgrade kit, please see below for the diagnostics file. If this is not what you need, please let me know :)

[config_entry-bambu_lab-dac187fb07368399e92214d209eec8e9.json.txt](https://github.com/greghesp/ha-bambulab/files/13113639/config_entry-bambu_lab-dac187fb07368399e92214d209eec8e9.json.txt)

**Comment by WolfwithSword** [comment]
> We should then be able to see if its possible to automatically detect this. If not, @AdrianGarside i suggest we add some config in the setup flow to allow for this?

I believe it should be detectable via the get_accessories command, if not then likely can only check if the value is non-zero or if it's as you mentioned, a selected option in the setup.

**Comment by enricominciamo** [comment]
I added my "p1p" with the kit as a "p1s" and the chamber fan works

**Comment by AdrianGarside** [comment]
> > We should then be able to see if its possible to automatically detect this. If not, @AdrianGarside i suggest we add some config in the setup flow to allow for this?
> 
> I believe it should be detectable via the get_accessories command, if not then likely can only check if the value is non-zero or if it's as you mentioned, a selected option in the setup.

My P1P doesn't react to the get_accessories command. I have it as:
{"system": {"sequence_id": "0", "command": "get_accessories", "accessory_type": "none"}}
Is that correct?

**Comment by WolfwithSword** [comment]
> My P1P doesn't react to the get_accessories command. I have it as: {"system": {"sequence_id": "0", "command": "get_accessories", "accessory_type": "none"}} Is that correct?

Should be right, maybe try a higher sequence id. A while ago I was helping debug someone with a P1P on much older firmware and sometimes sequence_id of 0 seemed to not work (but could've been anything tbh).

If it still doesn't work, I doubt there's anything in the get_version command either that could help.

What I'm curious of then is how it gets handled in bambu-studio or the handy app. If you don't have the chamber fan, does it still let you "change" the value and just, nothing happen? And if you do have the upgrade, can you set the chamber fan speeds in bambu studio?

**Comment by AdrianGarside** [comment]
I don’t have a chamber fan on my P1P but it still shows in Bambu handy and I can attempt to turn it on but when I exit that screen it’s still showing as off.

**Comment by WolfwithSword** [comment]
> I don’t have a chamber fan on my P1P but it still shows in Bambu handy and I can attempt to turn it on but when I exit that screen it’s still showing as off.

Yeah the they will show as off when it's at 0 speed. If you keep an eye on the request topic I'm willing to bet that there is a gcode command still sent to the printer. Because the value that's displayed in mqtt for the fan speed is whatever the sensor is reporting. For example if you go from 0-100, it will show it ramping up from say 0-20, 20-40, 40-70, 70-90 then 100. Even funnier is when it's on the edge between and keeps changing itself like 70-80% every few seconds lol.

But in that case if it shows as being editable despite not being present, it likely still sends the gcode command and since it just relies on reading the reported value, not much you can do.

One thing you could do is when the device is first added (or turned on), if the chamber fan is reporting 0, try increasing the speed to 20%, wait 10 seconds and if the fan speed is still 0 (and didn't even get an update for it except from a push-all) then it's not present or non-functioning.

**Comment by AdrianGarside** [comment]
That’s a good idea. The data we have for the A1 mini has a non zero speed for the chamber fan so we can’t just wait until we see a non-zero value. I also tried and so far failed to find a way to persist knowledge of the fans existence - attempting to add new data to the HA device config to track that throws an error. So still looking for a way to do the test once and then record it but doing the test always (for a P1P) would be a reasonable way to not need to do that. Although adding a new sensor later seems pretty fragile in home assistant.

**Comment by AdrianGarside** [comment]
The amount of work necessary to have a better-than-Bambu experience here isn't worth it IMO. So this is my proposed fix instead: #275.
