### ISSUE TITLE
[Feature] weight of current print

### ISSUE THREAD

**Issue by miabilabs** [greghesp/ha-bambulab#264]
### Describe the feature

Building some dashboards in HA and one thing I'd love to surface is the weight of the current print in grams.  This seems like it should be readily available since it's shown in Bambu Studio when you send your print to the printer. This is expressed in grams and represents the amount of filament needed for the current print job.  Possible to get this added?

### What device is this for?

P1P

**Comment by AdrianGarside** [comment]
Fixed in v2.0.0.
