### ISSUE TITLE
[Bug] Unable to connect (cloud or LAN)

### ISSUE THREAD

**Issue by flyingtech** [greghesp/ha-bambulab#268]
### Describe the bug

I'm trying to set up this integration and I cannot get it to connect to the Bambu cloud or with local MQTT.  

### To Reproduce

1: settings>devices>add integrations>bambu lab
not my real credentials for picture purposes

![image](https://github.com/greghesp/ha-bambulab/assets/14594149/2bb7e433-7178-4e40-ae87-2223199bc4c1)

![image](https://github.com/greghesp/ha-bambulab/assets/14594149/671c202b-49f1-49af-9ea9-0b645da2a7cf)

![image](https://github.com/greghesp/ha-bambulab/assets/14594149/a94c383a-9946-4b5d-bf1f-aeabb0608493)

### Expected Behaviour

anything

### What device are you using?

P1P

### Diagnostic Output

```shell
no output
```

**Comment by flyingtech** [comment]
so i reliazed that i had been using the 0Auth method in the app.  i changed the password but now getting the following:

This error originated from a custom integration.

Logger: custom_components.bambu_lab.pybambu
Source: custom_components/bambu_lab/pybambu/bambu_client.py:166
Integration: bambu_lab (documentation, issues)
First occurred: 7:56:04 AM (3 occurrences)
Last logged: 8:04:28 AM

On Disconnect: Disconnected from Broker: 0

**Comment by AdrianGarside** [comment]
Can you turn on debug logging globally and capture logs of your local connection attempt?

**Comment by flyingtech** [comment]
I'm not sure what happened but its working now.  i didn't change anything just tried it again after a few days. 🤷‍♂️
