### ISSUE TITLE
[Bug] All sensors + AMS devices not always reliably added on initial integration add - may require home assistant restart or integration reload

### ISSUE THREAD

**Issue by AdrianGarside** [greghesp/ha-bambulab#273]
### Describe the bug

Noticed while testing the A1 Mini support. But it's not specific to that. The bug seems to hit more consistently with cloud mode connection but an end user reported hitting it with local lan connection too.

### To Reproduce

Add a new printer.

### Expected Behaviour

All device entities for the printer and all AMS units get added correctly. But some of the time, not all printer entities get added and none of the AMS devices/entities get added. The AMS devices are missing from the found devices dialog shown during integration addition.

Restarting home assistant fixes all the missing sensors/devices.

### What device are you using?

P1P

### Diagnostic Output

```shell
I could not see any discernable difference in log output or timing comparing a 'good' to a 'bad' case.
```

**Comment by L1cardo** [comment]
I got this problem too, I got no AMS light with my A1 mini.
![image](https://github.com/greghesp/ha-bambulab/assets/33802186/bf78e6ee-0ab2-477d-8db9-cae8f266bb38)
![image](https://github.com/greghesp/ha-bambulab/assets/33802186/8096e395-555a-43f8-a074-ca0cc8bb43c5)

**Comment by AdrianGarside** [comment]
> I got this problem too, I got no AMS light with my A1 mini.
> ![image](https://user-images.githubusercontent.com/33802186/285486529-bf78e6ee-0ab2-477d-8db9-cae8f266bb38.png)
> ![image](https://user-images.githubusercontent.com/33802186/285486565-8096e395-555a-43f8-a074-ca0cc8bb43c5.png)

Did restarting home assistant fix it up?

**Comment by L1cardo** [comment]
> > I got this problem too, I got no AMS light with my A1 mini.
> > ![image](https://user-images.githubusercontent.com/33802186/285486529-bf78e6ee-0ab2-477d-8db9-cae8f266bb38.png)
> > ![image](https://user-images.githubusercontent.com/33802186/285486565-8096e395-555a-43f8-a074-ca0cc8bb43c5.png)
> 
> Did restarting home assistant fix it up?

Sadly no. I tried restarting home assistant for over 10 times, still no AMS light.

**Comment by AdrianGarside** [comment]
Can you grab diagnostic output. And ideally debug loga of home assistant startup.

**Comment by L1cardo** [comment]
> Can you grab diagnostic output. And ideally debug loga of home assistant startup.

How to grab diagnostic output of this plugin?

**Comment by L1cardo** [comment]
Yeah, I can see ams info in diagnostic file, but did not appear in HA.
[config_entry-bambu_lab-32d2355710552e810896c510578e446c.json.txt](https://github.com/greghesp/ha-bambulab/files/13461288/config_entry-bambu_lab-32d2355710552e810896c510578e446c.json.txt)

**Comment by AdrianGarside** [comment]
Aha. That's what we missed:

        {
          "name": "ams_f1/0",
          "project_name": "",
          "sw_ver": "00.00.07.89",
          "loader_ver": "00.00.00.00",
          "ota_ver": "00.00.00.00",
          "hw_ver": "AMS_F102",
          "sn": "**REDACTED**"
        }

X1 and P1 have:

      {
        "name": "ams/0",
        "project_name": "",
        "sw_ver": "00.00.05.96",
        "loader_ver": "00.00.00.00",
        "ota_ver": "00.00.00.00",
        "hw_ver": "AMS08",
        "sn": "**REDACTED**"
      }

We are looking current for ams/<n> but the A1 gives ams_f1/<n>

**Comment by AdrianGarside** [comment]
@L1cardo pushed https://github.com/greghesp/ha-bambulab/releases/tag/v1.9.1-dev1 that should fix this for you. And thank you for the new localization.

**Comment by L1cardo** [comment]
Yeah, v1.9.1-dev1 solved the problem, huge thank!

![image](https://github.com/greghesp/ha-bambulab/assets/33802186/98ee4d58-dbba-4274-af43-25953c5c946b)
![image](https://github.com/greghesp/ha-bambulab/assets/33802186/400726e2-b48d-4901-88b8-0e7c060a71da)

**Comment by AdrianGarside** [comment]
With the re-written bambu cloud setup connection I have been unable to repro this.
