### ISSUE TITLE
[Feature] Add the P1S camera to the cloud MQTT

### ISSUE THREAD

**Issue by zVaz** [greghesp/ha-bambulab#276]
I just tested the new camera sensor on my P1S and it is working!

## Feature
Add the P1S camera to the cloud MQTT

## Changes
- [ ] Need to ask for the access code (maybe IP too) in cloud MQTT
- [ ] Add the camera sensor to cloud MQTT

**Comment by kurim** [comment]
As a workaround for me I have created a very simple HA Addon, based on go2rtc and the known python code with some modifications.
It stream the mjpeg to 1984/api/stream.mjpeg?src=p1s and the rstp-mjpeg to 8554 (nice for Scrypted as an Homekit Cam)

**Comment by AdrianGarside** [comment]
I have fixed this in a private branch/release. Can you give it a test? Necessary steps are:
1. Upgrade to that version.
2. Go to the integration and hit configure on the printer:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/f392c359-d501-4dc5-bba1-dfaec0b28d7c)
3. Provide your bambu credentials.
4. It should list the printer and allow you specify the local IP address and (optionally) configure the mqtt connect to be local or not - you'll want to leave it cloud.
5. 
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0-dev1

**Comment by zVaz** [comment]
> I have fixed this in a private branch/release. Can you give it a test? Necessary steps are:
> 1. Upgrade to that version.
> 2. Go to the integration click the Bambu Lab expando and then hit configure on the printer:
> ![image](https://github.com/greghesp/ha-bambulab/assets/26147576/f392c359-d501-4dc5-bba1-dfaec0b28d7c)
> 3. Provide your bambu credentials.
> 4. It should list the printer and allow you specify the local IP address and (optionally) configure the mqtt connect to be local or not - you'll want to leave it cloud.
> 
> https://github.com/greghesp/ha-bambulab/releases/tag/v2.0-dev1
> 
> 

It is working thanks!
