### ISSUE TITLE
[Bug] Remove the word "layers" from both current layer and total layers

### ISSUE THREAD

**Issue by swampylee** [greghesp/ha-bambulab#279]
### Describe the bug

Seems the word "layers" has been added after the number shown for current and total layer values. I believe this should just be the number without the addition of the word "layers" which in the context of what the current layer is makes no sense anyway "Current Layer: 52 layers" etc.

### To Reproduce

Any print shows these values.

### Expected Behaviour

As above - don't shown the word "layers"

### What device are you using?

X1C

### Diagnostic Output

```shell
Not required
```

**Comment by AdrianGarside** [comment]
Yep, I've never been a fan of that either.

**Comment by swampylee** [comment]
Thanks for the quick fix / enhancement!
