### ISSUE TITLE
LAN connection from homeassistant blocks connection from bambu studio

### ISSUE THREAD

**Issue by EnigIVIa** [greghesp/ha-bambulab#302]
### Discussed in https://github.com/greghesp/ha-bambulab/discussions/301

<div type='discussions-op-text'>

<sup>Originally posted by **EnigIVIa** December  2, 2023</sup>
Is there a way to disconnect LAN mode in order to use Bambu Studio. Since the P1S only allows one LAN connection as soon as I setup the homeassistant intergration (which is amazing) I cant start prints anymore since bambu studio cant connect to the printer. Is there a disconnect button or the possibility to connect to the printer only every 5 minutes or so to give bambu studio a chance to connect?</div>

**Comment by AdrianGarside** [comment]
Yes, use the bambu cloud connection option instead. See #174.

**Comment by EnigIVIa** [comment]
Thank you for your quick response. I'm aware of the issue and also read the warning while configuring LAN mode. But it would still be a good solution to have a way to kill the connection to homeassistant if bambulab is not granting access for two devices in the near future. I'm kind of passionate about that because I was very happy to have found your solution and finally being able to use the P1S in LAN mode and still monitor it on my phone. It also feels weird to not being able to cut the connection without deleting the addon. But maybe this is just how homeassitant works, I'm new to this so sorry if I'm asking for crazy stuff :-).

**Comment by EnigIVIa** [comment]
Thank you for the explanation. I guess then it works for me since I always power the printer down after I use it. Also had to do that a while just to get bambu studio connecting. I honestly doubt that they will bring the functionality back any time soon if ever. They obviously make using the LAN inkonvenient and also pushing hard for their online platform (making it start page in the app etc.). There where rumors that they promised to make the bambu app work in LAN mode but there is also nothing so far. If I find the time I will also look into it. I already took a peek and saw that its written in python so I might manage to figure it out. I will share it if I'll get it to run.
