### ISSUE TITLE
[Feature] Expose microSD card usage

### ISSUE THREAD

**Issue by fanaticDavid** [greghesp/ha-bambulab#312]
### Describe the feature

Would it be possible to add a sensor which reports how much of the microSD card storage capacity has been used? If so, I think I would prefer to see a 'used' percentage, but I'm sure I could make do with having the amount of remaining gigabytes being reported. I'm just not sure which option would be most consistent with the existing sensors.

### What device is this for?

X1C

### Other Information

I've searched in this repository and couldn't find anyone asking the question or making the suggestion.

**Comment by WolfwithSword** [comment]
This unfortunately is not reported by the printer. At most you can get whether one is present or not in the printer, or if it is present but with errors.

**Comment by fanaticDavid** [comment]
Ah okay, good to know. Thanks for your reply, @WolfwithSword !
