### ISSUE TITLE
[Bug] current_stage isnt changing 

### ISSUE THREAD

**Issue by jl-p** [greghesp/ha-bambulab#314]
### Describe the bug

the wled integration doesnt respond when for example the front cover falls off. or if filament is empty.

### To Reproduce

start a print
and pull during print front cover of the head. 

### Expected Behaviour

lights will turn red. and current stage is 

options: offline, unknown, printing, auto_bed_leveling, heatbed_preheating, sweeping_xy_mech_mode, changing_filament, m400_pause, paused_filament_runout, heating_hotend, calibrating_extrusion, scanning_bed_surface, inspecting_first_layer, identifying_build_plate_type, calibrating_micro_lidar, homing_toolhead, cleaning_nozzle_tip, checking_extruder_temperature, paused_user, paused_front_cover_falling, calibrating_extrusion_flow, paused_nozzle_temperature_malfunction, paused_heat_bed_temperature_malfunction, idle

### What device are you using?

X1C

### Diagnostic Output

```shell
dont have
```

**Comment by AdrianGarside** [comment]
When I last looked at this I suspect you're out of luck. While all the above options are in the bambu source as possible values - they don't seem to generate most of them.
