### ISSUE TITLE
[Bug] Can't configure using either Bambu Cloud or LAN options

### ISSUE THREAD

**Issue by Djelibeybi** [greghesp/ha-bambulab#323]
### Describe the bug

I have installed the latest beta release of `v2.0-dev8-coverimage` and am unable to configure using either option. I am in Australia, which uses the Asia-Pacific region for Bambu.

I get the log entry when attepting to use Bambu Cloud. No log entries occur when trying to use the LAN option, even with debug logging enabled for both the integration and `pybambu` via `configuration.yaml`. 

I can't get a diagnostic output because the integration doesn't complete config flow.

### To Reproduce

1. Install `v2.0-dev8-coverimage`
2. Attempt to configure integration

### Expected Behaviour

Either option should work

### What device are you using?

X1C

### Diagnostic Output

```shell
N/A
```

### Log Extracts

```shell
2023-12-22 14:19:38.719 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code ("BambuCloud.__init__() missing 3 required positional arguments: 'email', 'username', and 'auth_token'",)
```

**Comment by AdrianGarside** [comment]
@Djelibeybi That error is a coding bug on my part - I haven't re-tested the initial setup flow(s) with the changes to add the cover image and given that error I've introduced a bug.

**Comment by AdrianGarside** [comment]
Dropped a new beta release with the new cover image support and the fix for the above error:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0-dev9

**Comment by Djelibeybi** [comment]
The new release gets past the first issue and shows me a list of printers, but I can't progress further. If I provide the IP address, it can't connect (though I can connect using Bambu Studio) and if I don't provide the IP address, it just refreshes the same dialog box. There are debug logs but no errors.

Trying a LAN connection from the start also ends up with a failed to connect error. Does this require the printer be in LAN only mode? I haven't tried that (yet).

**Comment by AdrianGarside** [comment]
Further fixes needed. That should address everything except the connect error when providing the IP address which I cannot repro. Are you sure the IP address you provided was correct?

New drop:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0-dev10

**Comment by Djelibeybi** [comment]
It's now all working. Seems I had a networking issue as well, sorry about that!
