### ISSUE TITLE
[Bug] Sensor: actual layer doesent work on A1

### ISSUE THREAD

**Issue by user858753257** [greghesp/ha-bambulab#342]
I have to take sensor "actual layer2" to read values . 

Maybe you can hide the first sensor for A1 users

**Comment by AdrianGarside** [comment]
You shouldn't have two 'actual layer' sensors - HA adds the second one if it detects a re-add of the same thing with a different underlying unique ID but the same friendly ID. Did you previously add the printer as an A1 Mini to get unblocked or was this setup done from scratch? If you delete and re-add the integration does the duplicated sensor get cleaned up?

**Comment by AdrianGarside** [comment]
Please reopen when you have more details.

**Comment by user858753257** [comment]
> You shouldn't have two 'actual layer' sensors - HA adds the second one if it detects a re-add of the same thing with a different underlying unique ID but the same friendly ID. Did you previously add the printer as an A1 Mini to get unblocked or was this setup done from scratch? If you delete and re-add the integration does the duplicated sensor get cleaned up?

Hey ,

sorry for the late answer . Yes I had previously added an A1 Mini to HA . 
Do you know where I can delete the device ?

**Comment by AdrianGarside** [comment]
I haven't quite worked out the rules but deleting the integration entirely and re-adding it should clean up the stale entry. You can also delete dead sensors which may not be necessary but wouldn't hurt to do before you delete/re-add the integration.
