### ISSUE TITLE
[Bug] Lan Mode Connection leading message issues

### ISSUE THREAD

**Issue by reedy** [greghesp/ha-bambulab#348]
### Describe the bug

![Screenshot 2023-12-24 at 15 16 02](https://github.com/greghesp/ha-bambulab/assets/67615/4a9d2980-ad63-4f75-9818-1ef70774709d)

The message suggests I need to tell you the local printer type, but there's no box for it. Not even after you submit it... Was it an option at one time that was removed/made into auto configuration?

"serial" should be "serial number".

Network settings should mention it's under WLAN (not "Network settings").

And the serial number on the device settings is labelled as SN.

### To Reproduce

Add a new integration, select "Lan Mode Configuration".

### Expected Behaviour

Not have leading text with instructions that aren't necessary :)

### What device are you using?

P1P

### Diagnostic Output

```shell
n/a
```

**Comment by AdrianGarside** [comment]
Thanks for the wording fixes.
