### ISSUE TITLE
[Bug] Clicking configure on an existing Integration should pre-select the correct current connection type

### ISSUE THREAD

**Issue by reedy** [greghesp/ha-bambulab#350]
### Describe the bug

If you setup a printer integration with Lan mode, when you edit/"configure" the existing selection, "Lan Mode Configuration" should be selected, not "Bambu Cloud Configuration"

![Screenshot 2023-12-24 at 15 55 58](https://github.com/greghesp/ha-bambulab/assets/67615/b5d7cf0f-a3b8-45b5-90d0-c8e55c11d567)

### To Reproduce

Add a printer integration via LAN mode, go back into Integration entries config for Bambu Lab, and click Configure on the right hand side

### Expected Behaviour

When you edit/configure an existing integration, it should pre select the current connection mode.

### What device are you using?

P1P

### Diagnostic Output

```shell
n/a
```

**Comment by AdrianGarside** [comment]
For this case I was actually want to work out how to not have it pre-select anything so you have to actively choose each time. I'll give it some thought to see if I agree with your suggestion instead.
