### ISSUE TITLE
P1P camera image stops working after 10 minutes

### ISSUE THREAD

**Issue by iluna8** [greghesp/ha-bambulab#360]
### Describe the feature

Chamber camera doesn't work after setup with Bambu Cloud. However, adding printer IP will poll the camera for the first 10 minutes. However, it won't be updated afterwards.

I recommend logic that divides chamber camera local and cloud behavior. This is all port maps of Bambu.

https://wiki.bambulab.com/en/general/printer-network-ports

Be aware of the Global/China distinction

Also, set the type type to the camera in order to turn the P1P chamber camera over to the HomeAssistant Homekit. Or why not change the camera / image mode for the camera P1P/P1S user in the initial setup?

### What device is this for?

P1P

**Comment by AdrianGarside** [comment]
Please provide actionable information such as debug logs for the repro.

**Comment by AdrianGarside** [comment]
Please reactivate with logs if you are still seeing this.
