### ISSUE TITLE
[Feature] Filament color (for template cards)

### ISSUE THREAD

**Issue by trwy7** [greghesp/ha-bambulab#368]
### Describe the feature

I would like the AMS tab to have the color of the filament.

### What device is this for?

AMS

### Other Information

This could be used in template cards, where the icon color could be the filament color

**Comment by AdrianGarside** [comment]
It's already present in the attributes so you can use it however you like in your dashboard:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/15895839-f977-4ff7-a166-fe57b8124a26)

**Comment by trwy7** [comment]
Thank you!

**Comment by jneilliii** [comment]
figured out a neat trick today to show active color using this. Only works with single AMS unit. 

```
  {{state_attr('sensor.x1c_00m00a330300134_ams_1_tray_'+states('sensor.x1c_00m00a330300134_active_tray_index'), 'color') }}
```

**Comment by AdrianGarside** [comment]
You can use active tray to track and present the filament currently in use.

**Comment by jneilliii** [comment]
Yeah, figured that out after posting. Thanks for such a great project.

**Comment by trwy7** [comment]
> It's already present in the attributes so you can use it however you like in your dashboard: ![image](https://private-user-images.githubusercontent.com/26147576/293294690-15895839-f977-4ff7-a166-fe57b8124a26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NzMzNTIsIm5iZiI6MTcwMzg3MzA1MiwicGF0aCI6Ii8yNjE0NzU3Ni8yOTMyOTQ2OTAtMTU4OTU4MzktZjk3Ny00ZmY3LWExNjYtZmU1N2I4MTI0YTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE4MDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOGIwN2I0ZWE4OGMyYTliMzg3NTdiYWM0MDc1OGU0MzRlYTdiNTA1ZDk2MTFmMWM0NGJiZTVkM2FmYzQyYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ieg84OGxhfiJKc6qEw6i-Kp79_wTb0UpVR57MWk6y8k)

So unrelated question, how did you get the print preview on your page? I am using an A1 so it may not be possible.

**Comment by AdrianGarside** [comment]
That's the new cover image sensor. It's available if you configure the integration to have your bambu crendentials.
