### ISSUE TITLE
[Bug] Start and end time sensor datetime strings do not reliably include the date  

### ISSUE THREAD

**Issue by markfrancisonly** [greghesp/ha-bambulab#374]
### Describe the bug

Based on the current day, the print job start and end time sensor values may not include a date

### Expected Behaviour

Expect integration to always provide a date for print start and end times. I need the print start and end dates for coding 

### What device are you using?

X1C

### Diagnostic Output

my templates are broken:

```

- sensor:
    - name: Bambu X1C Printer Job ETA
      state: |
        {% set sensor_datetime = strptime(states('sensor.bambu_x1c_printer_end_time'), '%d %B %Y %H:%M:%S') %}
        {% set current_datetime = now().replace(hour=0, minute=0, second=0, microsecond=0) %}
        {% if sensor_datetime.date() == current_datetime.date() %}
          {{ sensor_datetime | as_timestamp | timestamp_custom('%I:%M %p', true) }}
        {% else %}
          {{ sensor_datetime | as_timestamp | timestamp_custom('%m/%d/%Y %I:%M %p', true) }}
        {% endif %}
      icon: mdi:clock

    - name: Bambu X1C Printer Job Remaining
      state: |
        {{ strptime(states('sensor.bambu_x1c_printer_end_time'), '%d %B %Y %H:%M:%S')  | as_local }}
      device_class: timestamp      
      icon: mdi:timer
```

**Comment by markfrancisonly** [comment]
The breaking changes from https://github.com/greghesp/ha-bambulab/pull/341 can work still work for some if an attribute containing the full iso formatted datetime string is added to the sensors

**Comment by AdrianGarside** [comment]
The HA way is to create generic sensors that can be customized by folk as needed. So the proper fix IMO is to just return a straight datetime object. Which gives the default dashboard string output in this form:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/314384e4-486c-452c-9b2b-7f51ea029303)

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/pull/378

**Comment by AdrianGarside** [comment]
Fixed in:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.4
