### ISSUE TITLE
[Bug] P1P / P1S Camera is not showing anything in LAN only mode

### ISSUE THREAD

**Issue by Darthmonkey** [greghesp/ha-bambulab#386]
### Describe the bug

By default all the MQTT items are showing up correctly and reliably (until I connect with a slicer - but that's a different issue). The problem seems to be that neither my P1P nor my P1S are showing anything on the camera. 

### To Reproduce

Add the Bambu Labs integration to HACS in the usual way.
Connect to the printers in the Configured Integrations page.
List all the controls on the Device information page.
Note that everything shows data except the camera which only shows a date and a broken link.
![image](https://github.com/greghesp/ha-bambulab/assets/3304208/f2154775-d4db-4876-a3f9-8f97ff88cc56)

### Expected Behaviour

I expected the camera to run when a print is running, and the slicer is closed.

### What device are you using?

P1P / {P1S

### Diagnostic Output

```shell
Let me know if a diagnostics log will help in this instance.
```

**Comment by AdrianGarside** [comment]
Please try v2.0.5-dev1.

**Comment by Darthmonkey** [comment]
Thanks, after finding out how to do the beta update, I rebooted, and still no joy on either printer.
![BambuScreenshot](https://github.com/greghesp/ha-bambulab/assets/3304208/a95800e7-dc4a-4bfa-b612-35fe927fcf3a)

**Comment by bunicb** [comment]
Same here on my P1S, tried with v2.0.5-dev1, still doesn't show an image.

**Comment by AdrianGarside** [comment]
Please can you enable debug logs and see if that shows anything.

**Comment by AdrianGarside** [comment]
And also provide diagnostic logs.

**Comment by simonszu** [comment]
I have a similar issue, my camera feed is not loading when the integration connects via cloud. When it connects directly, all is fine. However, this triggers the LAN mode bug of firmware 1.04 ;) 

I also noticed that when i switch from LAN mode to cloud mode, the last captured image is displayed, but the camera entity does not seem to get new information. The regular Home Assistant Log shows nothing.

**Comment by bunicb** [comment]
I set a static DHCP entry and reconfigured it in HA, provided the IP and access code, and it works now.

**Comment by AdrianGarside** [comment]
@Darthmonkey can I confirm you provided the host IP and access code during integration setup? In the lan mode it's impossible to not. But in cloud mode it's optional but required for the camera to be accessible:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/4d14b3bd-ce1d-4d7c-b135-230b7cf2f51a)

**Comment by Darthmonkey** [comment]
Hi Adrian,
Although not a huge security issue, I'm not entirely comfortable posting my logfile for everyone to see. Happy for you to see it, but now I'm not entirely sure this won't get automatically posted to the forum...
If not I'll attach it to the next email.

________________________________

**Comment by AdrianGarside** [comment]
You could start by taking a look through the DEBUG logs when the integration starts up - does it have any obvious errors? In general I try to keep sensitive data out of our logging but I definitely can't guarantee I've done that perfectly. You could review the log for anything that should be there before posting it?

**Comment by Darthmonkey** [comment]
I do have the following errors:
This error originated from a custom integration.

Logger: custom_components.bambu_lab.pybambu
Source: custom_components/bambu_lab/pybambu/bambu_client.py:169
Integration: Bambu Lab (documentation, issues)
First occurred: 08:32:25 (6817 occurrences)
Last logged: 09:29:17

P1S: UNEXPECTED DATA RECEIVED: 0
P1P: UNEXPECTED DATA RECEIVED: 0

and

This error originated from a custom integration.

Logger: custom_components.bambu_lab.pybambu
Source: custom_components/bambu_lab/pybambu/bambu_client.py:130
Integration: Bambu Lab (documentation, issues)
First occurred: 08:31:25 (121 occurrences)
Last logged: 08:32:25

P1S: SSLWantReadError
P1P: SSLWantReadError
Is that enough?

**Comment by AdrianGarside** [comment]
It helps. The top lines are true errors - the printer shouldn't ever be giving no data - it should be either data or the SSLWantReadError. And that bottom SSLWantReadError was incorrect logging on my part - it's not an error but normal behavior when the printer doesn't have data to send yet.

So your printer appears to be failing to send the image data. I'll make some tweaks to improve the logging. I suspect it might result in a huge increase in the number of UNEXPECTED ATA RECEIVED: 0 lines in your log files. 

And to confirm - you're never getting an image - it's not working for a bit then stopping? Is that date listed for the image updating or is it stale from the start (approximately set to when you restarted the integration / home assistant)?

**Comment by AdrianGarside** [comment]
Oh, 6817 occurrences. Yeah your printers are simply not sending any data for some reason. I have no theories for why that might be.

**Comment by AdrianGarside** [comment]
Ok, I was able to reproduce this. You had the wrong access code.

**Comment by AdrianGarside** [comment]
Changes I already made to harden the setup should both prevent this state being reached accidentally and not have the image sensor present if the configuration doesn’t support it.

**Comment by Darthmonkey** [comment]
Wouldn't that mean that all my other sensors would also fail? They've been working fine from the start.
If I try to reconfigure the printers by putting the wrong access code in it fails, but succeeds if I put the correct one in.
![image](https://github.com/greghesp/ha-bambulab/assets/3304208/11c5c8fe-706a-409e-9fbf-a9c8575b0c7d)
Or am I misreading your statement?

**Comment by AdrianGarside** [comment]
Was your original connection also in lan mode or was it via the bambu cloud setup? If lan mode, then yes - my theory wouldn't work as it's the same access code for both the local mqtt connection and the chamber image. I've made various fixes to ensure it properly validates the connection details - earlier versions of 2.0.x didn't do as good a job of checking the IP / access code in the bambu cloud setup flow.

**Comment by Darthmonkey** [comment]
My original connection was using LAN Only mode. Going back to a different issue I was troubleshooting (the 'there can only be one' connection) I reset my P1P to factory defaults a few times, and needed the Handy app to connect it to the network, but that's the only time I ever use it. Both have been in LAN Only mode from the moment I could switch them over.

**Comment by Darthmonkey** [comment]
These are the immediate logs after a reboot showing in the log viewer including the two I already posted if they're of any use:
![image](https://github.com/greghesp/ha-bambulab/assets/3304208/b7474f71-e1df-4bac-9f5f-74d79640d1ce)

**Comment by AdrianGarside** [comment]
Well the only way I know you get the repetitive 0 bytes received error is if the access code is wrong. But if you hit this in lan mode with a working local mqtt connection I don't see how it could be. Can I confirm that your current state is that setting up the integration again from scratch did not repro this?

**Comment by Darthmonkey** [comment]
I am indeed getting access code issues, but after removing the integration, then the HACS integration, rebooting, re-adding, rebooting again, and re-adding the integration, then the two printers with SN IP and Access codes, (both of which are now reporting successfully while the slicer is off - tested turning the light on and off) they're still not showing the camera. This is the latest error:
![image](https://github.com/greghesp/ha-bambulab/assets/3304208/f5c53bb2-aa8d-475c-9039-fdd6203de4fc)

**Comment by AdrianGarside** [comment]
And your printers are both configured to be in lan mode (the printers themselves, not the integration)? I'll have to test that next since your successful local mqtt connection proves the IP and access code are correct.

**Comment by Darthmonkey** [comment]
Yes, both are most certainly in LAN Only mode, and while running a network scan from my PC, I was able to confirm that orca_slicer.exe was opening port 8883 to successfully connect to both printers, and 6000 was open once the camera was running.
I doubt very much if it's worth mentioning, but I also have the MJPEG integration running on Homeassistant, which is successfully streaming a number of Raspberry Pi Cameras. I only mention it as if I had the MJPEG URL, I might be able to add and test it there.

**Comment by AdrianGarside** [comment]
> I set a static DHCP entry and reconfigured it in HA, provided the IP and access code, and it works now.
> 
> Is the IP set only at the time of configuration if not using lan mode?

The IP is set during initial configuration and can be updated later by reconfiguring without removing/re-adding the integration but a static IP entry will be the better solution than having to do that each time your router decides to hand out a different IP address.

**Comment by AdrianGarside** [comment]
> I only mention it as if I had the MJPEG URL, I might be able to add and test it there.

The 'video' feed on port 6000 isn't a real video feed. It's just a stream of individual JPEGs with a preceding 16 byte header. So while it's conceptually equivalent to MJPEG, I don't believe it's structured such than any existing MJPEG player would handle it.

**Comment by AdrianGarside** [comment]
@Darthmonkey it's a long shot - but what cpu hardware is your home assistant running on?

**Comment by Darthmonkey** [comment]
I see where you're going with this, but I'm running on a Pi4 which is running at about 43% of the 2GB RAM and about 5% of the processor.
The access codes have changed a few times, and while testing, I manually re-entered them, but neither start with a 0 currently.
If it's more likely a problem with my system than the printers or integrations, I'm happy to use a different Pi, or run it in a VM to verify?

**Comment by AdrianGarside** [comment]
There was a possibility of a byte ordering issue but a Pi4 would be fine in that regard. But when I experimented with deliberately breaking the initial authentication byte handshake I didn't get the closed connection error you are seeing (which matches the behavior when an incorrect access code is provided) - I got a silent failure where the connection just never got sent any data.

I'm stumped I'm afraid. I just switched one of my printers to lan mode and still had no issues - I was able to connect successfully and the chamber image connection worked as well.

**Comment by AdrianGarside** [comment]
@Darthmonkey do you have any atypical firewall hardware on your network that could be blocking access to the printer?

**Comment by Darthmonkey** [comment]
Well, I did nothing but reboot the P1P (yes, I've done this on many occasions) after Octoprint decided it didn't want to send a print, and BAM! Got them BOTH at the same time... latest update today also.

**Comment by AdrianGarside** [comment]
The only additional change in the latest update was a 12x retry (every 5s for a minute) on initial connect or after a disconnect since some times when the printer is starting a print the connection was getting dropped by the printer.

**Comment by Darthmonkey** [comment]
That would make a lot of sense, although I don't have a firewall on the internal network machine, one of them has a medium-low quality wireless, and occasionally drops out.

**Comment by AdrianGarside** [comment]
Let me know if you have a re-occurrence of the issue. I'm going to mark this as fixed for now.

**Comment by Darthmonkey** [comment]
Okay, odd bonus side effect I wasn't expecting, I can now view both the Orca Slicer AND Homeassistant cameras simultaneously. It still cuts off the other sensors as soon as the slicer connects, but that's a great win!
