### ISSUE TITLE
[Feature] Capitalization in Serial Number

### ISSUE THREAD

**Issue by FriedCheese2006** [greghesp/ha-bambulab#394]
### Describe the feature

When entering the serial number for the device (for the MQTT pub/sub), the serial number is case sensitive. Not realizing this, I spent an embarrassing amount of time trying to figure out why I couldn't connect to a printer that I had the AP board replaced on. I found the issue was I was copy/pasta'ing the serial number from where I had sent it to Bambu support using lower case. Changed it to upper-case and the connection worked. 

So, this request is an enhancement to have the form normalize the input so others don't run into the same issue.

### What device is this for?

X1C

**Comment by AdrianGarside** [comment]
Thanks. I hadn't realized it was case sensitive!
