### ISSUE TITLE
P1S Camera Stopped Working 

### ISSUE THREAD

**Issue by vaderag** [greghesp/ha-bambulab#397]
### Describe the bug

I had the P1S Camera working all fine but since latest firmware update it doesn't seem to pull the feed any more.
I've double checked IP/ access code, but just get the same broken image you get before the LAN details are entered 

### To Reproduce

Unsure if related to latest firmware (1.05) but issue seems to have started after that.

### Expected Behaviour

Camera feed seen

### What device are you using?

P1P

### Diagnostic Output

```shell
On mobile and can't seem to attach - will try in comment once posted
```

**Comment by vaderag** [comment]
[config_entry-bambu_lab-cb3da52db35cde3a5258e99ee9a716bb.json](https://github.com/greghesp/ha-bambulab/files/13839954/config_entry-bambu_lab-cb3da52db35cde3a5258e99ee9a716bb.json)
[error_log.txt](https://github.com/greghesp/ha-bambulab/files/13839955/error_log.txt)

**Comment by vaderag** [comment]
Oddly this just started working again after home assistant updates

**Comment by AdrianGarside** [comment]
Which version of the integration are you using? Was there anything in the logs? The very latest version has rewritten logic for handling the chamber image data and better logging to try and work out what's causing this intermittent issue.

**Comment by vaderag** [comment]
> Was there any errors in the logs? The very latest version has rewritten logic for handling the chamber image data and better logging to try and work out what's causing this intermittent issue although most of the logging requires debug logging to be enabled for the integration.

I didn't directly check the logs so not sure
I'm on the latest version of the integration - if I see it again I'll try log in in desktop and have a closer look

**Comment by AdrianGarside** [comment]
You need the latest v2.05-dev (prerelease/beta) version.
