### ISSUE TITLE
[Feature] HMS mappings

### ISSUE THREAD

**Issue by ImagineerNL** [greghesp/ha-bambulab#4]
Since you requested mapping info in the [HA Bambu thread](https://community.home-assistant.io/t/bambu-lab-x1-x1c-mqtt/489510/197), I thought I'd post my answer here too

the HMS codes are [here](https://wiki.bambulab.com/en/x1/troubleshooting/hmscode), and they seem to map hexadecimal

your examples:

```
attr: 50336000 = in HEX signed 2's 03001100
code: 131074 = in HEX signed 2's : 00020002
```
Doesnt map.

```
attr: 50335744 = in HEX signed 2's 03001000
code: 131074 = in HEX signed 2's : 00020002
```
Doesnt map.

But....

```
attr: 201327360 = in HEX signed 2's 0C000300 
code: 131074 = in HEX signed 2's : 00020002
```
== [HMS_0C00_0300_0002_0002: First layer inspection terminated due to abnormal lidar data](https://wiki.bambulab.com/en/x1/troubleshooting/hmscode/0C00_0300_0002_0002)

So I guess the internal HMS codes are a bunch of statuscodes as reference, but only the errors are linked to troubleshooting, and/or only the ones we as consumers can troubleshoot are posted online.

Would be a nice feature if that part of the integration converted the errorcode to the correct link on the bambu wiki:
```
https://wiki.bambulab.com/en/x1/troubleshooting/hmscode/HMS_ {{ATTR2HEX}}_{{CODE2HEX}}
```

**Comment by AdrianGarside** [comment]
@npike what's a good way to expose the list of HMS errors as a sensor?

We will have:
- Full HMS string
- Description string for documented ones
- Maybe: The URL to the bambu wiki for documented ones

**Comment by npike** [comment]
I sort of like how the nodered flow does it, where the sensor is just a count of current events and the attributes show the actual events.

Afaik this can only be key value pairs, such as HMS code and url, or HMS code and human readable string.

Nothing else comes to mind at the moment.

**Comment by AdrianGarside** [comment]
This is one options to get all 3 in there:
![image](https://user-images.githubusercontent.com/26147576/232398614-fd86a533-682f-4690-a558-3c837f89fead.png)

This is another but now the URL isn't clickable:
![image](https://user-images.githubusercontent.com/26147576/232398859-caaf430d-525c-467e-992c-ccd455cbf47f.png)

**Comment by AdrianGarside** [comment]
Flipping the order doesn't work. Formating is awful and URL is no longer clickable:
![image](https://user-images.githubusercontent.com/26147576/232400403-e55ea24b-e63b-4b6f-a6c2-bcd9c3061a27.png)

**Comment by AdrianGarside** [comment]
Worst case of longest string description length:
![image](https://user-images.githubusercontent.com/26147576/232400633-60b46db0-063e-4871-9d82-138106f75cc1.png)

It's not... awful.

**Comment by AdrianGarside** [comment]
Maybe two entries but formatting is poor:
![image](https://user-images.githubusercontent.com/26147576/232401158-9b6cd0a2-bf2a-4e08-93a0-7d80dc125795.png)

**Comment by AdrianGarside** [comment]
![image](https://user-images.githubusercontent.com/26147576/232402193-de8045bc-8f24-44da-92b8-8f425b2aff95.png)

**Comment by npike** [comment]
I like the 3rd option. I'm not sure if the HMS code itself is very actionable by an end user - most maybe just want to display the next in a notification with an action to open url?

**Comment by AdrianGarside** [comment]
My concern with that was how would you access the value when the dictionary key wasn't known to you/automation. Currently I've checked in that very last option to the dev branch but trying this out to see if it's a little more visually appealing:
![image](https://user-images.githubusercontent.com/26147576/232548984-6dab0657-1f42-48f9-966d-3711fad701e0.png)

**Comment by npike** [comment]
Fair enough, that looks like it would work pretty well! Thanks
