### ISSUE TITLE
[Feature] Language change

### ISSUE THREAD

**Issue by DandeMC** [greghesp/ha-bambulab#407]
### Describe the feature

Hello. is it possible to get an option to change the language? Currently I delete the de.json file after every update so that the integration is set to english.

### What device is this for?

A1

**Comment by AdrianGarside** [comment]
AFAIK there is no way for an integration to override the HA language.

**Comment by DandeMC** [comment]
But if I delete the de.json it changes the language. Why can't this be included as an option?

**Comment by AdrianGarside** [comment]
As in have the integration itself delete its own files out from under home assistant?

**Comment by DandeMC** [comment]
It is sufficient if the language can be selected and then the appropriate json file is loaded. i cannot say whether the others have to be deleted or renamed for this.

**Comment by AdrianGarside** [comment]
AFAIK there is no way for an integration to override the Home Assistant set language.

**Comment by DandeMC** [comment]
The language is changed to English when the appropriate language file is deleted in the integration. I therefore think that it would be possible to choose between the language selected in home assistant and English.
Maybe you can find a way. I continue to delete the de.jason in the integration.

**Comment by AdrianGarside** [comment]
The default in home assistant is English. So if you delete the German language file it will fall back to English. But integrations cannot control the home assistant choice of language - all the integration does is provide the language files. Home assistant decides which to use. If you want all of home assistant in English that is trivial. It's set by going to Settings->System->General->Language.
