### ISSUE TITLE
[Feature] A1: Allow to switch sound ON or OFF

### ISSUE THREAD

**Issue by briceparent** [greghesp/ha-bambulab#416]
### Describe the feature

Amazing integration, thanks a lot! 

My feature request: It would be nice to be able to :

* know whether the printer's sound is ON or OFF (does it play the music when a print job starts and finishes?)
* switch the sound ON or OFF, manually or using an automation (don't play sound between 10PM and 7AM for example. Longer jobs can end at whatever time)

I'm not sure that there is an API endpoint at all for that on the printer though!

Thanks!

### What device is this for?

A1

**Comment by AdrianGarside** [comment]
Is this something that Bambu Studio or the Handy app allows you to control manually today?

**Comment by AdrianGarside** [comment]
Ok. So I know I can read those config setting. But I don't know yet how to set them so some research needed..

**Comment by briceparent** [comment]
Thanks a lot for your time and effort!

**Comment by AdrianGarside** [comment]
ENABLE_PROMPT_SOUND  = {"print" : {"sequence_id": "0", "command": "print_option", "sound_enable": True}}
DISABLE_PROMPT_SOUND = {"print" : {"sequence_id": "0", "command": "print_option", "sound_enable": False}}

**Comment by AdrianGarside** [comment]
@briceparent can you please try this:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.14-add_A1_prompt_sound_control

I don't have an A1 so I'm unable to test this.

**Comment by AdrianGarside** [comment]
No response. I can't test this so if someone wants to stand up and work with me to test the code I already implemented I can merge it in. Until then...
