### ISSUE TITLE
[Bug] AMS Colors Padded with 'FF'

### ISSUE THREAD

**Issue by FriedCheese2006** [greghesp/ha-bambulab#417]
### Describe the bug

I have two X1Cs with AMS. I have the integration setup in local mode. All of the filament color attributes are padded with FF.

![image](https://github.com/greghesp/ha-bambulab/assets/49689423/1b0d36ed-efab-493b-aeb1-fc76041644cd)

### To Reproduce

View "color" attribute of filament in AMS

### Expected Behaviour

Not padded.
[config_entry-bambu_lab-a4dd9572e56847f7dd333e2ca6c21104.json.txt](https://github.com/greghesp/ha-bambulab/files/13875558/config_entry-bambu_lab-a4dd9572e56847f7dd333e2ca6c21104.json.txt)

### What device are you using?

X1C

### Diagnostic Output

```shell
Couldn't attach a file here so I attached it under "Expected Behaviour" (drag and drop did not work).
```

**Comment by FriedCheese2006** [comment]
I take it back. This isn't a bug with the integration per se. The MQTT information has the color code padded.

**Comment by jphoke** [comment]
Hmmm -- is the MQTT data always suffixed with "FF" then? If so it should be stripped off to allow for using the attribute with css for example on dashboards IMO

**Comment by fmeus** [comment]
The hex color is a valid color. There is no need to remove the suffix code, this denotes the opactiy of the color. 

CSS supports this. I am making use of the color attribute on my dashboard without any issues.

```
  - type: custom:template-entity-row
    entity: sensor.x1c_00m09a341900619_ams_1_tray_1
    name: Tray 1
    color: '{{ state_attr(config.entity,''color'') }}'
    icon: |-
      {% if state_attr(config.entity, 'active') %}
        mdi:printer-3d-nozzle
      {% else %}
        mdi:printer-3d-nozzle-off
      {% endif %}
    secondary: >-
      Color = {{ state_attr(config.entity,'color') }}, Remaining = {{
      state_attr(config.entity,'remain') }} %
```
<img width="504" alt="Screenshot 2024-01-09 at 20 55 03" src="https://github.com/greghesp/ha-bambulab/assets/743402/6b4a3c85-ec63-4937-b6e2-88457ed7c19a">

**Comment by FriedCheese2006** [comment]
Closing as a non-issue.

**Comment by AdrianGarside** [comment]
@FriedCheese2006 this isn't a bug. It's by design. The 0xFF is the alpha value and Bambu allows (inconsistently) you to specify transparent filaments.

**Comment by jphoke** [comment]
Thanks -- completely forgot about the alpha value/channel in hex 🤦🏼‍♂️
