### ISSUE TITLE
[Feature] Camera stream only while printing or on request

### ISSUE THREAD

**Issue by crosserSniper** [greghesp/ha-bambulab#423]
### Describe the feature

My Homeassistant-Logfile is full with camera P1S has changed.
It would be great, if the image is only refreshing while printing, or on request - for example when the picture was pressed.

![grafik](https://github.com/greghesp/ha-bambulab/assets/110885066/f34191de-0c8e-465e-8f3a-d974a0eef19f)

### What device is this for?

P1S

**Comment by niklerus** [comment]
I second that, the camera never stops unless you power cycle the printer (and then you need to restart HA to get camera to start)
Logfile gets an updated entry every second as it is now.

**Comment by kiwiholmberg** [comment]
I added configuration  to exclude events from the camera since they were extremely spammy. Goes in your global HA configuration.yaml:

```` 
logbook:
  exclude:
    entities:
      - image.p1s_01pxxxxxxxx_camera
      
```

**Comment by cahdero** [comment]
> I added configuration to exclude events from the camera since they were extremely spammy. Goes in your global HA configuration.yaml:
> 
> ```yaml
> logbook:
>   exclude:
>     entities:
>       - image.p1s_01pxxxxxxxx_camera
>       
> ```

I've tried this...continues to record camera updates..

**Comment by niklerus** [comment]
I disabled the entity for now, hoping it will be fixed in the near future.

**Comment by miabilabs** [comment]
Adding a vote here. I've unfortunately disabled the entity as well.

**Comment by AdrianGarside** [comment]
> I added configuration to exclude events from the camera since they were extremely spammy. Goes in your global HA configuration.yaml:
> 
> ```yaml
> logbook:
>   exclude:
>     entities:
>       - image.p1s_01pxxxxxxxx_camera
>       
> ```

Is that working for you? It doesn’t for me. What version of home assistant are you running?

**Comment by cahdero** [comment]
> > > I added configuration to exclude events from the camera since they were extremely spammy. Goes in your global HA configuration.yaml:
> > > ```yaml
> > > logbook:
> > >   exclude:
> > >     entities:
> > >       - image.p1s_01pxxxxxxxx_camera
> > >       
> > > ```
> > 
> > 
> > Is that working for you? It doesn’t for me. What version of home assistant are you running?
> 
> Yes it works. I no longer see the events for the camera in the logbook. Running HAOS 11.2, the printer is in LAN mode. To be extra clear, you'll have to change the entity name in the filter to match whatever your camera entity name is 🙂

You’ll want to utilize the “record” function and not the “logbook” function. It still get recorded just doesn’t show on the logbook. Also if using the record function it doesn’t show on the logbook bag but only when you filter for the actual camera entity for some reason

**Comment by niklerus** [comment]
> > I second that, the camera never stops unless you power cycle the printer (and then you need to restart HA to get camera to start) Logfile gets an updated entry every second as it is now.
> 
> It’s a bug if you have to restart the printer to get the camera working again. I fixed a bug recently that led to that if you were connecting via the Bambu cloud Mqtt service instead of direct to the printer.

You've misread a bit, I said that I need to restart HA to get the camera to work again if I stop the logflow from the printer by restarting the printer.

**Comment by AdrianGarside** [comment]
I spent some time over the weekend trying to get recorder and logbook exclusions to work with no success - they’re still spamming the system. So I wonder what’s different for folk that have gotten it to behave as advertised.

**Comment by AdrianGarside** [comment]
> > > I second that, the camera never stops unless you power cycle the printer (and then you need to restart HA to get camera to start) Logfile gets an updated entry every second as it is now.
> > 
> > 
> > It’s a bug if you have to restart the printer to get the camera working again. I fixed a bug recently that led to that if you were connecting via the Bambu cloud Mqtt service instead of direct to the printer.
> 
> You've misread a bit, I said that I need to restart HA to get the camera to work again if I stop the logflow from the printer by restarting the printer.

Sorry I mistyped. I mean it’s a bug if you have to restart home assistant after you restarted the printer to get the camera working again. It should automatically reconnect without any intervention.

**Comment by AdrianGarside** [comment]
> > > > I added configuration to exclude events from the camera since they were extremely spammy. Goes in your global HA configuration.yaml:
> > > > ```yaml
> > > > logbook:
> > > >   exclude:
> > > >     entities:
> > > >       - image.p1s_01pxxxxxxxx_camera
> > > >       
> > > > ```
> > > 
> > > 
> > > Is that working for you? It doesn’t for me. What version of home assistant are you running?
> > 
> > 
> > Yes it works. I no longer see the events for the camera in the logbook. Running HAOS 11.2, the printer is in LAN mode. To be extra clear, you'll have to change the entity name in the filter to match whatever your camera entity name is 🙂
> 
> You’ll want to utilize the “record” function and not the “logbook” function. It still get recorded just doesn’t show on the logbook. Also if using the record function it doesn’t show on the logbook bag but only when you filter for the actual camera entity for some reason

I can't get recorder exclusion to work for these images by any means:
recorder:
  exclude:
    domains:
      - image
    entity_globs:
      - image.p1p*
    entities:
      - image.p1p_SERIAL_camera

None of domains, entity_globs or entities work to stop the state change being recorded and present in the logbook every 1-2 seconds. Were you able to get this to work?

**Comment by AdrianGarside** [comment]
My testing was flawed. The logbook *pane* in the device view shows pre-filtered changes. The actual logbook was properly excluding.

You can avoid this with either:
```
recorder:
  exclude:
    entities:
      - image.p1p_SERIAL_camera
      - sensor.p1p_SERIAL_wi_fi_signal
```
or
```
logbook:
  exclude:
    entities:
      - image.p1p_SERIAL_camera
      - sensor.p1p_SERIAL_wi_fi_signal
```

**Comment by sabaatworld** [comment]
Is it possible to expose camera as a `camera` entity? It would be easier to work with and also avoid the above issues.

**Comment by jawilson** [comment]
> Is it possible to expose camera as a `camera` entity? It would be easier to work with and also avoid the above issues.

I've added PR #595 to implement this.

**Comment by AdrianGarside** [comment]
Resolving as completed with #595
