### ISSUE TITLE
[Feature] Ability to change the saved Printer IP Address

### ISSUE THREAD

**Issue by cmeans** [greghesp/ha-bambulab#43]
**Describe the feature**
Mechanism to change the IP address of the printer, maybe in the System Options dialog.  Currently, the initially provided IP address appears to be hidden away (I'm a n00b in HA, so may be somewhere obvious).  Seems reasonable to allow the user to manually change it if needed (without having to delete the printer and start again).

**Device Type(please complete the following information):**
 - Printer: X1C & P1P
 - Firmware Version: N/A

**Comment by zuidwijk** [comment]
Agree with this feature :)

My advice for @cmeans : give the printer a "fixed" ip via dhcp reservation. That way no other wifi device can get that IP, only the reserved MAC address of the printer.

Nevertheless... I've changed some IP's in my network and therefore it would be nice to change the ip address...

**Comment by cmeans** [comment]
Thanks @zuidwijk 
I've already assigned a "fixed" IP (just assigned the one it started with so things weren't broken in AH), however, I prefer to have "servers" in a particular range, which means I need to change the IP assigned at random.  Until I can change the value used by the AH AddOn (without deleting and starting again), I'm stuck without this feature.

**Comment by zuidwijk** [comment]
> Thanks @zuidwijk
> I've already assigned a "fixed" IP (just assigned the one it started with so things weren't broken in AH), however, I prefer to have "servers" in a particular range, which means I need to change the IP assigned at random. Until I can change the value used by the AH AddOn (without deleting and starting again), I'm stuck without this feature.

Yeah exactly what I'm experiencing :)

**Comment by AdrianGarside** [comment]
Fixed with #62 which was merged into main earlier today and is in the 1.0.0 release.
