### ISSUE TITLE
[Feature] Cloud or SD Card Print identifier

### ISSUE THREAD

**Issue by beef76** [greghesp/ha-bambulab#456]
### Describe the feature

Not sure if the printer (X1C) is providing such information as well, but would be great to see if the actual print was started from SD Card or was initiated via Bambu Cloud (Studio). This could be used to make the entity image visible or hidden as prints from SD card do not have any entity image available (unfortunately)

### What device is this for?

X1C

**Comment by AdrianGarside** [comment]
That should be possible.

**Comment by AdrianGarside** [comment]
Zeldo made the icon change which is very nice but I think we'll want to expose the print source as an actual sensor value to allow automations to be built on top of it.

**Comment by beef76** [comment]
Awesome 👏🏻 thanks for making this happen 🤜🏻🤛🏻
