### ISSUE TITLE
[Bug] A1 camera feed "taken"

### ISSUE THREAD

**Issue by eried** [greghesp/ha-bambulab#460]
### Describe the bug

A1 camera does not work on the app or Bambu Studio reliable when this is installed on HA

### To Reproduce

1. Install this, configure it. 
2. Try to open the camera on HA, then close HA
3. Camera now will not be available on bambu handy or bambu studio, sometimes it will work again but not as before

### Expected Behaviour

Maybe a switch to disable the camera will fix the issue?

### What device are you using?

A1

### Diagnostic Output

```shell
Not needed
```

**Comment by AdrianGarside** [comment]
I'd be interested to know if the just released firmware changes this. I was seeing fragility in the handy app video feed with the P1 1.4 firmware but it seems to be solid now with the 1.5 firmware.

**Comment by Misiu** [comment]
I have A1 and even without this integration I often get a black screen in the handy app or the studio. I have no idea why this happens, I think it's not related to this integration.

**Comment by AdrianGarside** [comment]
That's true. Before I had the camera image added to the integration I was seeing it being very flaky / not loading in the handy app with my P1P. When they enabled cloud access the reliability for viewing it tanked with way slower startup perf even when it worked and frequently it failed to work.

**Comment by eried** [comment]
> I have A1 and even without this integration I often get a black screen in the handy app or the studio. I have no idea why this happens, I think it's not related to this integration.

Yes, sometimes, but with the integration in my case it is ALWAYS being displayed flawesly on HA, not on handy unless I reboot HA and spam handy refreshing the camera, then I get it on the app for a while until HA takes over again.

**Comment by eried** [comment]
> I'd be interested to know if the just released firmware changes this. I was seeing fragility in the handy app video feed with the P1 1.4 firmware but it seems to be solid now with the 1.5 firmware.

No changes on lates firmware, on the beta was broken for both tho (at least on my A1). Now it is always working on HA. I wish the stream was liberated if it was not used tho... it is weird to see it always black in the app

**Comment by AdrianGarside** [comment]
The latest dev release:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.15-dev4

Persists your choice of manual refresh mode. Does turning on manual refresh mode in the integration unbreak your camera feed in the handy app?

**Comment by eried** [comment]
> Persists your choice of manual refresh mode. Does turning on manual refresh mode in the integration unbreak your camera feed in the handy app?

This version seems to fix the issue :) I will test more later, when the printer is running to notice the update rate

**Comment by eried** [comment]
Actually it is still the same problem 😵 maybe an easier solution would be to add a function to detach the stream? Manually

**Comment by AdrianGarside** [comment]
Turning on manual refresh mode detaches all connections to the printer including for the camera images.

**Comment by eried** [comment]
> Turning on manual refresh mode detaches all connections to the printer including for the camera images.

oh ok! I will test. Will the odometer keep the right count if the manual mode is on?

**Comment by AdrianGarside** [comment]
No it won't. The integration basically has to be running continuously while a print is occurring for that to work.
