### ISSUE TITLE
[Bug] File name overflows in dashboard if too long

### ISSUE THREAD

**Issue by moebis** [greghesp/ha-bambulab#473]
### Describe the bug

As the title says, picture is a thousand words:

<img width="611" alt="Screenshot 2024-02-24 at 12 45 12 PM" src="https://github.com/greghesp/ha-bambulab/assets/3595244/746d4759-f034-4eae-a965-a6b76df978b7">

### To Reproduce

Print a file with a long enough filename to overflow.

### Expected Behaviour

ellipsis ... to truncate

### What device are you using?

X1C

### Diagnostic Output

```shell
Not nessesary
```

**Comment by AdrianGarside** [comment]
This is a home assistant bug so you'll need to log a bug on the home assistant github. This integration has no involvement in what's rendered in the dashboard - it just provides. the data.

**Comment by moebis** [comment]
@AdrianGarside ...nope, this is a bug with your code. Everything else respects the truncation in Home Assistant. Its just your add on that has this issue out of dozens that I run:

<img width="350" alt="image" src="https://github.com/greghesp/ha-bambulab/assets/3595244/04228c12-cc14-48e8-a7ab-43d60c8ae61e">

**Comment by AdrianGarside** [comment]
Those aren't the same thing. The strings being truncated there is the sensor name not the sensor content. There is literally not a single line of code in the integration that has any direct control over the home assistant UX. All it does is provide data.

**Comment by AdrianGarside** [comment]
Here is an example of a sensor name from this integration being truncated exactly as in you two screen snips above:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/c6e89578-e5dd-4448-a73f-2d5090f5307d)

**Comment by moebis** [comment]
It's because you're not using a property name, just a cloud icon and then the 1st element is the filename, try adding "File:" in the 1st column, and move the filename to the 2nd. If you see how you have "X1C Print..." and then the 3rd element "Smooth PEI" it's fine. I think this is the reason the text-overflow and white-space properties are being ignored from the case CSS.

<img width="690" alt="Screenshot 2024-02-24 at 2 20 52 PM" src="https://github.com/greghesp/ha-bambulab/assets/3595244/0a4479f3-65e2-4ab7-aaab-4b8bee970cc8">

**Comment by moebis** [comment]
That's also why there is a blank space in front of "Optimized...." you just skipped a css block.

**Comment by AdrianGarside** [comment]
Again, the integration has literally zero lines of code to control the UX. There Is no CSS in the integration.

The reason you aren't seeing the sensor name in your example is because home assistant has truncated it down to non-existant. The integration has zero involvement or control over that.

**Comment by AdrianGarside** [comment]
This is what it looks like when it's almost entirely truncated the sensor name to nothing:
![image](https://github.com/greghesp/ha-bambulab/assets/26147576/bc4bfa2c-88d4-44fb-8e26-bcfbf5dbb9d0)

Your example is just so extreme home assistant clipped the sensor name down to nothing - only the small gap between the zero sized sensor field and the text remains on the left of the text.

**Comment by AdrianGarside** [comment]
Your top sensor example is HA handling something it can line wrap (has spaces in the string) differently.
