### ISSUE TITLE
[Tuya Blueprint] 

### ISSUE THREAD

**Issue by MrAredhone** [greghesp/ha-bambulab#481]
### Describe the feature

hay there im realy new to this so im not even sure if im in the right place
but you have a wled blueprint but can you add a tuya blueprint aswell
i tryde converting your blueprint to a tuya one but the light only flashes every phew secconds 
please let me know if im in the wrong place
thanks in advvanced

### What device is this for?

X1C

**Comment by AdrianGarside** [comment]
I'm open to someone else building that but I don't want to get stuck with a broken and unmaintained one the way I did when someone else did that for wled.
