### ISSUE TITLE
[Feature] Catch 'filament runout' state?

### ISSUE THREAD

**Issue by sergeolkhovik** [greghesp/ha-bambulab#489]
### Describe the feature

Hi! I'd like to catch filement runout event and send some notifications via HA.
As I can see there're 2 main sensors available in this integration: _print_status and _current_stage.
Unfortunately I don't see any such event there (even I see paused_filament_runout here: https://github.com/greghesp/ha-bambulab/issues/483). I just got new filament loaded and checked HA history:

![image](https://github.com/greghesp/ha-bambulab/assets/5941860/61532439-d100-4636-a7a3-46ed6f86299c)

and 

![image](https://github.com/greghesp/ha-bambulab/assets/5941860/f3b9fb20-093e-4f46-a851-859cc8ae5357)

So either this event isn't sent from the printer or there's a bug in this integration?

### What device is this for?

P1S

### Other Information

HA 2024.1.0 + LAN mode configuration.

**Comment by AdrianGarside** [comment]
Bambu has a whole bunch of stages defined that they never actually generate. Instead filament runout is an HMS error. You can connect notifications to the existing hms error event that's raised but it's a bit noisy. I'm planning to add specific events for common cases like that.

**Comment by sergeolkhovik** [comment]
As I see HMS is just a binary sensor that shows either OK status or error:

![image](https://github.com/greghesp/ha-bambulab/assets/5941860/a2944218-f063-4b1f-b495-4cd07e84c809)

So not sure that it can help in filament runout state catching.
Anyway for now HA is generating an alert with 2 minutes repeat if printing is paused so at least this works for me in filament runout situation.
