### ISSUE TITLE
[Feature] Set bed temperature

### ISSUE THREAD

**Issue by Riincewiind** [greghesp/ha-bambulab#491]
### Describe the feature

Currently I can only read out the temperature from the X1C, but not set it.
I would like to set also the temperature of the bed.

usecase:
I am printing a lot with ABS. When the bed cools down after a print, the printed object pops off the bed. The strain in the object sometimes leaves white marks/shadows (visible e.g. on black ABS), which can be easily removed by simply heating up the object again for some minutes on the bed.
So i would like to realize an automation that gets triggered after print is finished, then waits until bed temperature is below 40°C for some minutes, then heats up to 100°C for 10min, then cools down finally.

### What device is this for?

X1C

**Comment by sabaatworld** [comment]
I would like to +1 this feature request. Somehow the Panda touch display is able to do it, so I suppose it should be possible with local API. It would be pretty useful with various automations.

**Comment by AdrianGarside** [comment]
It will be possible to add this. But Bambu is almost certainly going to block this at some point given their statements after Panda Touch got announced.

**Comment by tool666schism** [comment]
Would love to see the ability to set nozzle temperature added as well

**Comment by TomN7** [comment]
I'd like to +1 this as well - I hoped to create an automation that could set the bed temperature of my P1S and then send me a notification when the chamber had reached a warm enough ambient temperature for printing ABS (using a zigbee temperature sensor).

**Comment by MarcelLieb** [comment]
I would love this feature too. The P1S currently doesn't have a dedicated feature for filament drying, but by being able to set the bed temperature via Home Assistant, I could implement a similar feature myself.

**Comment by Nocturneit** [comment]
+1 on this feature

**Comment by roomonthethird** [comment]
+1

**Comment by Skydev0h** [comment]
It seems that you can set bed temperature by sending `GCode M140 S<temp>` and nozzle temperature is `M104 S<temp>` [1]
And the GCode in question can be sent using print.gcode_line [2, 3]

Ref:
1. https://github.com/bambulab/BambuStudio/blob/master/src/slic3r/GUI/DeviceManager.cpp#L1750
2. https://github.com/bambulab/BambuStudio/blob/master/src/slic3r/GUI/DeviceManager.cpp#L4910
3. https://github.com/Doridian/OpenBambuAPI/blob/main/mqtt.md#printgcode_line

**Comment by Skydev0h** [comment]
@Riincewiind @tool666schism 

It seems that you can set bed temperature by sending GCode `M140 S<temp>` and nozzle temperature is `M104 S<temp>` [1]
And the GCode in question can be sent using print.gcode_line [2, 3]

Ref:
1. https://github.com/bambulab/BambuStudio/blob/master/src/slic3r/GUI/DeviceManager.cpp#L1750
2. https://github.com/bambulab/BambuStudio/blob/master/src/slic3r/GUI/DeviceManager.cpp#L4910
3. https://github.com/Doridian/OpenBambuAPI/blob/main/mqtt.md#printgcode_line

@AdrianGarside I dont think BambuLab will ever block this cause it will break functionality of their own Bambu Studio, and print.gcode_line is a pretty low-level and core feature.

**Comment by Skydev0h** [comment]
By the way there is already a logic using gcode_line to set fan temperatures, so this should not be too hard to implement:

https://github.com/greghesp/ha-bambulab/blob/main/custom_components/bambu_lab/pybambu/models.py#L323

**Comment by AdrianGarside** [comment]
> @AdrianGarside I dont think BambuLab will ever block this cause it will break functionality of their own Bambu Studio, and print.gcode_line is a pretty low-level and core feature.

@Skydev0h they block it when it is sent directly to the local printer when the printer is connected to bambu cloud. So you either have to configure the print in lan mode or in full bambu cloud mode (talking to bambu cloud mqtt service).

**Comment by Skydev0h** [comment]
> @Skydev0h they did block it when it is sent directly to the local printer when the printer is connected to bambu cloud. So you either have to configure the print in lan mode or in full bambu cloud mode (talking to bambu cloud mqtt service).

That is quite strange, cause I have successfully adjusted heatbed temp with gcode via LAN MQTT with printer connected to cloud at the same time.

**Comment by AdrianGarside** [comment]
What printer and printer firmware?

**Comment by Skydev0h** [comment]
> What printer and printer firmware?

X1C
Firmware: 01.08.02.00
Hardware: AP05

**Comment by Skydev0h** [comment]
@AdrianGarside, take a look at this. Bambu Studio is connected with cloud, and MQTT Explorer sends command with LAN.

https://github.com/user-attachments/assets/b86497a5-1084-434e-a45b-f5095fd4210c

**Comment by jneilliii** [comment]
The X1 will work with both, the A1/P1 series printer I believe blocks local access when cloud connected.

**Comment by Skydev0h** [comment]
> The X1 will work with both, the A1/P1 series printer I believe blocks local access when cloud connected.

It seems you are right, but the MQTT is blocked in entirety - not the specific gcode_line or M140 / M104 codes.

**Comment by AdrianGarside** [comment]
Mqtt isn’t blocked entirely - just the commands that change printer state in a way that ‘could’ be damaging and enough to break panda touch.

**Comment by Skydev0h** [comment]
> Mqtt isn’t blocked entirely - just the commands that change printer state in a way that ‘could’ be damaging and enough to break panda touch. And panda touch is P1 only so I guess somehow the X1 doesn’t need that same ‘safety’ fix. :p
> 
> unless they’ve changed it again the P1 will accept 4 local connections

Interestingly enough, when I connect to P1 both MQTT Explorer and mqttMultimeter kinda work but the connection is broken at the moment when I attempt to subscribe to anything >_<

And the /request messages seem to be not delivered to the printer.

**Comment by AdrianGarside** [comment]
You must subscribe to the exact topic - you can't just do a wildcard subscribe on the P1/A1 printers.

**Comment by Skydev0h** [comment]
> You must subscribe to the exact topic - you can't just do a wildcard subscribe on the P1/A1 printers.

Oh, thanks, I noticed that entered serial number of the wrong P1, lol.
And that you can't subscribe to the /request topic.

**Comment by Skydev0h** [comment]
@AdrianGarside indeed, it seems that any command with `M140` or `M104` in it does not work locally.

However, you can use `M190` to set heatbed temperature and `M109` to set nozzle temperature.
The only drawback is that it waits for the temperature to be set, but it should be enough for some cases (such as changing heatbed temperature after the printing is completed).

Also, it may be possible that you can append `M108` command to "break and continue", but I have not tested it - it may either not work or have side effect of breaking something not intended to (such as if printer is waiting for nozzle temp, but it would break out of that by setting heatbed temp), or possibly it only affects local scope of gcode or M190 / M109 would not wait in such case altogether, idk.

**Comment by Skydev0h** [comment]
Implemented in #672, feel free to comment and adjust as you see fit.
Tested on X1C and P1S in LAN mode.

**Comment by AdrianGarside** [comment]
Awesome. I will take a look when the dust settles from Bambu's required verification code rollout.
