### ISSUE TITLE
[Feature] Pass device names in automations

### ISSUE THREAD

**Issue by RyanEwen** [greghesp/ha-bambulab#497]
### Describe the feature

It would be really nice to have the name of the printer that triggered an automation passed into the automation actions when handling device events such as print completed or print paused.

Use case: I have 5 P1S printers and don't want to create automations for each combination of printer and event type that I want to handle. I would instead like to create one automation for each event type, triggered by any of my printers, and have the name of the particular printer (as defined in HA rather than Bambu Cloud) that triggered the automation available to use in the resulting action.

For example, I currently have this automation that sends a message to my phone when a print is complete, but I cannot tell which printer triggered the automation, so the message I send to my phones simply says that a print completed. Which print, I don't know:
![image](https://github.com/greghesp/ha-bambulab/assets/1136808/d645c12f-6e5b-485b-9975-8ee127ab260c)

### What device is this for?

P1S

**Comment by RyanEwen** [comment]
> Curious why you would prefer the HA name over the Bambu cloud one?

Since it's an HA automation I just figured it made the most sense to use the names as defined in HA, but either (or both) would be nice.

**Comment by AdrianGarside** [comment]
Fixed in https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.38-dev4

**Comment by AdrianGarside** [comment]
Note that the cloud name is only ever set once during initial printer addition via Bambu cloud. It does not automatically react to changing the name in Bambu cloud as I would have to poll for that and risk throttling and cloudflare blocks which isn't worth the risk.
