### ISSUE TITLE
[Feature] blueprint compatibility with non WLED light entities

### ISSUE THREAD

**Issue by killtux** [greghesp/ha-bambulab#499]
### Describe the feature

it would be cool if you can add non wled light entities. for example i use a simple 5v cob led stripe that is integrated over esphome as light in Home Assistant but i cant choose it since it doesnt run over the wled integration.

### What device is this for?

X1C

**Comment by AdrianGarside** [comment]
You can set up custom automations very easily in HA to control simple lights. A common one people do is turning the chamber light on at the start of the print and off at the end. Or on when you open the door on the X1C and off when you close it.
