### ISSUE TITLE
[Feature] New Entity: Filament Costs

### ISSUE THREAD

**Issue by gbomacfly** [greghesp/ha-bambulab#509]
### Describe the feature

Hi there,

is it possible to add the Filament costs for the actual print?

### What device is this for?

X1C

**Comment by AdrianGarside** [comment]
Doesn't look like that's exposed in the data the printer provides. It can be calculated from the filament usage length and the spool cost. But the spool cost is only known to the slicer I think.

**Comment by gbomacfly** [comment]
Sad, but thanks :)

**Comment by jperquin** [comment]
filament usage weight is not exposed in LAN-only mode..

**Comment by AdrianGarside** [comment]
Yes, it comes from the Bambu cloud API so is only available when the printer is not in lan mode.
