### ISSUE TITLE
[Bug] Print Job Start/End/Remaining times unavailable

### ISSUE THREAD

**Issue by MwC-Trexx** [greghesp/ha-bambulab#512]
### Describe the bug

When print jobs are running the following entities are unavailable:

- Start Time
- End Time
- Remaining Time

### To Reproduce

Perform a print job and review entities for the print device

### Expected Behaviour

The print jobs should be updating the device entities to show job stats for start, finish(end), and remaining time.

[config_entry-bambu_lab-4dc739e7ee3dd96a8e872ec5737f6920.json](https://github.com/greghesp/ha-bambulab/files/15068478/config_entry-bambu_lab-4dc739e7ee3dd96a8e872ec5737f6920.json)
[bambu_labs.log](https://github.com/greghesp/ha-bambulab/files/15068481/bambu_labs.log)

### What device are you using?

X1C

### Diagnostic Output

```shell
See attached
```

**Comment by AdrianGarside** [comment]
Start/end time get set to unavailable if we have no end time so somehow we failed to get that. Remaining time has no holdback though - what was that showing?

Looking at your provided diagnostic data it seems they've removed gcode_start_time from the mqtt payload on the X1 in the latest firmware - it now matches the P1 series where I have to get the start time by observing the print start or (if available) using the cloud print data.

**Comment by MwC-Trexx** [comment]
I just confirmed it does show remaining time while the print job is running.  

Instead of ‘unavailable’ when no job is active, maybe change it to N/A (if printer status is idle) and unavailable (if no value when a job is running but there is no value or device unavailable).

That way helps differentiate between there is an issue with the integration vs expected behavior.

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.20
