### ISSUE TITLE
[Bug] AMS failed to pull back filament not being reported as HMS error any more?

### ISSUE THREAD

**Issue by AdrianGarside** [greghesp/ha-bambulab#515]
### Describe the bug

On my P1S just now I got:
      "print_error": 117473284,
and
      "hms": [],

Bambu Handy showed me the error once I opened it but since the mqtt payload had no hms errors, I didn't get a notification from HA like I shold have.

### To Reproduce

.

### Expected Behaviour

.

### What device are you using?

P1S

### Diagnostic Output

```shell
.
```

**Comment by AdrianGarside** [comment]
print_error = 0x07008004

**Comment by LRomandine** [comment]
+1 I just encountered this today

**Comment by LRomandine** [comment]
#529 fixes this error code but there are other errors I have seen that are not reported via MQTT. [More details in 529 comment](https://github.com/greghesp/ha-bambulab/pull/529#issuecomment-2170532238).

I vote this issue is closed (I do not have permission) as this issue is resolved.
