### ISSUE TITLE
[Bug] Chamber-fan speed 10% incorrect

### ISSUE THREAD

**Issue by EddyK69** [greghesp/ha-bambulab#522]
### Describe the bug

The chamber-fan speed seems to be showing incorrect; it's 10% off compared to Bambu Studio and BTT Panda Touch.

**Bambu Studio:**
<img width="419" alt="Scherm­afbeelding 2024-05-02 om 11 15 28" src="https://github.com/greghesp/ha-bambulab/assets/13943630/6bbdeb4a-68b4-4831-929f-5bb4866b7c31">

**Panda Touch:**
![IMG_1722 normaal](https://github.com/greghesp/ha-bambulab/assets/13943630/0faa86a6-a259-4ed3-80b5-e7d0f8af2562)

**HA-integration:**
<img width="323" alt="Scherm­afbeelding 2024-05-02 om 11 12 32" src="https://github.com/greghesp/ha-bambulab/assets/13943630/17fa90a4-ca4f-45ae-9511-aa8c4f1c1791">

### To Reproduce

-

### Expected Behaviour

-

### What device are you using?

P1S

### Diagnostic Output

```shell
-
```

**Comment by AdrianGarside** [comment]
Looks like they fixed their bug. I used to be 10% off and had to tweak the rounding to get the same behavior as Bambu Studio even though BS was incorrectly rounding.

**Comment by AdrianGarside** [comment]
I'm not reproducing this. All 3 (integration, bambu handy and bambu studio) show the same percentage.
