### ISSUE TITLE
[Feature] include the actual SN in AMS tray attributes

### ISSUE THREAD

**Issue by ppptmstr** [greghesp/ha-bambulab#523]
### Describe the feature

The AMS tray attributes include "Spool serial number", however the value in the entity attributes is the tag_uid, whereas the SN in Bambu studio is tray_uuid.
1. In Bambu studio, go to device screen
2. click the 'eye' below any Bambu spool in the AMS slots. There is a line with the "SN" below nozzle temperatures.
3. Verify the SN value displayed corresponds to the tray_uuid value sent in MQTT
4. Check the tray attributes in HA: the tag_uid is the value shown in Bambu Handy

It'd be nicer if the entity attributes also contain the SN shown in Bambu studio.

### What device is this for?

AMS

**Comment by AdrianGarside** [comment]
Fixed with #657

**Comment by AdrianGarside** [comment]
Hang on, re-reading the instructions. Are you saying that Bambu themselves are inconsistent between Bambu Studio and Bambu Handy?

**Comment by ppptmstr** [comment]
Exactly! Here is a fresh screenshot of latest Bambu Studio and Handy for the same roll of white PLA, to demonstrate their own inconsistency:

![image](https://github.com/user-attachments/assets/67868070-865a-472d-afdb-0e36d6456eb9)

**Comment by AdrianGarside** [comment]
Well that's just annoying. I'll make an update to add back tag_uid then so both are available.

**Comment by AdrianGarside** [comment]
Added back. Not yet in a release.

**Comment by excalbian** [comment]
Came here because the update just pushed with the tray_uuid which broke my automations on tag_uuid (that I had tested by matching the value in Bambu Handy). Thank you for adding it back - will be waiting for the release.
