### ISSUE TITLE
[Feature] Expose current layer count/total layer count

### ISSUE THREAD

**Issue by CitizenRacer** [greghesp/ha-bambulab#53]
### Describe the feature

The MQTT messages expose layer count and total layer count. Any way we could get them added to this plugin? I'm using this script: https://github.com/camarokris/BambuOBSData/blob/master/BambuDataCollect.py to overlay MQTT data over the live stream. There's a lot more data that could be exposed. Layer count and total layer count would be really handy.

### What device is this for?

X1C

**Comment by CitizenRacer** [comment]
Thank you!!

**Comment by AdrianGarside** [comment]
Merged into main and is in 1.0.0 release.
