### ISSUE TITLE
[Bug] Camera feed should be from camera domain, not image domain

### ISSUE THREAD

**Issue by marcinbauer85** [greghesp/ha-bambulab#531]
### Describe the bug

The current camera feed is using the image entity type, rather than camera which makes it difficult to publish via Homekit integration and use in other situations.

### To Reproduce

1. Add your printer via the integration
2. Preview the camera feed (will be image.printer_camera)

### Expected Behaviour

The camera feed should be from the camera domain, not image

### What device are you using?

A1

### Diagnostic Output

```shell
Bambulab A1
```

**Comment by honzis1364** [comment]
Same issue is present on P1 printers, only X1 sends video codec.

**Comment by honzis1364** [comment]
Have you managed to find a workaround @marcinbauer85? I've came across some converters, but I did not have any luck to get it working.

**Comment by marcinbauer85** [comment]
@honzis1364 unfortunately not.

**Comment by xxgmxx** [comment]
Same here, it would make everything much easier to have it as cammera and not as image :/ I have tried a lot of ways to change it, but did not find any workaroud.

**Comment by rb2k** [comment]
I think the image domain also leads to a LOT of unnecessary database usage:

<img width="1292" alt="Screenshot 2024-08-06 at 9 21 02 AM" src="https://github.com/user-attachments/assets/594d4865-e6cd-4bf7-b91e-6662cfa341b5">



(created with the [dbstats](https://github.com/jehy/hass-addons/tree/master/dbstats) addon)

**Comment by GMarty93** [comment]
I have the same frustrations with this in my A1 I’d like to bridge the camera to HomeKit but I can’t as it’s an image sensor not a camera

**Comment by jawilson** [comment]
I've added PR #595 to fix this.

**Comment by AdrianGarside** [comment]
Resolving as completed with #595.
