### ISSUE TITLE
[Bug] "no unconfigured printed in your account" after reinstallation of the plugin

### ISSUE THREAD

**Issue by starschild86** [greghesp/ha-bambulab#536]
### Describe the bug

i was a happy user in the past, i uninstalled because in that period my printer was having lan problems and i had the idea this plugin was creating issues.

i have now installed again because i would really like the features, however i can't seem to be able to add my printer again

### To Reproduce

hacs,
install bambulab component
restart home assistant
go to integrations
select bambu cloud
insert account

see this (in italian, mi translation on the side)

Selezione della stampante [printer selection]
Scegli la stampante che desideri aggiungere. [choose a printer to add]

Nessuna stampante non configurata trovata nell'account. [no unconfigured printer in your account]

however, when i look everywhere for my printer, i can't find it in home assistant :(

### Expected Behaviour

i would like to be able to start fresh without this error

### What device are you using?

P1P

### Diagnostic Output

```shell
Selezione della stampante
Scegli la stampante che desideri aggiungere.

Nessuna stampante non configurata trovata nell'account.
```

**Comment by starschild86** [comment]
Hi sorry does anybody have a suggestion on a workaround on this?

**Comment by AdrianGarside** [comment]
How did you uninstall? Just deleted the integration entry?

**Comment by starschild86** [comment]
I'm afraid so 😔
I tried to delete the repository from hacs but didn't resolve

Il Sab 29 Giu 2024, 19:56 AdrianGarside ***@***.***> ha
scritto:

**Comment by AdrianGarside** [comment]
Can you turn on debug logs and provide a debug log for this? You'll probably need to do that in your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.bambu_lab: debug
```

**Comment by AdrianGarside** [comment]
No response. So closing the issue as inactionable.
