### ISSUE TITLE
[Feature] <Target Temperatures as "number" rather than "sensor">

### ISSUE THREAD

**Issue by Alphafox992** [greghesp/ha-bambulab#538]
### Describe the feature

Simple; Requesting that the "Target nozzle, and Bed" temperature "sensors" be configured as "number, or other" for ability to modify temperatures via integration

### What device is this for?

X1C

### Other Information

Love this; I suck with MQTT, thanks!

**Comment by AdrianGarside** [comment]
When I get to this, it will only work in Lan mode with the updated firmwares.

**Comment by KeimpeRauwerda** [comment]
+1 for this

I copied the layout that got recommended in the readme, and found out that they use number values instead of sensor values to modify the temperatures. So yeah, would be nice to have, definitely.

**Comment by AdrianGarside** [comment]
Thanks to @Skydev0h: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.35-dev5
