### ISSUE TITLE
[Feature] Allow disabling the P1 camera image polling

### ISSUE THREAD

**Issue by bradsjm** [greghesp/ha-bambulab#539]
### Describe the feature

The P1 series can only support two active camera streams. If this integration is enabled, it will use one of the two streams even if the image entity is disabled.

If another application is also pulling the image stream (in my case, for Octo Everywhere) then the slicer will not be able to show the stream and the only way to have both is to disable the integration completely.

Request: Allow disabling the image polling either through an option when configuring the integration or if the image entity is disabled.

### What device is this for?

P1S

**Comment by LukeAbell** [comment]
Would love to have this too!

**Comment by AdrianGarside** [comment]
Resolving as completed with #595.

**Comment by AdrianGarside** [comment]
I will need to check as I'm not sure I've ever noticed this limitation and I have 4 potential viewers - bambu studio, handy, my production HA instance and my test one.

**Comment by AdrianGarside** [comment]
I am able to view the P1* camera from 4 devices simultaneously - 2 independent home assistant instances (production and test), bambu handy and bambu studio.

**Comment by AdrianGarside** [comment]
Please confirm this is still an issue. I'm going to close the issue for now.
