### ISSUE TITLE
[Feature] Custom Filaments support

### ISSUE THREAD

**Issue by clstr** [greghesp/ha-bambulab#540]
### Describe the feature

Add custom filament support.

since the release of bambu allowing custom filaments profiles the filament rolls in the ams do not show up properly and list as unknown. I have not tried the external spool.

![image](https://github.com/greghesp/ha-bambulab/assets/1195526/24b450c9-c75b-44b5-a6cf-44aabbba785c)

### What device is this for?

X1C

**Comment by kurim** [comment]
Based on earlier response from [AdrianGarside](https://github.com/AdrianGarside) it is not possible.
See here: 
`Custom filaments are unique to you so this can't be added to the integration.`
https://github.com/greghesp/ha-bambulab/pull/513#discussion_r1577251989

**Comment by clstr** [comment]
> Based on earlier response from [AdrianGarside](https://github.com/AdrianGarside) it is not possible. See here: `Custom filaments are unique to you so this can't be added to the integration.` [#513 (comment)](https://github.com/greghesp/ha-bambulab/pull/513#discussion_r1577251989)
> 
> What should be a way for it is like haveing a custom "store" for it, like look up in a custom.json file explzit for you where you also past the names matching the unique ID. @AdrianGarside what do you think?

I see understood, I added my custom filament Id to my `const.py` file. I will prob have to do this again when the module is updated. If some solution is created ill just maintain my own list with a cron job.

**Comment by dottor3d** [comment]
I'm in const.py file but I don't understand the code exposed with a custom filament. 
Example: code "GFB00" is mapped, in const.py, as "Bambu ABS". How can I map a custom filament named "Amazon PLA Basic" that I created? I can't find a code related to my custom filament. How did you achived your result?
Maybe I missing something, but can you explain in a more detailed way?
Thank you in advance

**Comment by clstr** [comment]
> I'm in const.py file but I don't understand the code exposed with a custom filament. Example: code "GFB00" is mapped, in const.py, as "Bambu ABS". How can I map a custom filament named "Amazon PLA Basic" that I created? I can't find a code related to my custom filament. How did you achived your result? Maybe I'm missing something, but can you explain in a more detailed way? Thank you in advance

In your config file where your custom filaments are stored
Windows: `%appdata%/BambuStudio/user/[YourUserId]/filament/base` 

Open the `*.json` file that has your custom filament and find the key `filament_id`, then you can add that id to yout const.py with whatever name you want.

**Comment by dottor3d** [comment]
Well yes, I confirm that works now! Thank you very much.

![Screenshot 2024-06-14 171408](https://github.com/greghesp/ha-bambulab/assets/166419639/aec8cb09-197a-41eb-873e-b37beb7ec0cd)

**Comment by kurim** [comment]
Btw. it can be grapped from the api as well.
https://api.bambulab.com/v1/iot-service/api/slicer/setting?version=undefined + usertoken

In block:
```json
"private": [
{
                "setting_id": "xxxxx",
                "version": "1.9.0.14",
                "name": "OVERTURE TPU 95 @Bambu Lab P1S 0.4 nozzle",
                "update_time": "2024-06-23 05:23:53",
                "base_id": null,
                "filament_id": "xxxx",
                "filament_type": "TPU",
                "filament_is_support": "0",
                "nozzle_temperature": [
                    200,
                    250
                ],
                "nozzle_hrc": "3",
                "filament_vendor": "OVERTURE"
            }
]
```

**Comment by phil-the-dev** [comment]
Just throwing some support that if it was possible to set the filament via HAss, it would be suuuuch a game changer. (Could also see something similar for nozzle settings too!)

**Comment by AdrianGarside** [comment]
This should be working now.
