### ISSUE TITLE
[Bug] Temperatures drop to 0 shortly after a finished print

### ISSUE THREAD

**Issue by boehser-enkel** [greghesp/ha-bambulab#542]
### Describe the bug

Temperatures (bed & nozzle) drop to 0 shortly after a finished print.
This occured with 2024.6 i think
![grafik](https://github.com/greghesp/ha-bambulab/assets/59539881/827b30f7-a8f9-4109-945c-18cedcfc31c8)

[home-assistant_bambu_lab_2024-06-13T09-50-04.487Z.log](https://github.com/user-attachments/files/15817350/home-assistant_bambu_lab_2024-06-13T09-50-04.487Z.log)

### To Reproduce

Start a print
Let it finish

### Expected Behaviour

No drop

### What device are you using?

A1

### Diagnostic Output

```shell
In the description
```

**Comment by AdrianGarside** [comment]
The integration just reports the values the printer provides.
