### ISSUE TITLE
[Bug] Strange behaviours on AUX and COOLING PART fans control (A1 Mini)

### ISSUE THREAD

**Issue by informagico** [greghesp/ha-bambulab#543]
### Describe the bug

A1 Mini does not have (AFAIK) an AUX fan to begin with.

Also, something weird is happening when controlling the cooling part fan: value does not update quickly and most of the time the fan speed value drops to 0 just after showing the commanded value (see graph below), on the physical printer fan stays at the commanded value.

![339743570-8281818e-8867-4b94-a3ef-185e584aa05d](https://github.com/greghesp/ha-bambulab/assets/38808827/694c76a4-6c39-4f74-9123-6064358cb676)

Commanding the cooling part fan then makes the aux fan to show the same value but nothing happen when the command is given via the AUX fan entity (as expected, there is no aux fan)

![339741465-f97dd544-4336-482c-8da3-2cd31bfb9df8](https://github.com/greghesp/ha-bambulab/assets/38808827/6e01d86d-61c3-40a4-8987-1e7cfbf29e9f)

### To Reproduce

Just try to command AUX and COOLING PART fans

### Expected Behaviour

1. AUX fan should not present an entity
2. Commanding the COOLING PART fan should makes the corresponding sensor entity to update the value and not to drop to 0

### What device are you using?

A1 Mini

### Diagnostic Output

[config_entry-bambu_lab-7d47e89068a82f40518dffe9d7dc67a8.json](https://github.com/user-attachments/files/15839618/config_entry-bambu_lab-7d47e89068a82f40518dffe9d7dc67a8.json)

```shell
```

**Comment by AdrianGarside** [comment]
Incorrect presence of the aux fan will be fixed in the next release (2.0.27) with #653

**Comment by AdrianGarside** [comment]
Since the cooling fan issue is separate and seems to be external per the comments I'm going to resolve this issue as completed.
