### ISSUE TITLE
[Bug] Binary sensor online toggles when printing in progress 

### ISSUE THREAD

**Issue by FWeinb** [greghesp/ha-bambulab#546]
### Describe the bug

Today the `binary_sensor.<printername>_online` started to behave erratically with toggling between "Running"/"Not Running" multiple times. 

### To Reproduce

1. Go to History for `binary_sensor.<printername>_online`
See: 
<img width="1356" alt="image" src="https://github.com/greghesp/ha-bambulab/assets/1250430/32dc78c7-dc63-4979-beb0-c799f99010e3">

### Expected Behaviour

Binary sensor will stay online as long as the printer is turned on. 

### What device are you using?

P1S

### Diagnostic Output

```shell
I got an javascript exception when trying to download the diagnostics:
ha-config-integration-page.ts:1323 Uncaught (in promise) {code: 'invalid_format', message: "expected str for dictionary value @ data['path']. Got None"}
```

### Other Information

Printer is in "LAN Mode"

**Comment by AdrianGarside** [comment]
The online sensor toggles to off if the mqtt connection to the printer drops or if it doesn't get data for 20 minutes. Your drops are much shorter than that. So the connection to the printer is dropping and reconnecting. Are you cloud or local connected to it?

**Comment by FWeinb** [comment]
I am using the printer in "LAN mode", the last few days it I could not reproduce this issue again. Might be a bad WiFi Signal?

**Comment by FWeinb** [comment]
After some more investigations it looks like this was related to an old instance open that constantly tried to reconnect with a wrong access code. Did not have this issue in the last few days.
