### ISSUE TITLE
[Feature] AMS Sensors 

### ISSUE THREAD

**Issue by HennieLP** [greghesp/ha-bambulab#55]
### Describe the feature

AMS Sensors wud be cool Like What filament is it holding and The Temperature and Humidity of the AMS 

### What device is this for?

AMS

**Comment by CitizenRacer** [comment]
This would be so useful to take action on humidity readings from the AMS.

**Comment by AdrianGarside** [comment]
Getting there:
![image](https://user-images.githubusercontent.com/26147576/231944106-0af754e5-8886-4573-a11d-72a5746d1a42.png)

**Comment by npike** [comment]
Very nice, thank you!

**Comment by AdrianGarside** [comment]
New release has this.
