### ISSUE TITLE
[Feature] Allow config of C temperature units even when HA is configured with Fahrenheit

### ISSUE THREAD

**Issue by sprior** [greghesp/ha-bambulab#551]
### Describe the feature

I hope I'm not the only one in this, but I live in the US where for temperatures like the weather we use Fahrenheit, but for 3D printers everything is in C.  I assume this plugin is showing bed and hot end temps because that's the temperature unit I've send for HA as a whole, but could we have the option to override to use C for 3D printing?

### What device is this for?

X1C

**Comment by WolfwithSword** [comment]
You should be able to click on any temperature entity in HA and set it to use C or F as the unit individually / outside of the global HA setting.

Click on any temperature sensor, go to the settings and you can click on the Unit of Measurement, and it will auto convert.

**Comment by sprior** [comment]
Ok, found the setting, thanks.
