### ISSUE TITLE
[Feature] Keep the value in entities when Printer is off

### ISSUE THREAD

**Issue by poudenes** [greghesp/ha-bambulab#552]
### Describe the feature

Would be nice to have the last values still loaded in the sensors and other entities. When printer is off everything become "Unavailable"

I use also watchman integration. It check if entities are gone. When my printer goes offline I got a list of all the entities of my printer that are gone... :)

### What device is this for?

A1

**Comment by AdrianGarside** [comment]
Which ones do you want to remain available? Most of the sensors remain with their last values. No sensors are forced to unavailable when the printer is off.

**Comment by AdrianGarside** [comment]
No response.

**Comment by poudenes** [comment]
Wow.... I don't know what happen. But didn't see your question.. Please reopen it and when I'm at home I will respond on this. I'm so sorry!

**Comment by poudenes** [comment]
Those for example:
sensor.bambulab_a1_mini_ams_lite_tray_1
sensor.bambulab_a1_mini_ams_lite_tray_2
sensor.bambulab_a1_mini_ams_lite_tray_3
sensor.bambulab_a1_mini_ams_lite_tray_4

But basically all sensors and camera.
When the printer is off it would be nice to still see the last used data for the printing process instead of Unavailable values

**Comment by AdrianGarside** [comment]
I don't repro this:
![image](https://github.com/user-attachments/assets/a47b18d4-8ec1-404b-b5e3-679f390ecb20)

Can you include debug logs of the printer going offline and being detected as offline by the integration?

**Comment by poudenes** [comment]
Those are Unavailable when printer is off and I did a HA restart. Would be great to have the old values still in HA even when the printer is off. 

<img width="1328" alt="Screenshot 2024-10-24 at 16 15 44" src="https://github.com/user-attachments/assets/8a023bb8-af75-43e6-8e47-f70288fe3ee3">

**Comment by AdrianGarside** [comment]
Restarting home assistant with the printer off will lose all printer state. That's by design - the integration does not persist any printer state. The only persisted data is that the devices exist and necessary authentication information.
