### ISSUE TITLE
Printer Name not being used by integration

### ISSUE THREAD

**Issue by Kingsidorak** [greghesp/ha-bambulab#558]
### Describe the bug

Whatever displays Printer Name isn't updating the printer's name if it changes

### To Reproduce

Add your printer to HA with this, and then change it's name via Bambu Studio or other options

### Expected Behaviour

Printer name should update

### What device are you using?

P1S

### Diagnostic Output

```shell
none
```

**Comment by AdrianGarside** [comment]
Does it fix up if you restart the integration?

**Comment by AdrianGarside** [comment]
I don't currently use the deviceName in the MQTT payload at all - the name you get is just the model name and you can rename it in Home Assistant.

**Comment by Kingsidorak** [comment]
I think you're thinking of something else. This is directly taking Printer Name information from the printer, which I can change in Bambu/Orca Studio 
![image](https://github.com/user-attachments/assets/89bb759c-a525-4a58-88ca-efa6fbe99a39)

**Comment by Kingsidorak** [comment]
The problem this post is about being that this information is not changing when I change it in the software, which updates everywhere else other than in HASS until I remove the printer, and add it back

**Comment by AdrianGarside** [comment]
Ah yes, if you configure via Bambu Cloud I get the printer name from that API and set it to the HA device. But that's a one-time deal. To make it react to changes in the printer name and to make it work for Lan-only connections I need to grab the deviceName from the MQTT payload and then also update the HA device with that name. Luckily I put the name into the options dictionary that allows for it to change.

**Comment by AdrianGarside** [comment]
The device name is purely a cloud concept so while I can grab it from the device list REST API (as I do during initial integration setup via the cloud assisted path), there's no event for changing it so I'd have to regularly query that API and detect the device name changing. Given the cloudflare problems recently and Bambu's stated concern about excessive calls from 3rd party software, I don't think it's worth the risk of adding that given it's not a lot of effort to just update the name in HA to match if you change the name in bambu cloud.
