### ISSUE TITLE
[Bug] Printer Name missing for A1 mini

### ISSUE THREAD

**Issue by mateuszdrab** [greghesp/ha-bambulab#574]
### Describe the bug

The Printer Name sensor is missing for A1 mini

### To Reproduce

Add A1 mini printer

### Expected Behaviour

Sensor would work, just like it does for my X1C

### What device are you using?

A1 Mini

### Diagnostic Output

```shell
TBC
```

**Comment by rugbyopera** [comment]
That entity works for me with my A1 Mini.

**Comment by mateuszdrab** [comment]
Unfortunately it's not working for me still, I even tried adding the printer from scratch on my test HA instance, all latest versions so 2024.9.1 for the core and 2.0.22 for the extension. On this instance, both printers are missing the printer name entity.

**Comment by AdrianGarside** [comment]
Inactionable without any diagnostic data and/or debug logs.

**Comment by AdrianGarside** [comment]
It will be present if it's saved to the config_entry for the integration. Maybe try deleting and re-adding the printers.
