### ISSUE TITLE
Camera feed not working X1C

### ISSUE THREAD

**Issue by doronazl** [greghesp/ha-bambulab#576]
### Describe the bug

i see the camera entity under my device, it always shows as "recording" state, but cant see the feed.

### To Reproduce

by clicking the camera entity

### Expected Behaviour

to show it

### What device are you using?

X1C

### Diagnostic Output

```shell
![Screenshot at Aug 16 09-00-38](https://github.com/user-attachments/assets/56bd382d-4986-4a9c-9a7d-0361886bee72)
```

**Comment by SHadley1138** [comment]
I get the same too....   I had the camera working fine on day one, but after a week, HA seems to have dropped it....    it's working fine in the Bambu app, but not via HA. weird
<img width="331" alt="image" src="https://github.com/user-attachments/assets/58fafc31-1232-4eb2-bdff-72db3cbc530f">

**Comment by AdrianGarside** [comment]
Try rebooting your printer. The X1 RTSP camera implementation is buggy and stops working. See the discussions tab for ways you can mitigate this and keep it working more than it will otherwise.

**Comment by AdrianGarside** [comment]
See #221
