### ISSUE TITLE
[Bug] Set temp entities missing

### ISSUE THREAD

**Issue by TaylorN15** [greghesp/ha-bambulab#577]
### Describe the bug

I have just setup this plugin and created the dashboards. One of the dashboards references some entities like `number.<printer_name>_set_nozzle_temp` and `number.<printer_name>_set_bed_temp` that don't seem to exist. I couldn't find anything in the documentation about support (or lack of) for this feature for the P1S.

### To Reproduce

1. Create a fan temps/control dashboard
2. Import the YAML into HA dashboard

### Expected Behaviour

Ability to set bed/nozzle temp

### What device are you using?

P1S

### Diagnostic Output

```shell
https://github.com/user-attachments/files/16642560/config_entry-bambu_lab-01J57V5DEKQ1E1WRP13CPNCE90.json
```

**Comment by WolfwithSword** [comment]
The dashboard templates use those in conditionals to only display if they are found, as it helps me minimize the differences between the HACs integration and my nodered integration for compatibility.

Currently this integration does not have bed or nozzle temp setting, but it has been requested. If/When it's added, I will update the dashboard templates to whatever naming scheme is chosen here.

See https://github.com/greghesp/ha-bambulab/issues/491 

Do note, that for P1 series currently it will only work if the printer is in lan mode, or if the integration is setup to connect over cloud with a cloud mode printer and not use lan connection.
