### ISSUE TITLE
[Bug] Refresh button brings up an error

### ISSUE THREAD

**Issue by Darthmonkey** [greghesp/ha-bambulab#587]
### Describe the bug

When clicking the refresh button (..._force_refresh_data), it appears to work, but I get a bug:
_"Failed to perform the action button/press. Caught blocking call to putrequest with args (<urllib3.connection.HTTPSConnection object at 0x7f56f42780>, 'GET', '/v1/iot-service/api/slicer/setting?version=undefined') inside the event loop by custom integration 'bambu_lab' at custom_components/bambu_lab/pybambu/bambu_cloud.py, line 189: response = requests.get(url, headers=headers, timeout=10). (offender: /usr/local/lib/python3.12/site-packages/urllib3/connection.py, line 219: return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)), please create a bug report at https://github.com/greghesp/ha-bambulab/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#putrequest"_

### To Reproduce

1. Go to Settings | Devices | Bambu Lab | Devices | <P1x Printer>
2. Press the 'Diagnostic - **Force Refresh Data**' button.
3. Error message pops up bottom left of the screen showing the bug message.

### Expected Behaviour

No bug message, refreshes all the data for the device.

### What device are you using?

P1S

### Diagnostic Output

```shell
No diagnostic data.
```

### Other Information

Also happens for my P1P, and removing and re-adding a device doesn't seem to help.

**Comment by nzrutman** [comment]
Same issue, A1 Mini.
May or may not be related, device is reported as "UNKNOWN", although all sensors except camera are discovered/working.
![Screenshot 2024-09-09 at 3 01 12 PM](https://github.com/user-attachments/assets/7f7df0e1-7f32-41be-a79b-4ee55472b906)

**Comment by SHadley1138** [comment]
I get the same on my x1c

Failed to perform the action button/press. Caught blocking call to putrequest with args (<urllib3.connection.HTTPSConnection object at 0x7f2b251b20>, 'GET', '/v1/iot-service/api/slicer/setting?version=undefined') inside the event loop by custom integration 'bambu_lab' at custom_components/bambu_lab/pybambu/bambu_cloud.py, line 189: response = requests.get(url, headers=headers, timeout=10). (offender: /usr/local/lib/python3.12/site-packages/urllib3/connection.py, line 219: return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)), please create a bug report at https://github.com/greghesp/ha-bambulab/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#putrequest

**Comment by zuhra031** [comment]
same thing here

P1S latest fw
HA Core 2024.9.1
HA Supervisor 2024.09.1
HA Frontend 20240906.0

HACS Bambu Lab integration v2.0.22

`Failed to perform the action button/press. Caught blocking call to putrequest with args (<urllib3.connection.HTTPSConnection object at 0xd48c3828>, 'GET', '/v1/iot-service/api/slicer/setting?version=undefined') inside the event loop by custom integration 'bambu_lab' at custom_components/bambu_lab/pybambu/bambu_cloud.py, line 189: response = requests.get(url, headers=headers, timeout=10). (offender: /usr/local/lib/python3.12/site-packages/urllib3/connection.py, line 219: return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)), please create a bug report at https://github.com/greghesp/ha-bambulab/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#putrequest`

**Comment by Telecino** [comment]
Just installed HACS Bambu Lab integration v2.0.22 and got the same error:

X1C latest fw 01.08.02.00
HA Core 2024.9.3
HA Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1

Failed to perform the action button/press. Caught blocking call to putrequest with args (<urllib3.connection.HTTPSConnection object at 0x7f09731d30e0>, 'GET', '/v1/iot-service/api/slicer/setting?version=undefined') inside the event loop by custom integration 'bambu_lab' at custom_components/bambu_lab/pybambu/bambu_cloud.py, line 189: response = requests.get(url, headers=headers, timeout=10). (offender: /usr/local/lib/python3.12/site-packages/urllib3/connection.py, line 219: return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)), please create a bug report at https://github.com/greghesp/ha-bambulab/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#putrequest

**Comment by eolder** [comment]
Got the same error with my P1S running the latest firmware, though I only tested this after the integration stopped working at all (printer just shows as 'offline')

**Comment by Amarrant** [comment]
Same here on local x1c
`Failed to perform the action button/press. Caught blocking call to putrequest with args (<urllib3.connection.HTTPSConnection object at 0x7fc4903034d0>, 'GET', '/v1/iot-service/api/slicer/setting?version=undefined') inside the event loop by custom integration 'bambu_lab' at custom_components/bambu_lab/pybambu/bambu_cloud.py, line 189: response = requests.get(url, headers=headers, timeout=10). (offender: /usr/local/lib/python3.12/site-packages/urllib3/connection.py, line 219: return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)), please create a bug report at https://github.com/greghesp/ha-bambulab/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#putrequest`

**Comment by Darthmonkey** [comment]
Since the latest update v2.0.24, this problem no longer occurs, it updates successfully.
