### ISSUE TITLE
[Bug] only shows 1 AMS system for P1S

### ISSUE THREAD

**Issue by mharris1984** [greghesp/ha-bambulab#590]
### Describe the bug

I have 2 AMS systems with the AMS hub and the plugin here only shows one AMS system with 4 spool types/color info. So the other 4 it doesn't show, Bambu labs studio and items all show it, so I assume it's just an extended attribute to get multiple AMS info. 

I am planning on getting 2 more AMS systems to have a full 4 AMS with 16 colors/spools. Would be nice for HA to show all my items for print status and setup alerting around amounts and such 

### To Reproduce

Plugin just shows 4 rolls from a single ams. 

### Expected Behaviour

All ams spools to show up 

### What device are you using?

P1S

### Diagnostic Output

```shell
N/A
```

**Comment by AdrianGarside** [comment]
This used to work (since I used to have 2 connected to one printer) so something regressed. Is there anything in the log output that sheds light on why it's failing? Please provide a diagnostic log as that will show what the integration discovered.

**Comment by AdrianGarside** [comment]
I need debug logs to have any chance of diagnosing this.
