### ISSUE TITLE
[Feature] Restream outside of Home Assistant

### ISSUE THREAD

**Issue by WayneManion** [greghesp/ha-bambulab#591]
### Describe the feature

I have a P1P with the P1S conversion kit. I run Frigate on a separate physical machine to monitor some cameras and record streams. I have this Home Assistant integration working.

The integration provides an image entity that works as reliably as can be expected from a camera connected over wi-fi. I would like to be able to capture this stream with my Frigate setup. 

Is there already some way I can access the nice, stable camera feed provided by this integration to some outside service?

### What device is this for?

P1P

**Comment by pravardhanreddy** [comment]
+1 for this. Exactly what i need as well. Or at least some way to disable the camera streaming for this integration so that we can use another tool like this https://github.com/synman/bambu-go2rtc
to integrate the stream into frigate.

**Comment by AdrianGarside** [comment]
Resolving as completed with #595. If there is a way to take a camera entity in home assistant and restream it to Frigate, then you should now be able to so. There is no plan to added an external restream from this integration itself.
