### ISSUE TITLE
[Feature] Get Head coordinates

### ISSUE THREAD

**Issue by MattiaConfalonieri** [greghesp/ha-bambulab#597]
### Describe the feature

It's possibile get the head coordinates when printing?

### What device is this for?

X1

**Comment by WolfwithSword** [comment]
The mqtt data does not provide current coordinates of the toolhead unfortunately. Though if it did, it would be updating *very* frequently for HA to handle.

**Comment by AdrianGarside** [comment]
Yes, there is zero chance it will ever be added to the mqtt with enough fidelity to be interesting.
