### ISSUE TITLE
[Feature] Expose a service/action to send direct commands

### ISSUE THREAD

**Issue by AurelioB** [greghesp/ha-bambulab#599]
### Describe the feature

Sending custom MQTT commands could enable advanced automations:
- **Running custom gcode commands**: Move toolhead to a specific position, preheat printer based on currently loaded filament
- Control filament settings programatically: I'm interested on changing filament settings programatically, but there could be other use cases. My use case involves choosing a filament from Spoolman's API and assigning the params to a specific AMS slot (min temp, max temp, material, color)

### What device is this for?

X1C

### Other Information

Reference filament settings command:

```js
{
    "print": {
        "sequence_id": "0",
        "command": "ams_filament_setting",
        "ams_id": 0, // Index of the AMS
        "tray_id": 0, // Index of the tray
        "tray_info_idx": "", // Probably the setting ID of the filament profile
        "tray_color": "00112233", // Formatted as hex RRGGBBAA (alpha is always FF)
        "nozzle_temp_min": 0, // Minimum nozzle temp for filament (in C)
        "nozzle_temp_max": 0, // Maximum nozzle temp for filament (in C)
        "tray_type": "PLA" // Type of filament, such as "PLA" or "ABS"
    }
}
```

**Comment by AdrianGarside** [comment]
Added by @gpambrozio
