### ISSUE TITLE
Integration fails every time the printer is power cycled

### ISSUE THREAD

**Issue by ezfrag2021** [greghesp/ha-bambulab#60]
### Describe the bug

Integration is setup as normal and all sensors are visible and everything works as expected. Printer is switched off and back on and device becomes unavailable in HA and integration says “failed to set up”.

### To Reproduce

1.Set up the integration in HA and verify all working as expected 
2. Turn off the printer at the socket (unplug)
3. Plug in power cable and turn on the printer 
4. Check availability of HA integration 

### Expected Behaviour

I expect the HA integration to persist when the printer is power cycled 

### What device are you using?

X1C

### Firmware Version

01.04.00.00

### Home Assistant Version

2023.3.6

### Component Version

Latest

### Log Extracts

log shows the following error (serial number redacted for security):

Error setting up entry **redacted** for bambu_lab
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bambu_lab/__init__.py", line 19, in async_setup_entry
    coordinator = BambuDataUpdateCoordinator(hass, entry=entry)
  File "/config/custom_components/bambu_lab/coordinator.py", line 31, in __init__
    entry.data["device_type"])
KeyError: 'device_type'

**Comment by AdrianGarside** [comment]
@ezfrag2021 the KeyError you're hitting there indicates that you will need to delete and re-add the integration as there was a breaking change to what we store about the printer.

With the latest bits that led to that breaking change, the integration should gracefully handle the printer being turned off - both at home assistant startup and while home assistant is already running. AFAIK it's now working very reliably.

**Comment by ezfrag2021** [comment]
@AdrianGarside thanks for the info. I have deleted the integration, updated in HACS and set-up again. All is back up but will test over the next couple of days to check the integration is sticking.

**Comment by AdrianGarside** [comment]
@ezfrag2021 I'm going to mark this closed. Please let me know if you can still repro this.
