### ISSUE TITLE
[Bug] Report as requested

### ISSUE THREAD

**Issue by miketarg** [greghesp/ha-bambulab#601]
### Describe the bug

Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan (documentation, issues)
First occurred: 12:34:19 PM (6 occurrences)
Last logged: 12:34:19 PM

Entity None (<class 'custom_components.bambu_lab.fan.BambuLabFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/greghesp/ha-bambulab/issues
Entity None (<class 'custom_components.bambu_lab.fan.BambuLabFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/greghesp/ha-bambulab/issues

### To Reproduce

Use the plugin

### Expected Behaviour

not to see a warning

### What device are you using?

x1c

### Diagnostic Output

```shell
n/a
```

**Comment by AdrianGarside** [comment]
This was fixed and will be in the latest dev build.
