### ISSUE TITLE
Warnings in log

### ISSUE THREAD

**Issue by miketarg** [greghesp/ha-bambulab#604]
### Describe the bug

This error originated from a custom integration.

Logger: custom_components.bambu_lab.pybambu
Source: custom_components/bambu_lab/pybambu/bambu_client.py:401
integration: Bambu Lab (documentation, issues)
First occurred: 10:41:34 PM (1 occurrences)
Last logged: 10:41:34 PM

_on_disconnect

### To Reproduce

use it and finish a print

### Expected Behaviour

not this 

### What device are you using?

X1C

### Diagnostic Output

```shell
This error originated from a custom integration.

Logger: custom_components.bambu_lab.pybambu
Source: custom_components/bambu_lab/pybambu/bambu_client.py:401
integration: Bambu Lab (documentation, issues)
First occurred: 10:41:34 PM (1 occurrences)
Last logged: 10:41:34 PM

_on_disconnect
```

**Comment by AdrianGarside** [comment]
This warning is appropriate. The integration lost connection to your printer, which is not expected.
