### ISSUE TITLE
paused_filament_runout, etc doesnt update on runout / errors  (sensor.bambu_lab_x1c_current_stage)

### ISSUE THREAD

**Issue by miketarg** [greghesp/ha-bambulab#608]
### Describe the bug

choose:
  - conditions:
      - condition: template
        value_template: >-
          {{ states('sensor.bambu_lab_x1c_current_stage') ==
          'paused_nozzle_clog' }}
    sequence:
      - data:
          entity_id: media_player.jen_is_sleeping
          message: |
            {% set messages = [
              "The printer has paused due to a nozzle clog. Please clear the nozzle to resume.",
              "Nozzle clog detected. Please check and clear the nozzle to continue printing.",
              "Printing is paused because of a nozzle clog. Kindly fix it to proceed.",
              "Attention: Nozzle clog! Please clear it to continue printing.",
              "The printer has stopped due to a nozzle clog. Please address it to resume printing.",
              "Nozzle clog alert: Please clear the clog to get back to printing.",
              "The printer has paused due to a nozzle issue. Clear it to proceed.",
              "Nozzle clog detected. Please fix it to resume printing.",
              "The printer halted because of a nozzle clog. Please take action to continue.",
              "Attention: Nozzle clog. Resolve this issue to resume printing."
            ] %} {{ messages | random }}
        action: tts.cloud_say
  - conditions:
      - condition: template
        value_template: >-
          {{ states('sensor.bambu_lab_x1c_current_stage') ==
          'paused_filament_runout' }}
    sequence:
      - data:
          entity_id: media_player.jen_is_sleeping
          message: |
            {% set messages = [
              "The printer has stopped because it ran out of filament. Please reload the filament.",
              "Filament runout detected. Reload the filament to continue printing.",
              "Printing paused due to filament runout. Please add more filament.",
              "Attention: Filament runout! Please reload to resume printing.",
              "The printer has paused because of filament runout. Reload it to continue.",
              "Filament runout alert: Please reload the filament to proceed.",
              "The printer halted due to filament runout. Reload it to continue printing.",
              "Filament runout detected. Reload it to resume your print job.",
              "The printer has stopped due to a lack of filament. Please reload it to continue.",
              "Attention: The printer is out of filament. Add more to resume printing."
            ] %} {{ messages | random }}
        action: tts.cloud_say
  - conditions:
      - condition: template
        value_template: "{{ states('sensor.bambu_lab_x1c_current_stage') == 'unknown' }}"
    sequence:
      - data:
          entity_id: media_player.jen_is_sleeping
          message: |
            {% set messages = [
              "The printer is in an unknown state. Please check for more details.",
              "Unknown state detected. Inspect the printer for more information.",
              "The printer’s current state is unclear. Please check the printer.",
              "Attention: The printer is in an unknown state. Please inspect it.",
              "Unknown state alert: Please check the printer for details.",
              "The printer has entered an unknown state. Review it for more information.",
              "The printer's state is unknown. Please inspect it for more details.",
              "Alert: The printer is in an unknown state. Check it for more information.",
              "The printer is in an unknown state. Please inspect it for further information.",
              "Unknown status detected. Please examine the printer for more details."
            ] %} {{ messages | random }}
        action: tts.cloud_say
  - conditions:
      - condition: template
        value_template: >-
          {{ states('sensor.bambu_lab_x1c_current_stage') ==
          'event_print_finished' }}
    sequence:
      - data:
          entity_id: media_player.jen_is_sleeping
          message: |
            {% set messages = [
              "The printer has just finished a print job!",
              "Print job completed successfully.",
              "The printer has finished printing.",
              "Your print job is done.",
              "The printer has completed the print.",
              "Printing finished successfully.",
              "The print job is complete.",
              "The printer has finished its task.",
              "Your print is ready.",
              "The printer has completed the print job.",
              "The print job is done. You can check it now.",
              "The printer has wrapped up the print job.",
              "Your print is finished. Check it out!",
              "The printer has completed its work.",
              "The print job is finished. You can inspect it now.",
              "The printer has completed the job. Your print is ready."
            ] %} {{ messages | random }}
        action: tts.cloud_say

this template used to work but now doesnt as the above never occurs when it should 

### To Reproduce

Use it

### Expected Behaviour

The previos behavoir of the state correclty reflecting what is happening

### What device are you using?

A1

### Diagnostic Output

```shell
n/A
```

**Comment by AdrianGarside** [comment]
Did you update the firmware? I think the other printers haven't been setting these stages (despite being defined) for a long time now.

**Comment by AdrianGarside** [comment]
Please provide debug logs or a diagnostic dump from the integraiton showing that current_stage is set to one of these values that no longer work for you. The integration shows what the printer tells it.
