### ISSUE TITLE
[Bug] httpx dependency not reliably being installed - breaks integration

### ISSUE THREAD

**Issue by AdrianGarside** [greghesp/ha-bambulab#615]
### Describe the bug

2024-10-21 22:54:39.076 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package httpx==0.27.2: ERROR: Cannot install httpx==0.27.2 because these package versions
have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

This worked on my test HA instance but is failing on my production one. It isn't clear what the version is conflicting with given it only list the bambu lab version requirement.

### To Reproduce

.

### Expected Behaviour

.

### What device are you using?

P1

### Diagnostic Output

```shell
.
```

**Comment by klausiklau** [comment]
same here. Die load the Dev version but HA is raising this issue. could not find the dependencies until now

**Comment by vordenken** [comment]
Same:

```
Unable to install package httpx==0.27.2: ERROR: Cannot install httpx==0.27.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by nagi603** [comment]
yeah, my older 2024.6.4 HA is needing 0.27.0 so perhaps not pinning specific version may be better? I have not experimented with it yet.

**Comment by TheDuffman85** [comment]
I know what is going on. @nagi603 is on the right track. HA it self comes with httpx as an requirement and was only bumped to 0.27.2 with HA 2024.10. I think we should change the requirement in the manifest to httpx>=0.27.0 so we at least also support HA 2024.09.

**Comment by AdrianGarside** [comment]
For other reasons 2024.8.1 is the min version and the dependency resolves with that version without changing the required version.

**Comment by TheDuffman85** [comment]
I agree that's not ideal. Sorry for the inconvenience. Would you like me to do a PR with the requirement changed to httpx>=0.27.0?

**Comment by klausiklau** [comment]
> I agree that's not ideal. Sorry for the inconvenience. Would you like me to do a PR with the requirement changed to httpx>=0.27.0?

thanks @TheDuffman85: this is working now!
