### ISSUE TITLE
[Bug] Firmware/Hardware versions never populate if printer was off when home assistant started when in cloud mqtt mode

### ISSUE THREAD

**Issue by AdrianGarside** [greghesp/ha-bambulab#63]
### Describe the bug

We send the get version and push all commands up front, regardless of whether the printer is on. If it's not then when it does get turned on, it will send its own unsolicited push all but doesn't send the version info unsolicited.

### To Reproduce

1. Turn printer off
2. Restart home assistant
3. Turn printer on
4. Initial state populates, but firmware/hardware versions never do.

### Expected Behaviour

Firmware/hardware should populate correctly.

### What device are you using?

P1P

### Home Assistant Version

Recent

### Component Version

Latest

**Comment by AdrianGarside** [comment]
May be a cloud only thing - you can connect to the cloud mqtt server even when the printer is offline.

**Comment by mydevpeeps** [comment]
where do you find the firmware version in the sensors?

**Comment by mydevpeeps** [comment]
I see the firmware version when restarting HA while powered off on both my X1C printers.  I am not in some special mode (whatever that means) on the printer.

**Comment by AdrianGarside** [comment]
Cloud mqtt support is currently not enabled and no immediate plans to re-enable since lan mode connection now works even with the printer is in cloud mode.
