### ISSUE TITLE
[Bug] Again login issue 2.0.24

### ISSUE THREAD

**Issue by andybali** [greghesp/ha-bambulab#631]
### Describe the bug

Regardless of the current problem, the integration worked for me with v2.0.24. I have installed a new 2nd AMS, something got mixed up and the AMS was recognized twice. I have deleted the integration in order to reconnect it so that the devices are read in again. 
Now I can no longer log in when I set up the integration again

```
Logger: custom_components.bambu_lab
Quelle: custom_components/bambu_lab/config_flow.py:124
Integration: Bambu Lab (Dokumentation, Probleme)
Erstmals aufgetreten: 14:26:16 (9 Vorkommnisse)
Zuletzt protokolliert: 14:42:42

Failed to connect with error code (403,)
```

### To Reproduce

?

### Expected Behaviour

?

### What device are you using?

X1C

### Diagnostic Output

```shell
na
```

### Log Extracts

```shell
Logger: custom_components.bambu_lab
Quelle: custom_components/bambu_lab/config_flow.py:124
Integration: Bambu Lab (Dokumentation, Probleme)
Erstmals aufgetreten: 14:26:16 (9 Vorkommnisse)
Zuletzt protokolliert: 14:42:42

Failed to connect with error code (403,)
```

**Comment by juanfranciscolopez28** [comment]
same here

**Comment by Jeffrey-JK** [comment]
The connection to my printer stopped working so I deleted it and tried to readd it and I am unable to login here as well.

**Comment by moscal65** [comment]
Same 403 received for me as well.

```
2024-10-25 16:35:23.915 DEBUG (SyncWorker_52) [custom_components.bambu_lab.pybambu] Getting accessToken from Bambu Cloud
2024-10-25 16:35:24.054 DEBUG (SyncWorker_52) [custom_components.bambu_lab.pybambu] Received error: 403
2024-10-25 16:35:24.055 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code (403,)
```

**Comment by kki03** [comment]
First time BambuLab user, just wanted to add my band new P1S to HA and I´m also not able to login.

```
Logger: custom_components.bambu_lab
Quelle: custom_components/bambu_lab/config_flow.py:124
Integration: bambu_lab ([Dokumentation](https://github.com/greghesp/ha-bambulab), [Probleme](https://github.com/greghesp/ha-bambulab/issues))
Erstmals aufgetreten: 22:33:09 (9 Vorkommnisse)
Zuletzt protokolliert: 22:59:48
Failed to connect with error code (403,)
```

**Comment by MistressPlague** [comment]
Seems to still occur on 2.0.25 (dev1) on trying to add device aka entry of my new printer.

**Comment by pleeja** [comment]
Same problem here.
UI shows: Failed to connect. Check credentials.

Bambulab probably updated something that broke this

**Comment by AdrianGarside** [comment]
Please try this release which has an additional cloudflare fix (adding the user agent header in a missed place in first round of fixeS): https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.25-dev2

**Comment by andybali** [comment]
works 👍 Thx

**Comment by kki03** [comment]
Works for me as well, thanks!
