### ISSUE TITLE
[Bug] A1 Camera not available

### ISSUE THREAD

**Issue by brauwers1981** [greghesp/ha-bambulab#659]
### Describe the bug

I have a HA intergration with my A1 mini and now also with my new A1.

But for the A1 mini I can see the camera feed but at the 'Sensor list' for the A1 I can't see the camera.

### To Reproduce

1. open device info A1
2. look at the sensor list
3. can't find the camera

Picture of the sensor list for the A1 mini:
![Home Assistant - A1 mini](https://github.com/user-attachments/assets/67d6ea62-94b9-4860-87c7-1f5778d540a9)

Picture of the sensor list of the A1:
![Home Assistant - A1 no camera](https://github.com/user-attachments/assets/64a78ff1-3d3d-4263-9332-eae115a8812e)

### Expected Behaviour

I see a camera sensor for the A1

### What device are you using?

A1

### Diagnostic Output

```shell
Doesn't have it
```

**Comment by AdrianGarside** [comment]
Without debug logs this is inactionable.

**Comment by brauwers1981** [comment]
Sorry, wasn't able to add the files yesterday. So I created a new Bug with the files. If you need more info, I can add them for you.
