### ISSUE TITLE
Firefox: Cameras freezing and causing web browser to freeze

### ISSUE THREAD

**Issue by Kingsidorak** [greghesp/ha-bambulab#660]
### Describe the bug

Using the latest version available at this time.
I run a print farm, and currently have 8 printers going. Since the recent change to the way the cameras are integrated my cameras often freeze, and are also causing Firefox to stop responding for about a minute

It may be a good idea to include the other camera method as option until this is smoothed out... I am assuming that isn't an option with the latest release since the cameras outright stopped working after the update

### To Reproduce

Unknown. Could be related to how many Bambu printer cameras you have set up

### Expected Behaviour

.

### What device are you using?

P1S

### Diagnostic Output

```shell
.
```

**Comment by AdrianGarside** [comment]
What OS / web browser is that happening in?

**Comment by Kingsidorak** [comment]
Firefox on Windows 10. Everything should be as up to date as possible

**Comment by penguinpatrol** [comment]
might be somewhat related but since the cameras update mine also just refuse to load?

**Comment by Kingsidorak** [comment]
So right now I have 7 printers up. Just rebooted HASS. 6 Cameras are working, the 7th is black until I click Edit then it shows up.

Typically whenever the cameras stop working it seems to be either mid printing, is idle for a while, or when the camera refreshes for some reason after the print is done.

**Comment by AdrianGarside** [comment]
And to double check - all 7 are P1S printers? How are you showing the camera in your dashboard? I.e. What cards are you using?

**Comment by Kingsidorak** [comment]
heres the yaml from one, this one is a P1P. I have 3 P1Ps and 5 P1Ss

type: vertical-stack
cards:
  - show_state: true
    show_name: true
    camera_view: live
    type: picture-entity
    entity: camera.p1_00_camera
    name: P1 00 Metallics

**Comment by tool666schism** [comment]
My camera has been having constant stuttering and freezing issues since the change as well. Also using Firefox.  Haven't tested other browsers but I'm going to now after seeing this.

**Comment by AdrianGarside** [comment]
Please let me know if other browsers are indeed better behaved.

**Comment by tool666schism** [comment]
Tried a few different browsers including mobile and all of them seem to have the same stuttering. Freezing seems to have gone away however but it's still running worse for me after the change to camera.

**Comment by Kingsidorak** [comment]
I am only able to test in Firefox and Chrome.

In Firefox 2 out of 8 cameras are often not started, and clicking edit fixes that.

In Chrome 2 out of 8 cameras are not shown. I can click edit, and it doesn't fix it. Sometimes it even turns off a camera and enables one of the ones that was disables, but still always 2 are disabled in chrome.

Freezing still happens, but it seems like it's usually after a print finishes. I am not able to fully test the system yet due to ongoing mods to the printers

**Comment by AdrianGarside** [comment]
Added a new setting to bring back the image sensor camera: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.35-dev6

**Comment by AdrianGarside** [comment]
There’s no change in the new drop on how camera cameras are handled. Just a new switch that lets you switch to the previous image camera where that is better handled be browsers.

**Comment by Kingsidorak** [comment]
What do I change it to to try the other camera?

type: vertical-stack
cards:
  - show_state: true
    show_name: true
    camera_view: live
    type: picture-entity
    entity: camera.p1_00_camera
    name: P1 00 Metallics

**Comment by AdrianGarside** [comment]
You need the latest dev version and then there should be a new switch so you can choose which type you get. Only one is available at a time since the image sensor spams HA with updates ever 2 seconds:
![image](https://github.com/user-attachments/assets/0ce7f047-2877-4f57-99fb-eab70da74c6f)

**Comment by tool666schism** [comment]
Thanks @AdrianGarside for the update. Image sensor definitely works much better for me in regards to latency. Not really sure why that is.

**Comment by AdrianGarside** [comment]
Latency wise the image sensor is as fast as it can be - as soon as a complete image is received from the printer the image is updated in HA. With the camera sensor we're at the mercy of when it detects that a new image is available since there's no push mechanism. So it will be a bit slower. Layer on top of that some of the video cards in dashboards aren't real time (maybe they have an option to make them more live such as camera_view: live) and it gets harder to reliably show real time (or as real time as it gets with the P1 camera) video.
