### ISSUE TITLE
[Feature] Refactor code so a HA restart is not required after every update

### ISSUE THREAD

**Issue by mikenelson-io** [greghesp/ha-bambulab#662]
### Describe the feature

Every update of this integration requires an HA restart and I'm not sure why. Restarts are disruptive and can cause other issues depending on the users configuration.

### What device is this for?

A1

**Comment by Chreece** [comment]
I'm a bit confused, do you have any custom component (HACS) installed that doesn't need a HA update after updating it?
In my knowledge that is by design (from ha) and the only exception are the frontend components that only need a browser refresh.

**Comment by AdrianGarside** [comment]
This is not under the control of this integration.
