### ISSUE TITLE
[Feature] Having a Total Print Time Sensor

### ISSUE THREAD

**Issue by r4yzs** [greghesp/ha-bambulab#666]
### Describe the feature

Hello,
How can I easily get the total time an impression took to finish? We have the start and end times, but my formulas are a bit complex. Isn’t it possible to have a sensor that indicates the elapsed time since the beginning of the print?

### What device is this for?

A1

**Comment by AdrianGarside** [comment]
The problem with that is that it will constantly be updating every second making home assistant do work and spam the backing sensor database. You can create a template sensor yourself that tracks this which will avoid the perf cost being paid by everyone.
