### ISSUE TITLE
Camera output will not show under HA

### ISSUE THREAD

**Issue by RobertoCravallo** [greghesp/ha-bambulab#674]
### Describe the bug

When first installed, I had the camera view in HA. Not sure when or why, that broke at some point. After update?

### To Reproduce

check entity "image.p1s_kamera". For me, it shows not available.

### Expected Behaviour

Show the bed / project in the printer. Worked when first installed.

### What device are you using?

P1S

### Diagnostic Output

```shell
Can't drag anything into this field.
```

**Comment by RobertoCravallo** [comment]
[home-assistant_bambu_lab_2024-11-04T09-47-30.972Z.log](https://github.com/user-attachments/files/17616391/home-assistant_bambu_lab_2024-11-04T09-47-30.972Z.log)

<img width="723" alt="Einstellungen – Home Assistant 2024-11-04 10-53-46" src="https://github.com/user-attachments/assets/7f5777c3-5748-4e49-8794-b50767e191d1">

**Comment by AdrianGarside** [comment]
image.p1s_kamera was replaced with camera.p1s_kamera.

I haven't come up with a good way to auto-delete removed sensors on upgrades so you have to manually delete it.

**Comment by RobertoCravallo** [comment]
![2024-11-05 09-06-10](https://github.com/user-attachments/assets/1e39360d-60d3-4fd2-8e22-c70c3d017df6)

I am using camera.p1s_kamera. Removed the integration and reinstalled it, no change. Camera working fine from App on MAC and ANDROID.

All I get is the "idle" message:
![2024-11-05 09-08-39](https://github.com/user-attachments/assets/3031d441-1333-4ebc-b8e2-8fd9e8182a10)

**Comment by RobertoCravallo** [comment]
I am on 28-code1 and the cloud login went fine!! Behavior of the camera has unfortunately not changed...

**Comment by AdrianGarside** [comment]
The camera always says idle on the right. What happens when you click it to view the feed?

**Comment by RobertoCravallo** [comment]
![2024-11-05 09-35-43](https://github.com/user-attachments/assets/5b0ed2f0-8077-4ac5-8c57-bdd90d98b45a)

This is all I get and I did have a picture when I originally installed the integration a while back. Since I have Pi-Hole, Adguard, etc running, I tried on my mobile without going through my wifi. Same effect. It is as if the window won't open.

My REOLINK integration is showing a picture though....
![2024-11-05 09-41-12](https://github.com/user-attachments/assets/e809e8ac-c723-4161-a910-9c2eb75f5600)

![2024-11-05 09-41-26](https://github.com/user-attachments/assets/719580b5-fe12-4a80-9576-1e646dddbcc4)

**Comment by matte-oss** [comment]
Same issue ):

**Comment by AdrianGarside** [comment]
Ok, I will need debug logs to see if that sheds light on this.

**Comment by AdrianGarside** [comment]
@RobertoCravallo your logs show the attempt to connect to the printer to get the camera images is failing:

2024-11-04 10:20:16.483 ERROR (P1S-Chamber-166) [custom_components.bambu_lab.pybambu] Socket error: _ssl.c:983: The handshake operation timed out

The mqtt connection to the printer is also being lost from time to time:
2024-11-04 10:41:53.039 WARNING (P1S-Mqtt-67) [custom_components.bambu_lab.pybambu] On Disconnect: Printer disconnected with error code: 7

And there's this error which I don't think I recall seeing / fixing:

2024-11-04 10:47:25.632 DEBUG (SyncWorker_54) [custom_components.bambu_lab.pybambu] Getting accessToken from Bambu Cloud
2024-11-04 10:47:25.957 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code ('list index out of range',)

Is this with the new verification code support?

Actually there's general connection issues to the printer:

2024-11-04 10:20:03.132 ERROR (SyncWorker_17) [custom_components.bambu_lab.pybambu] Failed to send message to topic device/01P00A452900965/request

Is the access code correct for it?

**Comment by AdrianGarside** [comment]
The newer logs show the same thing - the printer is not responding to the attempt to connect to get camera images:
2024-11-05 18:08:22.536 ERROR (P1S-Chamber-169) [custom_components.bambu_lab.pybambu] A Chamber Image thread outer exception occurred:
2024-11-05 18:08:22.536 ERROR (P1S-Chamber-169) [custom_components.bambu_lab.pybambu] Exception. Type: <class 'TimeoutError'> Args: timed out

Is the IP address you set for it in the integration correct?

**Comment by RobertoCravallo** [comment]
![2024-11-05 21-33-14](https://github.com/user-attachments/assets/489f97a9-a47c-47e9-9b4b-1861b839f9c4)

Double checked, all is ok. Checked the code too, the integration pulled the correct code.
If the IP was wrong, would not the other data also be faulty?

All data seems correct, only the video oes not show.

**Comment by AdrianGarside** [comment]
I think the answer is yes but is the access code correct too? I did have one report of the access code returned from bambu cloud being wrong - that’s the only reason it’s present and editable.

FWIW the camera sensor and the image sensor are both driven from the same data which in your case is inaccessible so the earlier image sensor would be equally broken.

**Comment by RobertoCravallo** [comment]
You mean  "Zugangscode" from the screen shot? Yes, checked it.

**Comment by matte-oss** [comment]
Could this be an EU issue?
I am located in Italy

**Comment by RobertoCravallo** [comment]
The strange thing is, it initially worked. All Apps have no problem, just the integration is not happy. I have no idea where to search. Installed multiple times, boot and power down reboot. No change! All data but the video feed is there. I don't know when it broke, but it worked fine initially...

**Comment by matte-oss** [comment]
Update: for me giving the printer a static ip on my router and Reading to ha fixed the issue 🙂

**Comment by RobertoCravallo** [comment]
Mine has had a static IP from the get go...

**Comment by RobertoCravallo** [comment]
> the printer a static ip on my router and re-adding to ha fixed the issue

Tried a different static IP, no joy...  :-(

**Comment by AdrianGarside** [comment]
Unfortunately, I can't help you get this working. If the IP address and access code are both correct then there is something odd going on with your printer or your network routing. From your logs this isn't a bug in the integration - the printer isn't responding correctly.

**Comment by manfredsteger** [comment]
good morning, i installed latest version of hacs bambu lab integration and checked every entity. there are two entities for the camera the old one with _image._ and with _camera._ Go to settings > device > serach for bambu > open bambu device > get new Kamera entity. Works like a charm now.

![tut](https://github.com/user-attachments/assets/6afa7f2e-b85b-4595-b217-f7b642839cee)

![p1p-camera-works](https://github.com/user-attachments/assets/97ed7c6e-67f9-4656-8462-4f4128378af5)

**Comment by AdrianGarside** [comment]
What version did you upgrade from?

**Comment by RobertoCravallo** [comment]
> there are two entities for the camera the old one with _image._ and with _camera._

No, only one entity for me. The "image" one has been gone for a couple of weeks now. I am still stumped, why it is not working. Bothe image & camera initially worked. 

Which version are you guys on?

![2024-11-11 09-12-00](https://github.com/user-attachments/assets/6442a58b-fce8-4197-b41f-eb37dab819d0)

**Comment by manfredsteger** [comment]
> What version did you upgrade from?

every minor update in the past 2 weeks ... about 3 or 4 🤣

**Comment by manfredsteger** [comment]
> Which version are you guys on?

now 2.0.34

I used the grid card with picture entity:

```
type: grid
square: false
columns: 1
cards:
  - type: entities
    entities:
      - entity: fan.p1p_01s00a2c0501299_bauteillufter
        name: Bauteillüfter
      - entity: select.p1p_01s00a2c0501299_druckgeschwindigkeit
        name: Druckgeschwindigkeit
      - entity: fan.p1p_01s00a2c0501299_druckkopflufter
        name: Druckkopflüfter
      - entity: light.p1p_01s00a2c0501299_druckraumbeleuchtung
        name: Druckraumbeleuchtung
      - entity: fan.p1p_01s00a2c0501299_druckraumlufter
        name: Druckraumlüfter
    title: P1P_01S00A2C0501299
  - show_state: true
    show_name: true
    camera_view: auto
    type: picture-entity
    entity: camera.p1p_01s00a2c0501299_kamera
  - type: picture
    image_entity: image.p1p_01s00a2c0501299_titelbild
```

**Comment by AdrianGarside** [comment]
The image camera was replaced with a real camera but I haven’t yet found a way to tell HA to delete the removed sensor - the user has to do that manually. Otherwise it will stick around forever.

in the latest dev version you can choose which type you want. But when you switch between the other is left dead and needs to be manually deleted.

**Comment by AdrianGarside** [comment]
Since Roberto’s problem is specific to his network/printer and there does not appear to be anything the integration can do to fix it, I’m going to close this issue.

**Comment by RobertoCravallo** [comment]
![2024-11-11 17-57-17](https://github.com/user-attachments/assets/97ce0c83-8bfe-410a-92ea-d4e2e5a95261)

With the newest version the message has changed....

**Comment by AdrianGarside** [comment]
I fixed it to say Streaming since that's the kind of camera it is instead of being stuck saying Idle.

**Comment by RobertoCravallo** [comment]
Sorry for being such a bother! I had restarted HA multiple times, no joy. Today I closed down HA and PROXMOX and restarted everything from ZERO. JOY!!!!! The feed is back. 

Thank you for your FANTASTIC integration and your patience with me!!!!

![2024-11-14 09-22-59](https://github.com/user-attachments/assets/9d5a7786-4a6a-43a9-95c6-335aec41e52b)
