### ISSUE TITLE
[Bug] Cannt use the phone nomber to login Bambu Cloud China Server

### ISSUE THREAD

**Issue by 403-Forbidde** [greghesp/ha-bambulab#686]
### Describe the bug

![0532022ef135eec77544e6ce6dc5377](https://github.com/user-attachments/assets/22abb464-50a2-402e-8eeb-c01a54b5ea4e)
![3461554112e2e515d4ed9f4c4f33a49](https://github.com/user-attachments/assets/a522c2d6-ddee-499d-8bbf-3669a23712c6)

- Version: v2.0.29
- Located in the China
- Cannt login Bambu Cloud China server 
- in system log -- Failed to connect with error code ('list index out of range',)

### To Reproduce

1、select China
2、input phone number and password
3、click the next button
so we can see Failed to connect.Check credentials.

### Expected Behaviour

we want use phone number to login Bambu Cloud China server PLZZZZZZZZZZZZZZZZZZZZZZZZZZZZ  T.T

### What device are you using?

A1

### Diagnostic Output

```shell
Logger: custom_components.bambu_lab
Source: custom_components/bambu_lab/config_flow.py:157
integration: Bambu Lab (documentation, issues)
First occurred: 11:04:35 AM (76 occurrences)
Last logged: 11:34:33 AM

Failed to connect with error code ('list index out of range',)
Failed to connect with error code (429,)
```

### Log Extracts

```shell
2024-11-06 11:23:57.650 DEBUG (SyncWorker_17) [custom_components.bambu_lab.pybambu] Requested loginType: 
2024-11-06 11:23:57.652 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code ('list index out of range',)
```

**Comment by joshua76y** [comment]
same

**Comment by FeiiiikLV** [comment]
Same here with Europe login, also after the update all the devices went offline. When downgrading to an older version they all seem to be back online but are missing some of the data. 

 

Error code, when trying to force refresh on the newest branch, I also tried on the dev version.
Failed to perform the action button/press. Caught blocking call to putrequest with args (<urllib3.connection.HTTPSConnection object at 0x7f96ff944d10>, 'GET', '/v1/iot-service/api/slicer/setting?version=undefined') inside the event loop by custom integration 'bambu_lab' at custom_components/bambu_lab/pybambu/bambu_cloud.py, line 316: response = requests.get(self._get_rest_url('https://api.bambulab.com/v1/iot-service/api/slicer/setting?version=undefined'), headers=self._get_headers_with_auth_token(), timeout=10). (offender: /usr/local/lib/python3.12/site-packages/urllib3/connection.py, line 219: return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)), please create a bug report at https://github.com/greghesp/ha-bambulab/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#putrequest

**Comment by bjornskov** [comment]
Same here.

Trying to login for the first time:

`2024-11-06 13:55:35.788 ERROR (SyncWorker_33) [custom_components.bambu_lab.pybambu] Login attempt failed with error code: 403
2024-11-06 13:55:35.789 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code (403,)`

**Comment by TwoPlayer** [comment]
Same here for E-Mail Login in Europe, Debug Log, shows, that I was blocked:
```
2024-11-06 15:53:47.992 DEBUG (SyncWorker_62) [custom_components.bambu_lab.pybambu] login()
2024-11-06 15:53:47.992 DEBUG (SyncWorker_62) [custom_components.bambu_lab.pybambu] Getting accessToken from Bambu Cloud
2024-11-06 15:53:48.156 ERROR (SyncWorker_62) [custom_components.bambu_lab.pybambu] Login attempt failed with error code: 403
2024-11-06 15:53:48.157 DEBUG (SyncWorker_62) [custom_components.bambu_lab.pybambu] Response: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->
<style>body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>
<!--<![endif]-->


</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> bambulab.com</h2>
      </div><!-- /.header -->

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div><!-- /.captcha-container -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">8de5ea47cb28c811</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">87.79.185.11</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script>
  window._cf_translation = {};
  
  
</script>

<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'8de5ea47cb28c811',t:'MTczMDkwNDgyOC4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>
</html>

2024-11-06 15:53:48.158 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code (403,)
```

**Comment by flying19880517** [comment]
same
2024-11-07 10:10:25.737 ERROR (SyncWorker_37) [custom_components.bambu_lab.pybambu] Login attempt failed with error code: 403
2024-11-07 10:10:25.738 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code (403,)

**Comment by AdrianGarside** [comment]
Cloudflare issue is fixed with #698 
For the phone number login case, please re-test with the newest version (2.0.30) as I also made a fix to the logging that affects what I will see for your failure repro.

**Comment by flying19880517** [comment]
> Cloudflare issue is fixed with #698 For the phone number login case, please re-test with the newest version (2.0.30) as I also made a fix to the logging that affects what I will see for your failure repro.

test 2.0.30 also can't login
2024-11-07 14:42:42.810 ERROR (SyncWorker_30) [custom_components.bambu_lab.pybambu] Response not understood: <bound method Response.json of <Response [200]>>
2024-11-07 14:42:42.811 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code ('list index out of range',)

**Comment by flying19880517** [comment]
> @flying19880517 I need to add more logging to shed light on your failure path. But that might also be affected by the cloudscraper response object differences.我需要添加更多的日志来帮助分析你的程序出错的原因。但是这也可能会受到云抓取响应对象差异的影响。

https://github.com/SoftFever/OrcaSlicer/blob/1088d0a6c713250ee3d14da791e27b76b4339363/src/slic3r/GUI/GUI_App.cpp#L1107
Different country_code use different api server, in China, it's api.bambulab.cn。

**Comment by AdrianGarside** [comment]
Yes, the integration already uses the china specific api endpoints.

**Comment by flying19880517** [comment]
@AdrianGarside 
![image](https://github.com/user-attachments/assets/ffd0d678-42c3-46d1-a449-f7c5907daeeb)

**Comment by AdrianGarside** [comment]
Perfect. That's what I was wanting to get from the logs. Fix coming up.

**Comment by 403-Forbidde** [comment]
> Still getting an error in EU for login after 2.0.30 update.

Same T.T 
Still getting an error in China for login after 2.0.30 update.

**Comment by AdrianGarside** [comment]
Please try this version and let me know if it fixes phone number login in China:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.31

For the folk hitting issues in the EU still - please provide new debug logs of a failure.

**Comment by flying19880517** [comment]
@AdrianGarside success login and add

**Comment by AdrianGarside** [comment]
Ok, I'm going to close this issue out. For EU folks still having connection issues - please open a new issue with updated logs from v2.0.31.
