### ISSUE TITLE
[Feature] Enable/Disable Printer Camera

### ISSUE THREAD

**Issue by CaptainKills** [greghesp/ha-bambulab#694]
### Describe the feature

At the moment, the camera of my A1 printer is always on when connected to Home Assistant. I'd like to have a feature to turn off the camera when I am not using it. This can be similar to how it is integrated into Bambu Studio. I don't want the camera to film me all the time.

I could use the integrated physical lens cover, but when I am away and forgot to open the cover, I still cannot view my print when I am away. Making a toggle or on/off button to enable/disable the camera would be a great addition.

### What device is this for?

A1

### Other Information

I have looked if there was a way to do it currently, but it does not seem to exist. If there is anything I missed then please let me know.

**Comment by Sven177** [comment]
Same opinion here for the A1 Mini - would be nice being able to switch it on and off...

**Comment by Lappun0** [comment]
Same here, would be pretty nice not having it film all the time

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.35-dev4
