### ISSUE TITLE
[Bug] Still can't login - cloudflare is blocking once again even using cloudscraper

### ISSUE THREAD

**Issue by FeiiiikLV** [greghesp/ha-bambulab#702]
### Describe the bug

Tried logging in, but still get error after the v2.0.31

### To Reproduce

Tried logging in using Bambu Cloud

### Expected Behaviour

.

### What device are you using?

P1P

### Diagnostic Output

```shell
Link to the log file:
https://www.dropbox.com/scl/fi/yd6bef2dzc383y5xl1d22/home-assistant_bambu_lab_2024-11-07T08-11-54.195Z.log?rlkey=nizonttax9tf25fmstjq4um7d&dl=0
```

### Other Information

All the connected devices function perfectly.

**Comment by AdrianGarside** [comment]
cloudflare has already adapted to the switch to the cloudscraper library. Back to square one :(

**Comment by AdrianGarside** [comment]
@t0nyz0 's test script is still able to login but the equivalent code running inside home assistant is getting cloudflared again.

**Comment by AdrianGarside** [comment]
The test script run inside my home-assistant docker also then fails.

**Comment by DavideBar** [comment]
@AdrianGarside have you checked Flaresolver? I don't know how it works but some torrent trackers need flaresolver to bypass Cloudflare.

https://github.com/FlareSolverr/FlareSolverr

**Comment by t0nyz0** [comment]
Hmm whats weird is the test script still works for me @AdrianGarside 
##
![image](https://github.com/user-attachments/assets/b47a179e-3020-42c2-b42f-0a57692599af)

**Comment by t0nyz0** [comment]
I've noticed that when I try to translate the python code into javascript (node.js) that I cant seem to get it to work. I've been trying to determine the differences in how the code functions in python vs node.

**Comment by AdrianGarside** [comment]
> Hmm whats weird is the test script still works for me @AdrianGarside

The script works for me in the WSL host. It doesn't work inside my home-assistant docker instance. cloudscraper was a slightly older version in the WSL host so I upgraded it to match home-assistant to see if it broke but it still kept working in WSL.

**Comment by t0nyz0** [comment]
Interesting, that does track with what I am seeing in my bambuboard app, its also running in a docker instance. I'll keep digging.

**Comment by AdrianGarside** [comment]
I'm stumped. I can't work out what the difference is between failure inside the home-assistant docker instance and success outside it in the WSL host. Debug output from cloudscraper showed only a minor ', br' difference:
< Accept-Encoding: gzip, deflate, br
in home-assistant but adding that to the headers in the script didn't change the behavior in WSL.

**Comment by AdrianGarside** [comment]
New fix attempt: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.33

**Comment by caux** [comment]
Works for me!

**Comment by virus514** [comment]
> New fix attempt: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.33

That also works for me! Thanks a lot!

**Comment by Datastore24Kirill** [comment]
China phone number not working

`2024-11-08 16:07:28.285 DEBUG (SyncWorker_6) [custom_components.bambu_lab.pybambu] login()
2024-11-08 16:07:28.286 DEBUG (SyncWorker_6) [custom_components.bambu_lab.pybambu] Getting accessToken from Bambu Cloud
2024-11-08 16:07:29.113 ERROR (SyncWorker_6) [custom_components.bambu_lab.pybambu] Login attempt failed with error code: 403
2024-11-08 16:07:29.114 DEBUG (SyncWorker_6) [custom_components.bambu_lab.pybambu] Response: '<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>

<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> bambulab.cn</h2>
      </div>
      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
              <span class="cf-no-screenshot error"></span>
          </div>
        </div>
      </div>
      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>
            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>
          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>
            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div>
      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">8df5c94a38fc3f4e</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">81.5.84.10</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>
    </div>
  </div>
  <script>
  window._cf_translation = {};
</script>
<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'8df5c94a38fc3f4e',t:'MTczMTA3MTI0OS4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>
</html>
'
2024-11-08 16:07:29.118 ERROR (MainThread) [custom_components.bambu_lab] Failed to connect with error code (403,)`
