### ISSUE TITLE
[Bug] access bambu api constantly

### ISSUE THREAD

**Issue by cataglyphis** [greghesp/ha-bambulab#704]
### Describe the bug

Recently, while using ha-bambulab, I noticed it was consuming a lot of data. After analyzing the network traffic, I found that it was constantly using Bambu's cloud interface, making approximately 300 calls every 5 minutes. Is this normal? I'm concerned that the high number of requests might lead to my account being suspended.

### To Reproduce

none

### Expected Behaviour

none

### What device are you using?

A1

### Diagnostic Output

```shell
none
```

**Comment by AdrianGarside** [comment]
That does not sound right. Can you enable debug logs and see if that shes light on the frequent calls. Or did your investigation already ascertain what the end point for those 300 calls is?

**Comment by flying19880517** [comment]
@AdrianGarside I think I have same problem, Cloudflare block requests, it connect every second, 5min = 600 times
[home-assistant.log](https://github.com/user-attachments/files/17659119/home-assistant.log)

**Comment by flying19880517** [comment]
@AdrianGarside I can't test it, I have already blocked and can not add device (it‘s too many requests and I deleted it before).

**Comment by AdrianGarside** [comment]
I'm going to resolve this fixed as the bug above would definitely cause these symptoms.
