### ISSUE TITLE
[Bug] Camera Not Loading on HA

### ISSUE THREAD

**Issue by retracdev** [greghesp/ha-bambulab#707]
### Describe the bug

I click on the camera, but nothing appears. It worked before but now doesn’t.
![IMG_3146](https://github.com/user-attachments/assets/effb667c-c5a7-46c2-9130-58f43a2f8b35)

### To Reproduce

By looking at the entity for the printer called **Camera** on the printer. _At first when installed it worked with the camera perfectly but now it does not._
![IMG_3146](https://github.com/user-attachments/assets/82a1b8ad-311e-446b-a5e8-774af8f586e0)

### Expected Behaviour

Show the printer camera feed.

### What device are you using?

X1C

### Diagnostic Output

```shell
N/A
```

**Comment by AdrianGarside** [comment]
See #221
