### ISSUE TITLE
[Bug] Failed to connect. Check credentials.

### ISSUE THREAD

**Issue by boris327** [greghesp/ha-bambulab#721]
### Describe the bug

The integration is stopped working and when I try to login I get "Failed to connect. Check credentials.
"

### To Reproduce

Logger: custom_components.bambu_lab
Source: custom_components/bambu_lab/config_flow.py:158
integration: Bambu Lab ([documentation](https://github.com/greghesp/ha-bambulab), [issues](https://github.com/greghesp/ha-bambulab/issues))
First occurred: 08:33:25 (6 occurrences)
Last logged: 08:42:35

### Expected Behaviour

Failed to connect. Check credentials.

### What device are you using?

A1

### Diagnostic Output

```shell
Logger: custom_components.bambu_lab
Source: custom_components/bambu_lab/config_flow.py:158
integration: Bambu Lab (documentation, issues)
First occurred: 08:33:25 (6 occurrences)
Last logged: 08:42:35
```

**Comment by bohoffi** [comment]
Sadly it's the same issue for me as well using `v2.0.33` and trying to login using `Europe` region:
```
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.bambu_lab
Quelle: custom_components/bambu_lab/config_flow.py:158
Integration: Bambu Lab (Dokumentation, Probleme)
Erstmals aufgetreten: 08:43:46 (3 Vorkommnisse)
Zuletzt protokolliert: 08:45:10

Failed to connect with error code (403,)
```

**Comment by Bjoern4877** [comment]
Ich habe 3 Bambus, vorgestern funktionierte es nicht , gestern ging es bei einem.
Heute wollte ich den zweiten einrichten, was wieder nicht funktionierte

**Comment by bohoffi** [comment]
I was able to finish logging in and adding my P1P using `v2.0.34-dev4`.

**Comment by peter202411** [comment]
Integration is not connecting to cloud.  I get "Failed to connect. Check credentials.

**Comment by miknuc** [comment]
same with me. It's a fresh install of ha-bambulab, HA core is 2024.9.2

**Comment by Datastore24Kirill** [comment]
v2.0.34-dev4 - solved the problem

**Comment by AdrianGarside** [comment]
Please included your integration version in your reports or they're useless. There are currently changes in every version to the login authentication to try and get past cloudflare. Without the version your failure data points are useless to me.

**Comment by AdrianGarside** [comment]
If you are still having connection issues with v2.0.34, please open a new issue. With debug logs.
