### ISSUE TITLE
[Feature] Add multiple printers at once

### ISSUE THREAD

**Issue by Datastore24Kirill** [greghesp/ha-bambulab#722]
### Describe the feature

When Bambu Lab entered authorization codes, we encountered a problem. If you have several printers, then when adding a printer you need to enter a phone number, password and verification SMS code, after adding 4 printers in a row, SMS stops coming and you need to wait an indefinite amount of time before adding more. 

Please consider the option of authorization once and saving tokens for further addition of printers, or allow adding more than one printer at a time

### What device is this for?

P1S

**Comment by AdrianGarside** [comment]
Multiple at once it's possible but I am able to find and re-use existing credentials to skipp authentication. Please try this version:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.35-dev2
