### ISSUE TITLE
[Feature] ASA-CF support

### ISSUE THREAD

**Issue by honcheng** [greghesp/ha-bambulab#731]
### Describe the feature

Current implementation does not recognize new Bambu Lab ASA-CF filament.

https://store.bambulab.com/products/asa-cf

### What device is this for?

AMS

### Other Information

![CleanShot 2024-11-12 at 14 24 42@2x](https://github.com/user-attachments/assets/85556fa9-3daa-4f86-900a-fb51ad8ea89b)

**Comment by AdrianGarside** [comment]
Fixed with #752
