### ISSUE TITLE
Log Out / Update Credentials

### ISSUE THREAD

**Issue by boasist** [greghesp/ha-bambulab#774]
### Discussed in https://github.com/greghesp/ha-bambulab/discussions/772

<div type='discussions-op-text'>

<sup>Originally posted by **boasist** November 21, 2024</sup>
Since Bambu has an issue with apple relay accounts, I've changed everything and moved accounts entirely. Yet since, the integration isn't working...of course.

I've tried disabling, reloading, and force updating, but nothing prompts for a password anymore. 

How can I log out/update my credentials?</div>

**Comment by AdrianGarside** [comment]
Oops. That will probably be a side effect of the change to reuse existing credentials if they still work for authentication. Have you tried completely removing the integration and readding it?

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.39-dev2
