### ISSUE TITLE
[Feature] Device trigger (or binary sensor) during timelapse 

### ISSUE THREAD

**Issue by denkyem** [greghesp/ha-bambulab#777]
### Describe the feature

When the printer’s timelapse is active, it would be great to have an event or even a binary_sensor triggered when the print head moves to the left to take the photo.
This way, we could create automations to make timelapses with other cameras of better quality.

### What device is this for?

A1

**Comment by AdrianGarside** [comment]
This is not exposed in the data feed from the printer. The closest will be the layer number changing but that is likely after the photo is taken.

**Comment by AdrianGarside** [comment]
There’s also a 1-2 second delay in receiving the latest data so you couldn’t drive anything real time off it.

**Comment by Alvie** [comment]
I had the same idea 😅 alas, will have to find a different way to do it haha
