### ISSUE TITLE
A Chamber Image thread outer exception occurred: / Exception. Type: <class 'ConnectionRefusedError'> Args: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by Benj-HaRRison** [greghesp/ha-bambulab#779]
### Home Assistant Version

core-2024.11.3

### Bambu Lab Integration Version

2.0.38

### Describe the bug

The live view of the printer camera does not work. At the same time, in the HA log immediately after loading HA there are errors that occur at the same time (most likely related).

### To Reproduce

Error in log, after HA loaded

### Expected Behaviour

Don't know

### What device are you using?

P1P

### Diagnostic Output

```shell
Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.bambu_lab.pybambu
Источник: custom_components/bambu_lab/pybambu/bambu_client.py:210
интеграция: Bambu Lab (документация, проблемы)
Первое сообщение: 02:11:56 (12 сообщений)
Последнее сообщение: 02:12:12

A Chamber Image thread outer exception occurred:

Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.bambu_lab.pybambu
Источник: custom_components/bambu_lab/pybambu/bambu_client.py:211
интеграция: Bambu Lab (документация, проблемы)
Первое сообщение: 02:11:56 (12 сообщений)
Последнее сообщение: 02:12:12

Exception. Type: <class 'ConnectionRefusedError'> Args: [Errno 111] Connection refused
```

**Comment by AdrianGarside** [comment]
Check your IP address for the printer is correct. Either the IP address or the access code is wrong.

**Comment by Benj-HaRRison** [comment]
> Check your IP address for the printer is correct. Either the IP address or the access code is wrong.

This solution is true.
Thank you!
