### ISSUE TITLE
[Feature] Add Mac addres to device `identifiers`

### ISSUE THREAD

**Issue by bjoernmayer** [greghesp/ha-bambulab#780]
### Describe the feature

Devices might be added to HomeAssistant from multiple integrations. If Home Assistant recognizes them as the same device, their entities and properties are merged into one device.

Would you be able to add to Printers Mac Address as another identifier?
See https://developers.home-assistant.io/docs/device_registry_index/#device-properties

### What device is this for?

A1

**Comment by bjoernmayer** [comment]
For example via my routers integration. I have my presence sensor provided by both: Aqara and  Fritz! Integration

**Comment by AdrianGarside** [comment]
The printers are already uniquely identified by serial number. Adding the MAC address, even if I could, would not change anything since there is a 1:1 mapping of serial number to MAC address.

I don’t know what you mean above.

**Comment by AdrianGarside** [comment]
I see. Unfortunately, I don't have access to the mac address.
