### ISSUE TITLE
[Bug] On Disconnect: Printer disconnected with error code: 0

### ISSUE THREAD

**Issue by Benj-HaRRison** [greghesp/ha-bambulab#781]
### Home Assistant Version

core-2024.11.3

### Bambu Lab Integration Version

2.0.38

### Describe the bug

After my printer Bambu Lab P1P is loaded, all in HA working, but log HA have warning "On Disconnect: Printer disconnected with error code: 0".

### To Reproduce

The problem appears after turning on the printer (idle state)

### Expected Behaviour

It is not known what this warning affects, all functionality in HA works (but if there is a warning, it means something is wrong).

### What device are you using?

P1P

### Diagnostic Output

```shell
This error occurred in custom integration.

Logger: custom_components.bambu_lab.pybambu
Source: custom_components/bambu_lab/pybambu/bambu_client.py:443
integration: Bambu Lab (documentation, problems)
First message: 21:00:41 (5 messages)
Last message: 21:05:00

On Disconnect: Printer disconnected with error code: 0
```

**Comment by AdrianGarside** [comment]
So the repro for this is printer off and then you get a connection error *after* turning it on?

**Comment by AdrianGarside** [comment]
No logs provided and no response to questions so closing as inactionable.
