### ISSUE TITLE
[Feature] Check filament price

### ISSUE THREAD

**Issue by BenGeba** [greghesp/ha-bambulab#782]
### Describe the feature

I have my own filament profiles that I use. I set the price in the profile so that the price is calculated correctly in the slicer. Is there a way to additionally query the price and specify it as an attribute?

### What device is this for?

AMS

**Comment by t3chguy** [comment]
I don't believe so, https://api.bambulab.com/v1/iot-service/api/slicer/setting?version=1.10.0.89 shows you what sort of data is available, and the slicer filament profiles are not there

**Comment by AdrianGarside** [comment]
Currently I don't know of any way to do this.
