### ISSUE TITLE
[Feature] BBL PLA-Wood to list of filaments

### ISSUE THREAD

**Issue by Cyberlytical-LLC** [greghesp/ha-bambulab#785]
### Describe the feature

Could you please add Bambu's PLA-Wood to the AMS filament JSON? I get and unknown error in HA when I place it in the AMS. 

Thank you for all you do! 

### What device is this for?

AMS

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.39-dev6
