### ISSUE TITLE
[Feature] Configuration option to disable camera stream

### ISSUE THREAD

**Issue by markfrancisonly** [greghesp/ha-bambulab#790]
### Describe the feature

I use Frigate to make a single connection to the Bambu X1C RTSPS camera feed for recording while simultaneously restreaming the camera feed to multiple tablet displays via go2rtc.

Opening additional streams (e.g., with HA-BambuLab integration or possibly Bambu Studio) generates wireless traffic.  Multiple concurrent streams is likely to cause instability in the X1C server.

To mitigate these issues and limit the number of camera connections to the printer, could we add an option in the HA-BambuLab integration to disable the camera or change the link to a restreaming proxy? This would help reduce network overhead and improve system stability from persons in my same boat

### What device is this for?

X1C

**Comment by AdrianGarside** [comment]
That already exists:
![image](https://github.com/user-attachments/assets/5dcfa1ec-545b-40c7-974f-c7e9780f0b6d)
