### ISSUE TITLE
[Bug] No connection to printer (X1C)

### ISSUE THREAD

**Issue by Puller** [greghesp/ha-bambulab#792]
### Home Assistant Version

2024.12.3

### Bambu Lab Integration Version

v2.0.38

### Describe the bug

When setting up the integration, everything works fine up to the point, where I have to set up the LAN connection. 
<img width="620" alt="Bildschirmfoto 2024-12-17 um 14 49 44" src="https://github.com/user-attachments/assets/cc7bc9f9-cedf-4dd5-ad4b-02cecde8f06b" />

I'm sure, the IP address is correct, but it still won't connect. Restarted everything, but still no connection!

### To Reproduce

1. Install Bambulab from HACS
2. Add integration
3. Fill in the cloud credentials, wait for the token via Email and add it
4. Fill inn correct IP address
5. Boom... no luck!

### Expected Behaviour

Add printer integration after connection

### What device are you using?

X1C

### Diagnostic Output

```shell
No Output because the integration canÄt be installed...
```

**Comment by bobster22388** [comment]
I am having the same issue when trying to setup my P1S

**Comment by AdrianGarside** [comment]
Please provide debug logs. And also double check the access code retrieved from the bambu cloud api matches your printer. In a single case it was seen that it didn't.

**Comment by AdrianGarside** [comment]
Adding this to your configuration.yaml (and restarting home assistant allows debug logs to be connected from the initial integration setup:

logger:
  default: info
  logs:
    custom_components.bambu_lab: debug

**Comment by AdrianGarside** [comment]
Not actionable without logs and I'm not able to reproduce any connection issues adding a printer with the correct IP address and access code.
