### ISSUE TITLE
[Bug]The cloud login function is not available in China

### ISSUE THREAD

**Issue by windy0220** [greghesp/ha-bambulab#793]
### Home Assistant Version

2024.12.4

### Bambu Lab Integration Version

v2.0.38

### Describe the bug

我选择的地区是china，账号处输入的是手机号，填入密码后，点击下一步，会出现一个邮箱验证码需要填写，在中国区的makerworld上并没有设置邮箱的地方，我的手机也没有收到任何验证码
-------------------------------------------------------------------------------------
I chose China as the region, entered my mobile phone number in the account field, filled in my password, and clicked Next. An email verification code would appear, but there was no email address set up on MakerWorld in China, and my phone did not receive any verification code.

### To Reproduce

![QQ20241220-154147](https://github.com/user-attachments/assets/a5244874-a605-4df8-9c11-75ca7b9e5bd0)

### Expected Behaviour

应该弹出可以输入手机验证码的输入框，并发送手机验证码到手机
---------------------------
An input box should pop up where you can enter the mobile verification code and send the mobile verification code to your phone.

### What device are you using?

P1S

### Diagnostic Output

```shell
Does not exist
```

**Comment by peach0x33a** [comment]
same problems

**Comment by AdrianGarside** [comment]
Please can you provide debug logs and I'll see if I can work out what's wrong. It's difficult though as I have no way to test.

**Comment by windy0220** [comment]
I didn't find any logs about bambulab in the core logs. It may be that the installation has not been successful. When I enter the account password on the interface and click Next, the interface will be called. These response information are all obtained from the browser. I don't know if it helps. I have hidden all sensitive fields.

`{
    "type": "form",
    "flow_id": "01JFPB0CQ6DRPG05KT15Y8F0ZS",
    "handler": "bambu_lab",
    "data_schema": [
        {
            "selector": {
                "select": {
                    "options": [
                        {
                            "value": "AsiaPacific",
                            "label": "Asia Pacific"
                        },
                        {
                            "value": "China",
                            "label": "China"
                        },
                        {
                            "value": "Europe",
                            "label": "Europe"
                        },
                        {
                            "value": "NorthAmerica",
                            "label": "North America"
                        },
                        {
                            "value": "Other",
                            "label": "Other"
                        }
                    ],
                    "mode": "list",
                    "sort": false,
                    "multiple": false,
                    "custom_value": false
                }
            },
            "name": "region",
            "required": true,
            "default": "China"
        },
        {
            "selector": {
                "text": {
                    "type": "email",
                    "multiline": false,
                    "multiple": false
                }
            },
            "name": "email",
            "required": true,
            "default": "186*******"
        },
        {
            "selector": {
                "text": {
                    "type": "password",
                    "multiline": false,
                    "multiple": false
                }
            },
            "name": "password",
            "required": true,
            "default": "*******"
        },
        {
            "selector": {
                "text": {
                    "type": "text",
                    "multiline": false,
                    "multiple": false
                }
            },
            "name": "verifyCode",
            "required": true,
            "default": ""
        }
    ],
    "errors": {
        "base": "verifyCode"
    },
    "description_placeholders": null,
    "last_step": false,
    "preview": null,
    "step_id": "Bambu"
}`

**Comment by windy0220** [comment]
I logged in to makerworld.com.cn and obtained the following interface information, I hope it will be helpful to you
Login request interface, if a verification code is required, this interface exports the 

**mobile phone verification code**
https://bambulab.cn/api/sign-in/form
Post
{"account":"[Mobile number]","password":"[Password]","apiError":""}
{"tfaKey":"","loginType":""}

**If a mobile phone verification code is required, it is equivalent to**
{"tfaKey":"","loginType":"verifyCode"}

**If you need to send the verification code again, call the following interface**
https://bambulab.cn/api/v1/user-service/user/sendsmscode
Post
{"phone":"[Mobile phone]","type":"[codeLogin]"}
{}

**Interface for logging in with a verification code**
https://bambulab.cn/api/sign-in/form
Post
{"account":"[Mobile phone]","code":"[Verification code]"}
{"tfaKey":"","loginType":""}

**Comment by Charshell** [comment]
Same here, asked for mail verification code, hard time in china🥲

**Comment by AdrianGarside** [comment]
To enable debug logs before the integration is installed, you can edit your configuration.yaml to include:
logger:
  logs:
    custom_components.bambu_lab: debug

This will allow capturing of the debug logs during the initial authentication and hopefully shed light on if this is a bug in the integration or if we need to explicitly request a phone code (you do not with email - that gets sent automatically).

The UI text is confusing - it says email code but it's the same flow for both email and phone. I will fix the wording to reflect that.

**Comment by AdrianGarside** [comment]
The only difference between email and phone is that if you enter an expired code it will automatically request an new email code - which won't work if you're using a phone for the account name.

**Comment by AdrianGarside** [comment]
Fixed text now mentions phone too:
![image](https://github.com/user-attachments/assets/26ec0f74-c14b-41a6-9ee8-69e26321a6b4)

But if the attempt to login with phone doesn't automatically send the phone code as it used to, I'll need to make a further fix.

I have observed that many repeated attempts to login with email get you into a throttled state where it won't automatically send the email code. I don't have a way currently in the UX to trigger a request for a new code.

**Comment by AdrianGarside** [comment]
Added a way to request a code to be sent:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.39-dev5

**Comment by Charshell** [comment]
> Added a way to request a code to be sent: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.39-dev5

Amazing! Worked! Thanks a lot!

**Comment by windy0220** [comment]
> Added a way to request a code to be sent: https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.39-dev5

The development version has been successfully connected. Thank you for your work.
There is another small problem. When entering the mobile phone number, there will be an error message because the front-end verification must include @.

**Comment by AdrianGarside** [comment]
Ha, no one ever mentioned that to me before. That's an easy fix.

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.40-beta1

**Comment by windy0220** [comment]
> https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.40-beta1

Great! no errors reported.

**Comment by AdrianGarside** [comment]
Can you please try https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.40-beta1 to see if the addition of checking the ssl certificate chain breaks connection to the China specific mqtt server?

**Comment by windy0220** [comment]
> Can you please try https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.40-beta1 to see if the addition of checking the ssl certificate chain breaks connection to the China specific mqtt server?

I have set up an SSL environment locally, and the test shows that it can connect to Bambu Cloud normally, and the status of related entities is also normal.
![Uploading QQ20250105-184531.png…]()
