### ISSUE TITLE
MQTT TLS Issue in Latest Update

### ISSUE THREAD

**Issue by greghesp** [greghesp/ha-bambulab#8]
This is a note to add functionality to support the latest firmware update which has added TLS to MQTT.

To get this to work, you must now use port `8883`, as well as enabling TLS with the username `bblp` and the LAN Access Code from the printer as the password ,and disabling certification validation

**Comment by AdrianGarside** [comment]
mqtt.username_pw_set(username, password=None) - need to use before mqtt.connect()
mqtt.tls_set() or mqtt.tls_set_context() to enable tls - needs to be used before mqtt.connect()

**Comment by AdrianGarside** [comment]
I think that's all that's needed (plus plumbing of the lan code I added in my other PR through as the password). But I have a P1P so I cannot test this. And I'm not sure if I can make both work in the short term until the P1P gets tls enabled too.
