### ISSUE TITLE
[Feature] End print hour to local user our

### ISSUE THREAD

**Issue by zoic21** [greghesp/ha-bambulab#806]
### Describe the feature

Hello,

To begin thanks for your integration, it's work perfectly and I can disable cloud mode with it to work only on local mode and get notification in case of issue or end print.

Only one thinks I see this morning it's end hour, it's seem to be in UTC and not in local hour (CET for me). I miss something or it's an evolution ?

Thanks in advance

### What device is this for?

A1 Mini

**Comment by AdrianGarside** [comment]
It's always been stored in UTC - home assistant converts to local time automatically. I'm not sure why that wouldn't be happening for you.

**Comment by AdrianGarside** [comment]
I cannot repro this and no logs were provided although I doubt they would help since home assistant decides how to show time values.
