### ISSUE TITLE
[Bug] random translation of entity_ids 

### ISSUE THREAD

**Issue by lx05** [greghesp/ha-bambulab#810]
### Home Assistant Version

2024.12.5

### Bambu Lab Integration Version

2.0.39

### Describe the bug

Entity_IDs are in German language, even though I dont want this. There is a similar feature request #773, i dont know why it was closed. This seems quite major as the idea of HASS is that entity_ids are universal. No other integration I use tries to translate entity_ids. This makes it also quite hard to build dashboards, since the entity_ids arent consistent. 

Please fix this or leave the user the choice if he wants to translate the entity_ids!

### To Reproduce

Install Integration and add printer, then sometimes all entity_ids are german

### Expected Behaviour

Entity_IDs should be always the same (preferably english) and friendly name is changed according to language.

### What device are you using?

P1S

### Diagnostic Output

```shell
-
```

**Comment by AdrianGarside** [comment]
Support for translation of entity ids was added to home assistant core in 2023 and is now the expected way integrations should behave:
https://developers.home-assistant.io/docs/internationalization/core/#name-of-entities
although many integrations do not yet. The changes to this integration to align to that were done by a core home assistant developer in #178. Feel free to reach out to him to discuss it further.
