### ISSUE TITLE
[Bug] <Replace this part>

### ISSUE THREAD

**Issue by cinghialino** [greghesp/ha-bambulab#811]
### Home Assistant Version

2024.12.5

### Bambu Lab Integration Version

v2.0.39

### Describe the bug

the entity 

`sensor.[printer]_target_bed_temperature`

should be

`'sensor.[printer]_bed_target_temperature`

### To Reproduce

it's really the way the integration sets it up.

### Expected Behaviour

bed_target_temperature

### What device are you using?

P1S

### Diagnostic Output

```shell
irrelevant to the issue
```

**Comment by AdrianGarside** [comment]
I really want to make this fix too. But it breaks all existing dashboards that reference those sensors/numbers.
